clisp voz-full-1-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-1-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-2-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-2-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-3-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-3-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-4-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-4-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-5-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-5-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-6-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-6-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-7-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-7-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-8-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-8-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-9-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-9-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-10-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-10-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-11-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-11-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-12-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-12-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-13-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-13-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-14-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-14-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-15-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-15-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-16-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-16-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-17-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-17-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-18-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-18-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-19-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-19-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-full-20-levinverb_nofunc_roleexp_prep_sty.lisp > voz-full-20-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
