clisp voz-eval-1-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-1-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-2-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-2-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-3-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-3-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-4-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-4-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-5-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-5-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-6-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-6-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-7-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-7-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-8-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-8-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-9-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-9-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-10-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-10-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-11-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-11-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-12-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-12-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-13-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-13-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-14-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-14-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-15-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-15-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-16-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-16-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-17-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-17-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-18-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-18-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-19-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-19-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
clisp voz-eval-20-levinverb_nofunc_roleexp_prep_sty.lisp > voz-eval-20-levinverb_nofunc_roleexp_prep_sty.lisp.txt &
