;; --------------------------------------------------------------------
;; This file has been automatically generated by SAM Story Editor v1.11
;; Santiago Ontanon
;; Jichen Zhu
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-03
     (:discourse
       (:clauses
         (phase1 (:s t1 t2 t3 t4 t5 t6 t7))
       )
       (:templates
         ;; The door remains in its place.
         ;;  It occurs to Enrique that he has brought his diving knife.
         ;;  He fetches it from near his ankle and works the titanium blade through the rust.
         ;;  The door eventually comes loose and sinks to the ocean floor.
         ;;  Through the opening, he looks inside the ship but only sees more blackness.
         ;;  Enrique?s head is throbbing with pain and he is almost running out of air.
         ;;  He knows that he should ascend immediately, but 
         (t1 "The " (door "door") " remains in its place.")
         (t2 " It occurs to " (E2  (Enrique "Enrique") " that he has brought his diving " (knife "knife") ) ".")
         (t3 " " (E3  (Enrique "He") " fetches " (knife "it") ) " from near his ankle and works the titanium " (E6  (knife "blade") " through the " (door "rust") ) ".")
         (t4 " The " (door "door") " eventually comes loose and " (E9  (door "sinks") " to the ocean " (floor "floor") ) ".")
         (t5 " Through the opening, " (E11  (Enrique "he") " looks inside the " (ship "ship") ) " but only " (E12  (Enrique "sees") " more " (darkness "blackness") ) ".")
         (t6 " " (E13  (Enrique "Enrique") "?s head is " (pain "throbbing") ) " with pain and he is almost " (E14  (Enrique "running") " out of " (air "air") ) ".")
         (t7 " " (E15  (Enrique "He") " knows that he should " (ascent "ascend") ) " immediately, but ")
         (t10 (E8  (door "Door") " similar to " (freedom "freedom") ) ".")
         (t11 (E10  (ship "Ship") " like " (boat "boat") ) ".")
       )
     )
     (:structure
       (common
         (:entities
           (human :type animate)
           (location :type entity)
           (emotion :type entity)
           (condition :type entity)
           (vehicle :type inanimate)

           (door :type inanimate)
           (Enrique :type human)
           (equipment :type inanimate)
           (knife :type equipment)
           (ship :type vehicle)
         )
         (:expressions
         )
       )
       (phase1
         (:entities
           (floor :type location)
           (darkness :type condition)
           (pain :type condition)
           (air :type inanimate)
           (ascent :type condition)

           (freedom :type condition)
           (boat :type vehicle)
         )
         (:expressions
           ((have Enrique knife) :name E2)
           ((pull Enrique knife) :name E3)
           ((push knife door) :name E6)
           ((go-to floor door) :name E9)
           ((watch Enrique ship) :name E11)
           ((watch Enrique darkness) :name E12)
           ((have Enrique pain) :name E13)
           ((gasp-for Enrique air) :name E14)
           ((resist Enrique ascent) :name E15)

           ((similar-to door freedom) :name E8)
           ((similar-to ship boat) :name E10)
         )
       )
     )
   )
)