;; --------------------------------------------------------------------
;; This file has been automatically generated by SAM Story Editor v1.11
;; Santiago Ontanon
;; Jichen Zhu
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-01
     (:discourse
       (:clauses
         (phase1 (:s t1 t2 t3 t4))
         (phase2 (:s tb1))
       )
       (:templates
         ;; Julian hasn?t come across a Tiger Dolphin in twenty-three years,
         ;; and he has never been this close to one.
         ;; Julian couldn?t tell if his sudden shortness of breath was from excitement or tank damage from the dolphin?s nudging.
         ;; He considers resurfacing to check his tank.
         ;; Dolphin push tank.
         ;; Julian needs air.
         (t1 (E0  (Julian "Julian") " hasn't come across a " (dolphin "Tiger Dolphin") ) " in twenty-three years,")
         (t2 "and " (Julian "he") " has never been " (E1  (Julian "this") " close to " (dolphin "one") ) ".")
         (t3 (Julian "Julian") " couldn?t " ( "tell") " if " (E6  (Julian "his") " sudden shortness of " (tired "breath") ) " was " (E2  (Julian "from") " " (excited "excitement") ) " or " (E4  (equipment "tank") " damage from the " (dolphin "dolphin") ) "?s nudging.")
         (t4 (E7  (Julian "He") " considers " (surface "resurfacing") ) " to check " (E8  (Julian "his") " " (equipment "tank") ) ".")
         (t5 (E5  (dolphin "Dolphin") " push " (equipment "tank") ) ".")
         (t6 (E9  (Julian "Julian") " needs " (air "air") ) ".")

         (tb1 "And " (EB1 (Julian "Julian") " lived happily ever after"))
       )
     )
     (:structure
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (role :type entity)
           (Hero :type role)
           (Villain :type role)
           (Tester :type role)
           (Prize :type role)
           (FalseHero :type role)
           (Other :type role)

         )
         (:expressions
         )
       )
       (phase1
         (:entities
           (dolphin :type animal)
           (excited :type emotion)
           (equipment :type inanimate)
           (tired :type condition)
           (surface :type location)

           (dolphin :type animal)
           (equipment :type inanimate)
           (Julian :type human)
           (air :type inanimate)
         )
         (:expressions
           ((wants Julian dolphin) :name E0)
           ((find Julian dolphin) :name E1)
           ((feel Julian excited) :name E2)
           ((damage equipment dolphin) :name E4)
           ((have Julian tired) :name E6)
           ((go-to Julian surface) :name E7)
           ((use equipment Julian) :name E8)

           ((push dolphin equipment) :name E5)
           ((gasp-for Julian air) :name E9)
         )
       )

       (phase2
         (:entities

         )
         (:expressions
           ((happy Julian) :name EB1) 
         )
       )
     )
   )
)