
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-21
     (:discourse
       (:clauses
         (c0 (:s phase1))
         (phase1 (:s  t1 t2))

       )
       (:templates
         ;; An old widower lived with his daughter in a farm.
         ;; The widower eventually married another woman who had a daughter of her own.

         (t1 "An old widower lived with his daughter in a farm . ")
         (t2 "The widower eventually married another woman who had a daughter of her own . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    