
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-23
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2 phase3 phase4))
         (phase1 (:s  t1 t2 t3 t4))
         (phase2 (:s  t5 t6 t7))
         (phase3 (:s  t8 t9 t10 t11 t12))
         (phase4 (:s  t13))

       )
       (:templates
         ;; There once lived a priest with his son.
         ;; The boy was very strong and all the other children were afraid of him.
         ;; The villagers asked the priest to keep his son away from their families.
         ;; The priest kept the boy locked in a room.
         ;; The bull ate the town's crops and ruined their fields.
         ;; The boy heard the villagers complaining and wanted to help them.
         ;; He escaped his room and went to the fields.
         ;; He found the bull in the fields.
         ;; The boy and the bull engaged in a fight.
         ;; The boy was able to eventually overcome the bull's strength.
         ;; The bull then became docile.
         ;; The boy tied a rope to the bull's neck and led it back to the village.
         ;; They used the bull and the boy's strengths to mend the fields and were prosperous.

         (t1 "There once lived a priest with his son . ")
         (t2 "The boy was very strong and all the other children were afraid of him . ")
         (t3 "The villagers asked the priest to keep his son away from their families . ")
         (t4 "The priest kept the boy locked in a room . ")
         (t5 "The bull ate the town 's crops and ruined their fields . ")
         (t6 "The boy heard the villagers complaining and wanted to help them . ")
         (t7 "He escaped his room and went to the fields . ")
         (t8 "He found the bull in the fields . ")
         (t9 "The boy and the bull engaged in a fight . ")
         (t10 "The boy was able to eventually overcome the bull 's strength . ")
         (t11 "The bull then became docile . ")
         (t12 "The boy tied a rope to the bull 's neck and led it back to the village . ")
         (t13 "They used the bull and the boy 's strengths to mend the fields and were prosperous . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )
       (phase3
         (:entities
         )
         (:expressions
         )
       )
       (phase4
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    