
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-12
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1 t2 t3))
         (phase2 (:s  t4 t5 t6))

       )
       (:templates
         ;; There was once a dragon that terrorized a little kingdom.
         ;; The dragon would kidnap the town's maidens.
         ;; One night the king had a dream where a tanner rescued his daughter from the dragon.
         ;; The king approached the tanner and asked him to rescue his daughter.
         ;; Eventually the tanner conceded and prepared to go fight the dragon.
         ;; He took a big mace and parted to seek the dragon.

         (t1 "There was once a dragon that terrorized a little kingdom . ")
         (t2 "The dragon would kidnap the town 's maidens . ")
         (t3 "One night the king had a dream where a tanner rescued his daughter from the dragon . ")
         (t4 "The king approached the tanner and asked him to rescue his daughter . ")
         (t5 "Eventually the tanner conceded and prepared to go fight the dragon . ")
         (t6 "He took a big mace and parted to seek the dragon . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    