
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-5
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2 phase3 phase4))
         (phase1 (:s  t1 t2 t3 t4 t5 t6))
         (phase2 (:s  t7 t8 t9))
         (phase3 (:s  t10 t11))
         (phase4 (:s  t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25))

       )
       (:templates
         ;; An old couple lived with their daughter in a farm.
         ;; The mother died of illness.
         ;; The widower eventually married a widow that had a daughter of her own.
         ;; The stepmother was always cruel to the poor girl.
         ;; One night a group of pirates came to the farm.
         ;; They spied the family through the windows.
         ;; The next morning, the girl and her stepsister couldn't find their parents.
         ;; They decided to go look for them.
         ;; They took separate ways.
         ;; The old lady asked her help her pick apples from the top of an apple tree.
         ;; The girl climbed the tree and gave the apples to the old lady.
         ;; The girl was still atop the tree when she saw the pirates come back.
         ;; The pirates saw her.
         ;; One of the pirates had iron teeth and began chewing on the tree.
         ;; But the girl was very agile and jumped from tree to tree until she arrived home.
         ;; The pirates surrounded the farm with the two girls inside.
         ;; But then, the old lady from earlier heard their voices and made the pirates stop.
         ;; The old lady was partly blind and asked the girls if they had helped her.
         ;; The stepsister, immediately jumped and told the old lady she had helped her.
         ;; The other girl implored the old lady to take her but free her parents.
         ;; The old lady smelled the apples on the girl.
         ;; She cursed at the stepsister for being a liar.
         ;; The pirates freed the girl's father.
         ;; The stepmother and stepsister were taken by the pirates and sold as slaves.
         ;; The girl was married to a captain and lived a good life at sea.

         (t1 "An old couple lived with their daughter in a farm . ")
         (t2 "The mother died of illness . ")
         (t3 "The widower eventually married a widow that had a daughter of her own . ")
         (t4 "The stepmother was always cruel to the poor girl . ")
         (t5 "One night a group of pirates came to the farm . ")
         (t6 "They spied the family through the windows . ")
         (t7 "The next morning , the girl and her stepsister could n't find their parents . ")
         (t8 "They decided to go look for them . ")
         (t9 "They took separate ways . ")
         (t10 "The old lady asked her help her pick apples from the top of an apple tree . ")
         (t11 "The girl climbed the tree and gave the apples to the old lady . ")
         (t12 "The girl was still atop the tree when she saw the pirates come back . ")
         (t13 "The pirates saw her . ")
         (t14 "One of the pirates had iron teeth and began chewing on the tree . ")
         (t15 "But the girl was very agile and jumped from tree to tree until she arrived home . ")
         (t16 "The pirates surrounded the farm with the two girls inside . ")
         (t17 "But then , the old lady from earlier heard their voices and made the pirates stop . ")
         (t18 "The old lady was partly blind and asked the girls if they had helped her . ")
         (t19 "The stepsister , immediately jumped and told the old lady she had helped her . ")
         (t20 "The other girl implored the old lady to take her but free her parents . ")
         (t21 "The old lady smelled the apples on the girl . ")
         (t22 "She cursed at the stepsister for being a liar . ")
         (t23 "The pirates freed the girl 's father . ")
         (t24 "The stepmother and stepsister were taken by the pirates and sold as slaves . ")
         (t25 "The girl was married to a captain and lived a good life at sea . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )
       (phase3
         (:entities
         )
         (:expressions
         )
       )
       (phase4
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    