
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-14
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11))
         (phase2 (:s  t12 t13 t14 t15 t16 t17 t18 t19 t20 t21))

       )
       (:templates
         ;; There was once a very wealthy merchant who had a marvelously beautiful daughter.
         ;; This merchant carried goods to various provinces, and one day he came to a certain kingdom and brought precious cloths to the king as a gift.
         ;; The king said to him: "Why can I not find a bride for myself?"
         ;; The merchant answered: "I have a beautiful daughter, and she is so clever that no matter what a man is thinking, she can guess it."
         ;; The king immediately wrote a letter and called his guards.
         ;; "Go to that merchant's house," he told them, "and deliver this letter to the merchant's daughter."
         ;; The letter said: "Make ready to get married."
         ;; The merchant's daughter took the letter, burst into tears, and prepared to go, taking also her maidservant; and no one could distinguish this maid from the merchant's daughter, they were so like each other.
         ;; They dressed in dresses that were alike and went to the king for the marriage.
         ;; The maid was full of spite, and said: "Let us take a walk on the island."
         ;; They went to the island; there the maidservant gave the merchant's daughter sleeping potions, cut out her eyes, and put them in her pocket.
         ;; They answered: "We need only you, we have no use for that peasant girl."
         ;; They went to the king; he married the maid at once, and they began to live together.
         ;; The king thought to himself: "The merchant must have cheated me; she cannot be a merchant's daughter.
         ;; Why is she so ignorant?
         ;; She does not know how to do anything."
         ;; Meanwhile the merchant's daughter recovered from the illness that her maid had brought upon her.
         ;; She could not see; she could only hear and she heard an old man tending cattle.
         ;; She said to him: "Where are you, grandfather?"
         ;; "I live in a little hut."
         ;; "Please take me into your hut."

         (t1 "There was once " (STORY14-m5848 "a very wealthy merchant who had a marvelously beautiful daughter") " " (STORY14-m5849 "a marvelously beautiful daughter") " . ")
         (t2 "" (STORY14-m5848 "This merchant") " carried goods to various provinces , and one day " (STORY14-m5848 "he") " came to a certain kingdom and brought precious cloths to " (STORY14-m5855 "the king") " as a gift . ")
         (t3 "" (STORY14-m5855 "The king") " said to " (STORY14-m5848 "him") " : ' Why can " (STORY14-VERB3 "" (STORY14-m5855 "I") " not find " (STORY14-m5856 "a bride") " for " (STORY14-m5855 "myself") " " ) "? ' ")
         (t4 "" (STORY14-m5848 "The merchant") " answered : ' " (STORY14-m5848 "I") " have " (STORY14-m5849 "a beautiful daughter") " , and " (STORY14-m5849 "she") " is so clever that no matter what a man is thinking , " (STORY14-m5849 "she") " can guess it . ' ")
         (t5 "" (STORY14-m5855 "The king") " immediately wrote a letter and called his " (STORY14-m5859 "his guards") " . ")
         (t6 "' Go to " (STORY14-m5848 "that merchant") " 's house , ' " (STORY14-m5855 "he") " told " (STORY14-m5859 "them") " , ' and deliver this letter to " (STORY14-m5849 "the merchant's daughter") " . ' ")
         (t7 "The letter said : ' Make ready to get married . ' ")
         (t8 "" (STORY14-m5849 "The merchant's daughter") " took the letter , burst into tears , and prepared to go , taking also her " (STORY14-m5862 "her maidservant") " ; and no one could distinguish " (STORY14-m5862 "this maid") " from " (STORY14-m5849 "the merchant's daughter") " , they were so like each other . ")
         (t9 "They dressed in dresses that were alike and went to " (STORY14-m5855 "the king") " for the marriage . ")
         (t10 "" (STORY14-m5862 "The maid") " was full of spite , and said : ' Let us take a walk on the island . ' ")
         (t11 "They went to the island ; there " (STORY14-m5862 "the maidservant") " gave " (STORY14-m5849 "the merchant's daughter") " sleeping potions , cut out her eyes , and put them in her pocket . ")
         (t1001 (STORY14-EXTRA1  (STORY14-m5856 "a bride") " is the " (NA "NA") ) ".")
         (t1002 (STORY14-EXTRA2  (STORY14-m5859 "them") " is the " (Other "Other") ) ".")
         (t1003 (STORY14-EXTRA3  (STORY14-m5862 "the maidservant") " is the " (Other "Other") ) ".")
         (t1004 (STORY14-EXTRA4  (STORY14-m5848 "merchant") " is the " (Other "Other") ) ".")
         (t1005 (STORY14-EXTRA5  (STORY14-m5849 "the merchant's daughter") " is the " (Hero "Hero") ) ".")
         (t1006 (STORY14-EXTRA6  (STORY14-m5855 "the king") " is the " (Other "Other") ) ".")
         (t12 "" (STORY14-m5859 "They") " answered : ' " (STORY14-VERB8 "" (STORY14-m5859 "We") " need only " (STORY14-m5862 "you") " " ) ", " (STORY14-m5859 "we") " have no use for " (STORY14-m5849 "that peasant girl") " . ' ")
         (t13 "They went to " (STORY14-m5855 "the king") " ; " (STORY14-m5855 "he") " married " (STORY14-m5862 "the maid") " at once , and they began to live together . ")
         (t14 "" (STORY14-m5855 "The king") " thought to " (STORY14-m5855 "himself") " : ' " (STORY14-m5848 "The merchant") " must have cheated " (STORY14-m5855 "me") " ; " (STORY14-m5862 "she") " can not be a merchant 's daughter . ")
         (t15 "Why is " (STORY14-m5862 "she") " so ignorant ? ")
         (t16 "" (STORY14-m5862 "She") " does not know how to do anything . ' ")
         (t17 "Meanwhile " (STORY14-m5849 "the merchant's daughter") " recovered from the illness that her " (STORY14-m5862 "her maid") " had brought upon " (STORY14-m5849 "her") " . ")
         (t18 "" (STORY14-m5849 "She") " could not see ; " (STORY14-m5849 "she") " could only hear and " (STORY14-m5849 "she") " heard " (STORY14-m5876 "an old man tending cattle") " cattle . ")
         (t19 "" (STORY14-m5849 "She") " said to " (STORY14-m5876 "him") " : ' Where are " (STORY14-m5876 "you, grandfather") " ? ' ")
         (t20 "' " (STORY14-m5876 "I") " live in a little hut . ' ")
         (t21 "' Please take " (STORY14-m5849 "me") " into your hut . ' ")
         (t1007 (STORY14-EXTRA7  (STORY14-m5856 "a bride") " is the " (NA "NA") ) ".")
         (t1008 (STORY14-EXTRA8  (STORY14-m5859 "we") " is the " (Other "Other") ) ".")
         (t1009 (STORY14-EXTRA9  (STORY14-m5862 "her maid") " is the " (Other "Other") ) ".")
         (t1010 (STORY14-EXTRA10  (STORY14-m5876 "I") " is the " (Tester "Tester") ) ".")
         (t1011 (STORY14-EXTRA11  (STORY14-m5848 "merchant") " is the " (Other "Other") ) ".")
         (t1012 (STORY14-EXTRA12  (STORY14-m5849 "me") " is the " (Hero "Hero") ) ".")
         (t1013 (STORY14-EXTRA13  (STORY14-m5855 "me") " is the " (Other "Other") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY14-m5856 :type FE)
           (STORY14-m5859 :type GR)
           (STORY14-m5862 :type FE)
           (STORY14-m5848 :type MA)
           (STORY14-m5849 :type FE)
           (STORY14-m5855 :type MA)
         )
         (:expressions
           ((levin-11-3 STORY14-m5848 STORY14-m5855) :name STORY14-VERB1)
           ((levin-37-7 STORY14-m5855 STORY14-m5848) :name STORY14-VERB2)
           ((levin-29-4 STORY14-m5855 STORY14-m5855) :name STORY14-VERB3)
           ((levin-29-3 STORY14-m5855 STORY14-m5859) :name STORY14-VERB4)
           ((levin-37-2 STORY14-m5855 STORY14-m5849) :name STORY14-VERB5)
           ((levin-11-3 STORY14-m5849 STORY14-m5862) :name STORY14-VERB6)
           ((levin-13-1 STORY14-m5862 STORY14-m5848) :name STORY14-VERB7)
           ((roleNA STORY14-m5856) :name STORY14-EXTRA0)
           ((roleOther STORY14-m5859) :name STORY14-EXTRA1)
           ((roleOther STORY14-m5862) :name STORY14-EXTRA2)
           ((roleOther STORY14-m5848) :name STORY14-EXTRA3)
           ((roleHero STORY14-m5849) :name STORY14-EXTRA4)
           ((roleOther STORY14-m5855) :name STORY14-EXTRA5)
         )
       )
       (phase2
         (:entities
           (STORY14-m5856 :type FE)
           (STORY14-m5859 :type GR)
           (STORY14-m5862 :type FE)
           (STORY14-m5876 :type MA)
           (STORY14-m5848 :type MA)
           (STORY14-m5849 :type FE)
           (STORY14-m5855 :type MA)
         )
         (:expressions
           ((levin-32-1 STORY14-m5859 STORY14-m5862) :name STORY14-VERB8)
           ((levin-29-4 STORY14-m5855 STORY14-m5862) :name STORY14-VERB9)
           ((levin-11-3 STORY14-m5862 STORY14-m5849) :name STORY14-VERB10)
           ((levin-30-1 STORY14-m5849 STORY14-m5876) :name STORY14-VERB11)
           ((levin-37-7 STORY14-m5849 STORY14-m5876) :name STORY14-VERB12)
           ((roleNA STORY14-m5856) :name STORY14-EXTRA6)
           ((roleOther STORY14-m5859) :name STORY14-EXTRA7)
           ((roleOther STORY14-m5862) :name STORY14-EXTRA8)
           ((roleTester STORY14-m5876) :name STORY14-EXTRA9)
           ((roleOther STORY14-m5848) :name STORY14-EXTRA10)
           ((roleHero STORY14-m5849) :name STORY14-EXTRA11)
           ((roleOther STORY14-m5855) :name STORY14-EXTRA12)
         )
       )

     )
   )
)
    