
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-20
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1 t2))
         (phase2 (:s  t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14))

       )
       (:templates
         ;; In a land far away, there lived a rich family with a single spoilt daughter.
         ;; One day, the parents to work.
         ;; There were candied apples in the top of the tree but the girl couldn't reach.
         ;; The apple tree asked the girl to eat some of its green apples and then it would give her a candy apple.
         ;; The girl rejected the green apples.
         ;; The apple tree did not give her candied apples.
         ;; Further down the path she found a river of pudding.
         ;; The river asked her to eat some porridge and then it would hive her some pudding.
         ;; The girl refused to eat any porridge.
         ;; The river of pudding did not give her any pudding.
         ;; At the darkest part of the forest the girl found a house made of bread.
         ;; She asked for some gingerbread but the house told her she'd need to eat some rye bread first.
         ;; The girl said that she wouldn't eat any rye bread.
         ;; The house did not give her any gingerbread.

         (t1 "In a land far away , there lived a rich family with a single spoilt daughter . ")
         (t2 "One day , the parents to work . ")
         (t3 "There were candied apples in the top of the tree but the girl could n't reach . ")
         (t4 "The apple tree asked the girl to eat some of its green apples and then it would give her a candy apple . ")
         (t5 "The girl rejected the green apples . ")
         (t6 "The apple tree did not give her candied apples . ")
         (t7 "Further down the path she found a river of pudding . ")
         (t8 "The river asked her to eat some porridge and then it would hive her some pudding . ")
         (t9 "The girl refused to eat any porridge . ")
         (t10 "The river of pudding did not give her any pudding . ")
         (t11 "At the darkest part of the forest the girl found a house made of bread . ")
         (t12 "She asked for some gingerbread but the house told her she 'd need to eat some rye bread first . ")
         (t13 "The girl said that she would n't eat any rye bread . ")
         (t14 "The house did not give her any gingerbread . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    