
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-23
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1 t2 t3 t4))
         (phase2 (:s  t5 t6 t7))

       )
       (:templates
         ;; There once lived a priest with his son.
         ;; The boy was very strong and all the other children were afraid of him.
         ;; The villagers asked the priest to keep his son away from their families.
         ;; The priest kept the boy locked in a room.
         ;; The bull ate the town's crops and ruined their fields.
         ;; The boy heard the villagers complaining and wanted to help them.
         ;; He escaped his room and went to the fields.

         (t1 "There once lived a priest with his son . ")
         (t2 "The boy was very strong and all the other children were afraid of him . ")
         (t3 "The villagers asked the priest to keep his son away from their families . ")
         (t4 "The priest kept the boy locked in a room . ")
         (t5 "The bull ate the town 's crops and ruined their fields . ")
         (t6 "The boy heard the villagers complaining and wanted to help them . ")
         (t7 "He escaped his room and went to the fields . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    