
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-10
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2 phase3 phase4))
         (phase1 (:s  t1))
         (phase2 (:s  t2 t3 t4 t5))
         (phase3 (:s  t6 t7 t8 t9))
         (phase4 (:s  t10))

       )
       (:templates
         ;; In a kingdom far away there was a town terrified by a dragon.
         ;; The king issued a call for help.
         ;; A humble soldier responded to the call.
         ;; The king told the soldier he would make him a nobleman is he could rescue the princess.
         ;; The soldier agreed and departed.
         ;; The dragon ambushed him but the soldier was faster than him.
         ;; The dragon saw he could not win and asked the soldier for forgiveness.
         ;; The soldier ordered the dragon to leave and never come back.
         ;; He found the princess and rescued her.
         ;; The soldier married the princess and they lived a happy and peaceful life.

         (t1 "In a kingdom far away there was a town terrified by a dragon . ")
         (t2 "The king issued a call for help . ")
         (t3 "A humble soldier responded to the call . ")
         (t4 "The king told the soldier he would make him a nobleman is he could rescue the princess . ")
         (t5 "The soldier agreed and departed . ")
         (t6 "The dragon ambushed him but the soldier was faster than him . ")
         (t7 "The dragon saw he could not win and asked the soldier for forgiveness . ")
         (t8 "The soldier ordered the dragon to leave and never come back . ")
         (t9 "He found the princess and rescued her . ")
         (t10 "The soldier married the princess and they lived a happy and peaceful life . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )
       (phase3
         (:entities
         )
         (:expressions
         )
       )
       (phase4
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    