
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-7
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1))
         (phase2 (:s  t2 t3 t4 t5 t6 t7 t8 t9 t10))

       )
       (:templates
         ;; This soldier got permission to go on leave.
         ;; He walked and walked, but nowhere did he see any water and he wanted to wet his hardtack and eat a little along the way and road.
         ;; His belly had long since been empty.
         ;; There was nothing to be done and so he dragged himself on a bit further.
         ;; Then he looked and saw a creek running.
         ;; He went up to this creek and got three biscuits out of his pack and put them in the water.
         ;; Besides  the hardtack the soldier had this fiddle.
         ;; In his free time he played various songs to chase away his boredom.
         ;; So the soldier sat down next to the stream and began playing.
         ;; Suddenly out of nowhere the Unclean One with the appearance of an old man came up to him with a book in his hands.

         (t1 "" (STORY7-m5965 "This soldier") " got permission to go on leave . ")
         (t1001 (STORY7-EXTRA1  (STORY7-m5965 "This soldier") " is the " (Hero "Hero") ) ".")
         (t2 "" (STORY7-m5965 "He") " walked and walked , but nowhere did " (STORY7-m5965 "he") " see any water and " (STORY7-m5965 "he") " wanted to wet his hardtack and eat a little along the way and road . ")
         (t3 "His belly had long since been empty . ")
         (t4 "There was nothing to be done and so " (STORY7-m5965 "he") " dragged " (STORY7-m5965 "himself") " on a bit further . ")
         (t5 "Then " (STORY7-m5965 "he") " looked and saw a creek running . ")
         (t6 "" (STORY7-m5965 "He") " went up to this creek and got three biscuits out of his pack and put them in the water . ")
         (t7 "Besides the hardtack " (STORY7-m5965 "the soldier") " had this fiddle . ")
         (t8 "In his free time " (STORY7-m5965 "he") " played various songs to chase away his boredom . ")
         (t9 "So " (STORY7-m5965 "the soldier") " sat down next to the stream and began playing . ")
         (t10 "Suddenly out of nowhere " (STORY7-m5982 "the Unclean One with the appearance of an old man") " came up to " (STORY7-m5965 "him") " with a book in his hands . ")
         (t1002 (STORY7-EXTRA2  (STORY7-m5965 "him") " is the " (Hero "Hero") ) ".")
         (t1003 (STORY7-EXTRA3  (STORY7-m5982 "the Unclean One with the appearance of an old man") " is the " (Villain "Villain") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY7-m5965 :type MA)
         )
         (:expressions
           ((roleHero STORY7-m5965) :name STORY7-EXTRA0)
         )
       )
       (phase2
         (:entities
           (STORY7-m5965 :type MA)
           (STORY7-m5982 :type MB)
         )
         (:expressions
           ((levin-11-4 STORY7-m5965 STORY7-m5965) :name STORY7-VERB1)
           ((roleHero STORY7-m5965) :name STORY7-EXTRA1)
           ((roleVillain STORY7-m5982) :name STORY7-EXTRA2)
         )
       )

     )
   )
)
    