
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-28
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2 phase3 phase4))
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7))
         (phase2 (:s  t8))
         (phase3 (:s  t9 t10 t11))
         (phase4 (:s  t12))

       )
       (:templates
         ;; A poor traveling gypsy and his son got lost in the woods.
         ;; Late at night they found a tower and asked for help.
         ;; A little frog let them in.
         ;; The frog told them that they could stay the night but asked them not to go upstairs.
         ;; In the middle of the night, they heard noise upstairs and went to check it out.
         ;; There was a witch.
         ;; She converted the father into a lizard.
         ;; The boy agreed but the witch was too fast and he couldn't get her hat.
         ;; She asked the boy to take her with him.
         ;; The boy agreed and the frog gave the boy a magic ring that would turn him invisible.
         ;; With the magic ring, the boy walked to the witch and stole her hat.
         ;; The boy and the princess got married and all lived happy in the palace.

         (t1 "A poor traveling gypsy and his son got lost in the woods . ")
         (t2 "Late at night they found a tower and asked for help . ")
         (t3 "A little frog let them in . ")
         (t4 "The frog told them that they could stay the night but asked them not to go upstairs . ")
         (t5 "In the middle of the night , they heard noise upstairs and went to check it out . ")
         (t6 "There was a witch . ")
         (t7 "She converted the father into a lizard . ")
         (t8 "The boy agreed but the witch was too fast and he could n't get her hat . ")
         (t9 "She asked the boy to take her with him . ")
         (t10 "The boy agreed and the frog gave the boy a magic ring that would turn him invisible . ")
         (t11 "With the magic ring , the boy walked to the witch and stole her hat . ")
         (t12 "The boy and the princess got married and all lived happy in the palace . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )
       (phase3
         (:entities
         )
         (:expressions
         )
       )
       (phase4
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    