
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-4
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4 t5))
         (phase2 (:s  t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42 t43 t44 t45 t46 t47 t48 t49 t50 t51 t52 t53 t54 t55 t56 t57))
         (phase3 (:s  t58 t59 t60))

       )
       (:templates
         ;; In a certain kingdom in a certain land there lived a king who had three sons.
         ;; One day they said to him: "Father, our gracious sovereign, give us your blessing; we wish to go hunting."
         ;; The father gave them his blessing and they set out in different directions.
         ;; The youngest son rode and rode and lost his way; he came to a clearing, and there lay a dead horse, around which were gathered beasts of many kinds, birds, and reptiles.
         ;; A falcon rose, flew up to the prince, perched on his shoulder, and said: "Prince Ivan, divide that horse among us; it has lain here for thirty years, and we have been quarreling ever since, unable to find a way of sharing it."
         ;; "Thank you, Prince Ivan," said the falcon.
         ;; "For your kindness you shall be able to turn into a bright falcon or an ant whenever you wish."
         ;; Prince Ivan struck the damp earth, turned into a bright falcon, soared up into the air, and flew to the thrice tenth kingdom.
         ;; More than half of that kingdom had been swallowed into a crystal mountain.
         ;; The prince flew straight into the royal palace, turned into a goodly youth, and asked the palace guards: "Will your king take me into his service?"
         ;; "Why should he not take such a goodly youth?" they answered.
         ;; Thus he entered the service of that king and lived in his palace for one week, then a second, then a third.
         ;; The king's daughter asked her father: "Father, my sovereign, give me leave to take a ride with Prince Ivan to the crystal mountain."
         ;; The king gave her leave.
         ;; They mounted good steeds and set out.
         ;; When they approached the crystal mountain, a golden goat jumped suddenly out from nowhere.
         ;; The prince chased it; he galloped and galloped, but could not catch the goat, and when he returned the princess had vanished.
         ;; What was he to do?
         ;; How could he dare to appear before the king?
         ;; He disguised himself as a very old man, so that he would be unrecognizable, came to the palace, and said to the king: "Your Majesty, hire me as your herdsman."
         ;; "Very well," said the king, "be my herdsman.
         ;; When the three-headed dragon comes to your herd, give him three cows; when the six-headed dragon comes, give him six cows; and when the twelve-headed dragon comes, count off twelve cows."
         ;; Prince Ivan drove his herd over mountains and valleys.
         ;; Suddenly the three-headed dragon came flying from a lake and said: "Ah, Prince Ivan, what kind of work are you engaged in?
         ;; A goodly youth like you should be vying in combat, not tending cattle.
         ;; Well, let me have three cows!"
         ;; "Won't that be too much?" asked the prince.
         ;; "I myself eat only one duck a day, and you want three cows.
         ;; But you won't get any!"
         ;; The dragon flew into a rage, and instead of three cows, seized six.
         ;; Prince Ivan straightway turned into a bright falcon, cut off all the three heads of the dragon, and drove the cattle home.
         ;; "Well, grandfather," asked the king, "has the three-headed dragon come?
         ;; Did you give him three cows?"
         ;; "No, Your Majesty," replied Prince Ivan, "I did not give him any."
         ;; Next day the prince drove his herd over mountains and valleys, and the six-headed dragon came from the lake and demanded six cows.
         ;; "Ah, you gluttonous monster," said the prince, "I myself eat only one duck a day, and see what you demand!
         ;; I won't give you any!"
         ;; The dragon flew into a rage and instead of six, seized twelve cows; but the prince turned into a bright falcon, fell upon the dragon, and cut off his six heads.
         ;; He drove the herd home and the king asked him: "Well, grandfather, has the six-headed dragon come?
         ;; Has my herd grown much smaller?"
         ;; "Come he did, but he took nothing," answered the prince.
         ;; Late at night Prince Ivan turned into an ant and crawled into the crystal mountain through a little crack.
         ;; Lo and behold, the princess was in the crystal mountain.
         ;; "Good evening!" said Prince Ivan.
         ;; "How did you get here?"
         ;; "The twelve-headed dragon carried me off," said the princess.
         ;; "He lives in father's lake and has a coffer in his side.
         ;; In this coffer is a hare, in this hare is a duck, in this duck is an egg, and in this egg is a seed.
         ;; If you slay the dragon and get that seed, it will be possible to destroy the crystal mountain and rescue me."
         ;; Prince Ivan crawled out of the mountain, turned again into a herdsman, and drove his herd.
         ;; Suddenly the twelve-headed dragon flew up to him and said: "Ah, Prince Ivan, you are not doing what you should; a goodly youth like you should be vying in combat, not tending a herd.
         ;; Well, count off twelve cows for me!"
         ;; "That will be too much for you!" said the prince.
         ;; "I myself eat only one duck a day, and see what you demand!"
         ;; They began to fight, and after a long struggle or a short struggle, Prince Ivan defeated the twelve-headed dragon, slashed open his trunk, and found the coffer in his right side.
         ;; In the coffer he found a hare, in the hare a duck, in the duck an egg, in the egg a seed.
         ;; He took the seed, set it alight, and brought it to the crystal mountain, which soon melted away.
         ;; The wedding was held at once.
         ;; I was at that wedding too.
         ;; I drank beer and mead; they flowed down my beard but did not go into my mouth.

         (t1 "In a certain kingdom in a certain land there lived " (3344 "a king who had three sons") "" (3345 "three sons") ". "
         (t2 "One day " (3345 "they") "said to him : ' " (3344 "Father, our gracious sovereign") "" (3344 "Father, our gracious sovereign") "your blessing ; " (3345 "we") "wish to go hunting . ' "
         (t3 "" (3344 "The father") "gave " (3345 "them") "his blessing and " (3345 "they") "set out in different directions . "
         (t4 "" (3349 "The youngest son") "rode and rode and lost his way ; " (3349 "he") "came to a clearing , and there lay a dead horse , around which were gathered beasts of many kinds , birds , and reptiles . "
         (t5 "" (3357 "A falcon") "rose , flew up to the prince , perched on his shoulder , and said : ' " (3349 "Prince Ivan") ", divide that horse among us ; it has lain here for thirty years , and we have been quarreling ever since , unable to find a way of sharing it . ' "
         (t6 "' Thank " (3349 "you") ", " (3349 "Prince Ivan") ", ' said " (3357 "the falcon") ". "
         (t7 "' For your kindness " (3349 "you") "shall be able to turn into " (3368 "a bright falcon") "or an ant whenever " (3349 "you") "wish . ' "
         (t8 "" (3349 "Prince Ivan") "struck the damp earth , turned into a bright falcon , soared up into the air , and flew to the thrice tenth kingdom . "
         (t9 "More than half of that kingdom had been swallowed into a crystal mountain . "
         (t10 "" (3349 "The prince") "flew straight into the royal palace , turned into a goodly youth , and asked " (3376 "the palace guards") "" (3376 "the palace guards") "' Will your " (3377 "your king") "take " (3349 "me") "into his service ? ' "
         (t11 "' Why should " (3377 "he") "not take " (3349 "such a goodly youth") "? ' " (3376 "they") "answered . "
         (t12 "Thus " (3349 "he") "entered the service of " (3377 "that king") "and lived in his palace for one week , then a second , then a third . "
         (t13 "" (3382 "The king's daughter") "" (3382 "The king's daughter") "" (3377 "her father") ": ' " (3377 "Father, my sovereign") "" (3377 "Father, my sovereign") "" (3382 "me") "leave to take a ride with " (3349 "Prince Ivan") "to the crystal mountain . ' "
         (t14 "" (3377 "The king") "gave her leave . "
         (t15 "They mounted good steeds and set out . "
         (t16 "When they approached the crystal mountain , " (3387 "a golden goat") "jumped suddenly out from nowhere . "
         (t17 "" (3349 "The prince") "chased " (3387 "it") "; " (3349 "he") "galloped and galloped , but could not catch " (3387 "the goat") ", and when " (3349 "he") "returned " (3382 "the princess") "had vanished . "
         (t18 "What was " (3349 "he") "to do ? "
         (t19 "How could " (3349 "he") "dare to appear before the king ? "
         (t20 "" (3349 "He") "disguised " (3349 "himself") "as a very old man , so that " (3349 "he") "would be unrecognizable , came to the palace , and said to the king : ' " (3377 "Your Majesty") ", hire " (3349 "me") "as your herdsman . ' "
         (t21 "' Very well , ' said " (3377 "the king") ", ' be my " (3390 "my herdsman") ". "
         (t22 "When " (3391 "the three-headed dragon") "comes to your herd , give " (3391 "him") "three cows ; when " (3394 "the six-headed dragon") "comes , give him six cows ; and when " (3396 "the twelve-headed dragon") "comes , count off twelve cows . ' "
         (t23 "" (3349 "Prince Ivan") "drove his herd over mountains and valleys . "
         (t24 "Suddenly " (3391 "the three-headed dragon") "came flying from a lake and said : ' Ah , " (3349 "Prince Ivan") ", what kind of work are you engaged in ? "
         (t25 "" (3349 "A goodly youth like you") "should be vying in combat , not tending cattle . "
         (t26 "Well , let " (3391 "me") "have three cows ! ' "
         (t27 "' Wo n't that be too much ? ' asked " (3349 "the prince") ". "
         (t28 "' " (3349 "I myself") "eat only one duck a day , and " (3391 "you") "want three cows . "
         (t29 "But " (3391 "you") "wo n't get any ! ' "
         (t30 "" (3391 "The dragon") "flew into a rage , and instead of three cows , seized six . "
         (t31 "" (3349 "Prince Ivan") "straightway turned into a bright falcon , cut off all the three heads of " (3391 "the dragon") ", and drove the cattle home . "
         (t32 "' Well , grandfather , ' asked " (3377 "the king") ", ' has " (3391 "the three-headed dragon") "come ? "
         (t33 "Did " (3349 "you") "give " (3391 "him") "three cows ? ' "
         (t34 "' No , Your Majesty , ' replied " (3349 "Prince Ivan") ", ' " (3349 "I") "did not give " (3391 "him") "any . ' "
         (t35 "Next day " (3349 "the prince") "drove his herd over mountains and valleys , and " (3394 "the six- headed dragon") "came from the lake and demanded six cows . "
         (t36 "' Ah , you gluttonous monster , ' said " (3349 "the prince") ", ' " (3349 "I myself") "eat only one duck a day , and see what " (3394 "you") "demand ! "
         (t37 "" (3349 "I") "wo n't give " (3394 "you") "any ! ' "
         (t38 "" (3394 "The dragon") "flew into a rage and instead of six , seized twelve cows ; but " (3349 "the prince") "turned into " (3349 "a bright falcon") ", fell upon " (3394 "the dragon") ", and cut off his six heads . "
         (t39 "" (3349 "He") "drove the herd home and " (3377 "the king") "asked " (3349 "him") ": ' Well , grandfather , has " (3394 "the six-headed dragon") "come ? "
         (t40 "Has my herd grown much smaller ? ' "
         (t41 "' Come " (3394 "he") "did , but " (3394 "he") "took nothing , ' answered " (3349 "the prince") ". "
         (t42 "Late at night " (3349 "Prince Ivan") "turned into an ant and crawled into the crystal mountain through a little crack . "
         (t43 "Lo and behold , " (3382 "the princess") "was in the crystal mountain . "
         (t44 "' Good evening ! ' said " (3349 "Prince Ivan") ". "
         (t45 "' How did " (3382 "you") "get here ? ' "
         (t46 "' " (3396 "The twelve-headed dragon") "carried " (3382 "me") "off , ' said " (3382 "the princess") ". "
         (t47 "' " (3396 "He") "lives in " (3377 "father") "'s lake and has a coffer in his side . "
         (t48 "In this coffer is a hare , in this hare is a duck , in this duck is an egg , and in this egg is a seed . "
         (t49 "If " (3349 "you") "slay " (3396 "the dragon") "and get that seed , it will be possible to destroy the crystal mountain and rescue " (3382 "me") ". ' "
         (t50 "" (3349 "Prince Ivan") "crawled out of the mountain , turned again into " (3349 "a herdsman") ", and drove his herd . "
         (t51 "Suddenly " (3396 "the twelve-headed dragon") "flew up to him and said : ' Ah , " (3349 "Prince Ivan") ", " (3349 "you") "are not doing what " (3349 "you") "should ; " (3349 "a goodly youth like you") "should be vying in combat , not tending a herd . "
         (t52 "Well , count off twelve cows for " (3396 "me") "! ' "
         (t53 "' That will be too much for " (3396 "you") "! ' said " (3349 "the prince") ". "
         (t54 "' " (3349 "I myself") "eat only one duck a day , and see what " (3396 "you") "demand ! ' "
         (t55 "They began to fight , and after a long struggle or a short struggle , " (3349 "Prince Ivan") "defeated " (3396 "the twelve-headed dragon") ", slashed open his trunk , and found the coffer in his right side . "
         (t56 "In the coffer " (3349 "he") "found a hare , in the hare a duck , in the duck an egg , in the egg a seed . "
         (t57 "" (3349 "He") "took the seed , set it alight , and brought it to the crystal mountain , which soon melted away . "
         (t58 "The wedding was held at once . "
         (t59 "" (3426 "I") "was at that wedding too . "
         (t60 "" (3426 "I") "drank beer and mead ; they flowed down my beard but did not go into my mouth . "

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)
         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m3344 :type MA)
           (m3345 :type MA)
           (m3349 :type MA)
           (m3357 :type AA)
         )
         (:expressions
           ((verb-lived m3344 m-1) :name E1)
           ((verb-had m3344 m3345) :name E2)
           ((verb-said m3345 m3345) :name E3)
           ((verb-give m3344 m3345) :name E4)
           ((verb-wish m3345 m-1) :name E5)
           ((verb-go m3345 m-1) :name E6)
           ((verb-gave m3344 m3345) :name E7)
           ((verb-set m3345 m-1) :name E8)
           ((verb-rode m3349 m-1) :name E9)
           ((verb-rode m3349 m-1) :name E10)
           ((verb-lost m3349 m-1) :name E11)
           ((verb-came m-1 m3349) :name E12)
           ((verb-rose m-1 m3357) :name E13)
           ((verb-flew m-1 m3357) :name E14)
           ((verb-perched m-1 m3357) :name E15)
           ((verb-said m3357 m3349) :name E16)
           ((verb-divide m3349 m-1) :name E17)
         )
       )
       (phase2
         (:entities
           (m3376 :type GR)
           (m3394 :type MB)
           (m3396 :type MB)
           (m3377 :type MA)
           (m3368 :type AA)
           (m3344 :type MA)
           (m3345 :type MA)
           (m3349 :type MA)
           (m3382 :type FE)
           (m3387 :type AA)
           (m3357 :type AA)
           (m3390 :type MA)
           (m3391 :type MB)
         )
         (:expressions
           ((verb-said m3357 m3349) :name E18)
           ((verb-Thank m3357 m3349) :name E19)
           ((verb-be m-1 m3349) :name E20)
           ((verb-turn m3349 m3368) :name E21)
           ((verb-wish m3349 m-1) :name E22)
           ((verb-struck m3349 m-1) :name E23)
           ((verb-turned m-1 m3349) :name E24)
           ((verb-soared m-1 m3349) :name E25)
           ((verb-flew m-1 m3349) :name E26)
           ((verb-flew m-1 m3349) :name E27)
           ((verb-turned m-1 m3349) :name E28)
           ((verb-asked m3349 m3376) :name E29)
           ((verb-take m3377 m3349) :name E30)
           ((verb-take m3377 m3349) :name E31)
           ((verb-answered m3376 m3377) :name E32)
           ((verb-entered m3349 m3377) :name E33)
           ((verb-lived m3349 m-1) :name E34)
           ((verb-asked m3382 m3377) :name E35)
           ((verb-give m3377 m3349) :name E36)
           ((verb-take m3382 m3349) :name E37)
           ((verb-gave m3377 m-1) :name E38)
           ((verb-jumped m3387 m-1) :name E39)
           ((verb-chased m3349 m3387) :name E40)
           ((verb-galloped m3349 m-1) :name E41)
           ((verb-galloped m3349 m-1) :name E42)
           ((verb-catch m3349 m3387) :name E43)
           ((verb-returned m-1 m3349) :name E44)
           ((verb-vanished m-1 m3382) :name E45)
           ((verb-do m3349 m-1) :name E46)
           ((verb-dare m-1 m3349) :name E47)
           ((verb-appear m-1 m3349) :name E48)
           ((verb-disguised m3349 m3349) :name E49)
           ((verb-be m-1 m3349) :name E50)
           ((verb-came m-1 m3349) :name E51)
           ((verb-said m3349 m3377) :name E52)
           ((verb-hire m3377 m3349) :name E53)
           ((verb-said m3377 m3390) :name E54)
           ((verb-be m-1 m3390) :name E55)
           ((verb-comes m-1 m3391) :name E56)
           ((verb-give m-1 m3391) :name E57)
           ((verb-comes m-1 m3394) :name E58)
           ((verb-give m-1 m3394) :name E59)
           ((verb-comes m-1 m3396) :name E60)
           ((verb-count m-1 m3396) :name E61)
           ((verb-drove m3349 m-1) :name E62)
           ((verb-came m-1 m3391) :name E63)
           ((verb-flying m-1 m3391) :name E64)
           ((verb-said m3391 m3349) :name E65)
           ((verb-engaged m-1 m3349) :name E66)
           ((verb-vying m3349 m-1) :name E67)
           ((verb-tending m3349 m-1) :name E68)
           ((verb-let m-1 m3391) :name E69)
           ((verb-have m3391 m-1) :name E70)
           ((verb-asked m3349 m-1) :name E71)
           ((verb-eat m3349 m3349) :name E72)
           ((verb-want m3391 m-1) :name E73)
           ((verb-get m3391 m-1) :name E74)
           ((verb-flew m-1 m3391) :name E75)
           ((verb-seized m3391 m-1) :name E76)
           ((verb-turned m-1 m3349) :name E77)
           ((verb-cut m3349 m3391) :name E78)
           ((verb-drove m3349 m-1) :name E79)
           ((verb-asked m3377 m3391) :name E80)
           ((verb-come m-1 m3391) :name E81)
           ((verb-give m3349 m3391) :name E82)
           ((verb-replied m3349 m3391) :name E83)
           ((verb-give m3349 m3391) :name E84)
           ((verb-drove m3349 m-1) :name E85)
           ((verb-came m-1 m3394) :name E86)
           ((verb-demanded m3394 m-1) :name E87)
           ((verb-said m3349 m3394) :name E88)
           ((verb-eat m3349 m3349) :name E89)
           ((verb-see m3394 m3394) :name E90)
           ((verb-demand m3394 m-1) :name E91)
           ((verb-give m3349 m3394) :name E92)
           ((verb-flew m-1 m3394) :name E93)
           ((verb-seized m3394 m-1) :name E94)
           ((verb-turned m-1 m3349) :name E95)
           ((verb-fell m-1 m3349) :name E96)
           ((verb-cut m3349 m3394) :name E97)
           ((verb-drove m3349 m-1) :name E98)
           ((verb-asked m3377 m3349) :name E99)
           ((verb-come m-1 m3394) :name E100)
           ((verb-Come m-1 m3394) :name E101)
           ((verb-answered m3349 m3394) :name E102)
           ((verb-took m3394 m-1) :name E103)
           ((verb-turned m-1 m3349) :name E104)
           ((verb-crawled m3349 m-1) :name E105)
           ((verb-Lo m-1 m3382) :name E106)
           ((verb-was m-1 m3382) :name E107)
           ((verb-behold m-1 m3382) :name E108)
           ((verb-said m3349 m-1) :name E109)
           ((verb-get m-1 m3382) :name E110)
           ((verb-carried m3396 m3382) :name E111)
           ((verb-said m3382 m3396) :name E112)
           ((verb-lives m3396 m3377) :name E113)
           ((verb-has m3396 m-1) :name E114)
           ((verb-slay m3349 m3396) :name E115)
           ((verb-get m3349 m-1) :name E116)
           ((verb-destroy m3349 m-1) :name E117)
           ((verb-rescue m3349 m3382) :name E118)
           ((verb-be m-1 m3382) :name E119)
           ((verb-crawled m3349 m-1) :name E120)
           ((verb-turned m-1 m3349) :name E121)
           ((verb-drove m3349 m-1) :name E122)
           ((verb-flew m-1 m3396) :name E123)
           ((verb-said m3396 m3349) :name E124)
           ((verb-doing m3349 m3349) :name E125)
           ((verb-vying m3349 m-1) :name E126)
           ((verb-tending m3349 m-1) :name E127)
           ((verb-count m-1 m3396) :name E128)
           ((verb-said m3349 m3396) :name E129)
           ((verb-be m-1 m3396) :name E130)
           ((verb-eat m3349 m3349) :name E131)
           ((verb-see m3349 m3396) :name E132)
           ((verb-demand m3396 m-1) :name E133)
           ((verb-defeated m3349 m3396) :name E134)
           ((verb-slashed m3349 m-1) :name E135)
           ((verb-found m3349 m-1) :name E136)
           ((verb-found m3349 m-1) :name E137)
           ((verb-found m3349 m-1) :name E138)
           ((verb-found m3349 m-1) :name E139)
           ((verb-found m3349 m-1) :name E140)
           ((verb-took m3349 m-1) :name E141)
           ((verb-set m3349 m-1) :name E142)
           ((verb-brought m3349 m-1) :name E143)
         )
       )
       (phase3
         (:entities
           (m3376 :type GR)
           (m3394 :type MB)
           (m3396 :type MB)
           (m3377 :type MA)
           (m3368 :type AA)
           (m3426 :type MB)
           (m3344 :type MA)
           (m3345 :type MA)
           (m3349 :type MA)
           (m3382 :type FE)
           (m3387 :type AA)
           (m3357 :type AA)
           (m3390 :type MA)
           (m3391 :type MB)
         )
         (:expressions
           ((verb-was m-1 m3426) :name E144)
           ((verb-drank m3426 m-1) :name E145)
         )
       )

     )
   )
)
    