
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-15
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16))
         (phase2 (:s  t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42 t43 t44 t45 t46 t47 t48 t49 t50 t51 t52 t53 t54 t55 t56 t57 t58 t59 t60 t61 t62 t63 t64 t65 t66 t67 t68 t69 t70 t71 t72 t73 t74 t75 t76 t77 t78 t79 t80 t81 t82 t83 t84 t85 t86 t87 t88 t89 t90 t91 t92 t93 t94 t95 t96 t97))
         (phase3 (:s  t98))

       )
       (:templates
         ;; In a certain kingdom there was a king who had three daughters of surpassing beauty.
         ;; The king guarded them more carefully than his most precious treasure; he built underground chambers and kept his daughters there like birds in a cage, so that rough winds could not blow upon them nor the red sun scorch them with his rays.
         ;; One day the princesses read in a certain book that there was a marvelous bright world, and when the king came to visit them, they straightway began to implore him with tears in their eyes, saying: "Sovereign, our father, let us out to see the bright world and walk in the green garden."
         ;; The king tried to dissuade them but to no avail.
         ;; They would not even listen to him; the more he refused, the more urgently they besought him.
         ;; There was nothing to be done, so the king granted their insistent prayer.
         ;; And so the beautiful princesses went out to walk in the garden.
         ;; They beheld the red sun, the trees, and the flowers, and were overjoyed that they had the freedom of the bright world.
         ;; They ran about in the garden and enjoyed themselves - when a sudden whirlwind seized them and carried them off far and high, no one knew whither.
         ;; The alarmed nurses and governesses ran to report this to the king; the king straightway sent his faithful servants in all directions, promising a great reward to him who should find traces of the princesses.
         ;; The servants traveled and traveled but did not discover anything and came back no wiser than they had set out.
         ;; The king called his grand council together and asked his councilors and boyars whether anyone among them would undertake to search for his daughters.
         ;; To any man who might find them, he said, he would give the princess of his choice in marriage, and a rich dowry.
         ;; The king asked once and the boyars were silent; he asked a second time and they still did not answer; he asked a third time and no one made a sound!
         ;; The king burst into tears.
         ;; "Apparently I have no friends or helpers here," he said, and ordered that a call be issued throughout the kingdom.
         ;; At that time there lived in one village a poor widow who had three sons; they were mighty champions.
         ;; All of them were born in one night - the eldest in the evening, the second at midnight, and the youngest in the early dawn, and therefore they were called Evening, Midnight, and Dawn.
         ;; When the king's call reached them, they straightway asked for their mother's blessing, made ready for their journey, and rode to the capital city.
         ;; They came to the king, bowed low, and said: "Rule for many years, sovereign!
         ;; We have come to you not to celebrate a feast, but to perform a task.
         ;; Give us leave to go in search of your daughters."
         ;; "Hail, good youths!
         ;; What are your names?"
         ;; "We are three brothers - Evening, Midnight, and Dawn."
         ;; "What shall I give you for your voyage?"
         ;; "We do not need anything, sire; only do not forget our mother, care for her in her poverty and old age."
         ;; The king took the old woman into his palace, and ordered that she be given food and drink from his table and clothes and shoes from his stores.
         ;; The good youths set out on their way.
         ;; They rode one month, a second, and a third; then they came to a wide desert steppe.
         ;; Beyond that steppe was a thick forest, and close to the forest stood a little hut.
         ;; They knocked at the window and there was no answer; they entered and no one was in the hut.
         ;; "Well, brothers," said one of the three, "let us stop here for a time and rest from our travels."
         ;; They undressed, prayed to God, and went to sleep.
         ;; Next morning Dawn, the youngest brother, said to Evening, his eldest brother: "We two shall go hunting, and you stay at home and prepare our dinner."
         ;; The eldest brother consented.
         ;; Near the hut there was a shed full of sheep; without thinking much he took the best ram, slaughtered and cleaned it, and put it onto roast for dinner.
         ;; He prepared everything and lay down to rest on a bench.
         ;; Suddenly there was a rumbling noise, the door opened, and there entered a little man as big as a thumb, with a beard a cubit long.
         ;; He cast an angry look around and cried to Evening: "How dared you make yourself at home in my house, how dared you slaughter my ram?"
         ;; Evening answered: "First grow up - otherwise you cannot be seen from the ground!
         ;; I shall take a spoonful of cabbage soup and a crumb of bread and throw them in your eyes!"
         ;; The old man as big as a thumb grew more furious: "I am small but strong!"
         ;; He snatched up a crust of bread and began to beat Evening on the head with it; he beat him till he was half dead and threw him under the bench.
         ;; Then the little old man ate the roasted ram and went into the woods.
         ;; Evening tied a rag around his head and lay moaning.
         ;; The brothers returned and asked him: "What is the matter with you?"
         ;; "Eh, brothers, I made a fire in the stove, but because of the great heat I got a headache; I lay all day like one dazed, I could neither cook nor roast!"
         ;; Next day Dawn and Evening went hunting, and Midnight was left at home to prepare the dinner.
         ;; Midnight made a fire, chose the fattest ram, slaughtered it, and put it in the oven; then he lay on the bench.
         ;; Suddenly there was a rumbling noise, and the old man as big as a thumb, with a beard a cubit long, came in and began to beat and thrash him; he almost beat him to death.
         ;; Then he ate the roasted ram and went into the woods.
         ;; Midnight tied up his head with a handkerchief and lay under the bench and moaned.
         ;; The brothers returned.
         ;; "What is the matter with you?" Dawn asked him.
         ;; "I have a headache from the fumes of the stove, brothers, and I have not prepared your dinner."
         ;; On the third day the two elder brothers went hunting and Dawn stayed at home; he chose the best ram, slaughtered and cleaned it, and put it on to roast.
         ;; Then he lay on the bench.
         ;; Suddenly there was a rumbling noise - and he saw the old man as big as a thumb, with a beard a cubit long, carrying a whole hayrick on his head and holding a huge cask of water in his hand.
         ;; The little old man put down the cask of water, spread the hay over the yard, and began to count his sheep.
         ;; He saw that another ram was missing, grew angry, ran to the house, jumped at Dawn, and hit him on the head with all his strength; Dawn jumped up, grabbed the little old man by his long beard, and began to drag him around, repeating: "Look before you leap, look before you leap!"
         ;; The old man as big as a thumb, with a beard a cubit long, began to implore him: "Have pity on me, mighty champion, do not put me to death, let my soul repent!"
         ;; Dawn dragged him out into the yard, led him to an oaken pillar, and fastened his beard to the pillar with a big iron spike; then he returned to the house and sat down to wait for his brothers.
         ;; The brothers came back from their hunting and were amazed to find him safe and sound.
         ;; Dawn smiled and said: "Come with me, brothers, I have caught your fumes and fastened them to a pillar."
         ;; They went into the yard, they looked - but the old man as big as a thumb had long since run away.
         ;; But half of his beard dangled from the pillar, and blood was spattered over his tracks.
         ;; Following this clue, the brothers came to a deep hole in the ground.
         ;; Dawn went to the woods, gathered lime bast, wound a rope, and told his brothers to drop him underground.
         ;; Evening and Midnight dropped him into the hole.
         ;; He found himself in the other world, released himself from the rope, and walked straight ahead.
         ;; He walked and walked, and saw a copper castle.
         ;; He entered the castle, and the youngest princess, rosier than a pink rose, whiter than white snow, came out to meet him and asked him kindly: "How have you come here, good youth - of your own will or by compulsion?"
         ;; "Your father has sent me in search of you, princess."
         ;; She straightway seated him at the table, gave him meat and drink, and then handed him a phial with the water of strength.
         ;; "Drink of this water," she said, "and you will have added strength."
         ;; Dawn drank the phial of water and felt great power in himself.
         ;; "Now," he thought, "I can get the better of anyone."
         ;; At this moment a wild wind arose, and the princess was frightened.
         ;; "Presently," she said, "my dragon will come."
         ;; And she took Dawn by his hand and hid him in the adjoining room.
         ;; A three-headed dragon came flying, struck the damp earth, turned into a youth, and cried: "Oh, there is a Russian smell in here!
         ;; Who is visiting you?"
         ;; "Who could be here?
         ;; You have been flying over Russia and you have the Russian smell in your nostrils - that is why you fancy it is here."
         ;; The dragon asked for food and drink; the princess brought him a variety of meats and drink and poured a sleeping potion into the wine.
         ;; The dragon ate and drank his fill and was soon overwhelmed by drowsiness; he made the princess pick the lice from his hair, lay on her knees, and fell sound asleep.
         ;; The princess called Dawn.
         ;; He came forth, swung his sword, and cut off all of the dragon's three heads; then he made a bonfire, burned the foul dragon and scattered his ashes in the open field.
         ;; "Now farewell, princess!
         ;; I am going to seek your sisters; and when I have found them I shall come back for you," said Dawn, and set out.
         ;; He walked and walked, and came to a silver castle; in that castle lived the second princess.
         ;; Dawn killed a six-headed dragon there and went on.
         ;; After a long time or a short time, he reached a golden castle, and in that castle lived the eldest princess; Dawn killed a twelve-headed dragon and freed that princess from captivity.
         ;; The princess was overjoyed, made ready to return home, went out into the wide courtyard, waved a red handkerchief, and the golden kingdom rolled up into an egg; she took the egg, put it in her pocket, and went with Dawn to seek her sisters.
         ;; These princesses did the same thing: they rolled up their kingdoms into eggs, took them, and all of them went to the hole.
         ;; Evening and Midnight pulled their brother and the three princesses out into the bright world.
         ;; The king was more overjoyed than any tongue can tell; he immediately married Dawn, Evening, and Midnight to his daughters, and at his death made Dawn his heir.

         (t1 "In a certain kingdom there was " (6140 "a king who had three daughters of surpassing beauty") "" (6141 "three daughters of surpassing beauty") ". "
         (t2 "" (6140 "The king") "guarded " (6141 "them") "more carefully than his most precious treasure ; " (6140 "he") "built underground chambers and kept his daughters there like birds in a cage , so that rough winds could not blow upon " (6141 "them") "nor the red sun scorch " (6141 "them") "with his rays . "
         (t3 "One day " (6141 "the princesses") "read in a certain book that there was a marvelous bright world , and when " (6140 "the king") "came to visit " (6141 "them") ", " (6141 "they") "straightway began to implore " (6140 "him") "with tears in their eyes , saying : ' " (6140 "Sovereign, our father") "" (6140 "Sovereign, our father") "" (6141 "us") "out to see the bright world and walk in the green garden . ' "
         (t4 "" (6140 "The king") "tried to dissuade " (6141 "them") "but to no avail . "
         (t5 "" (6141 "They") "would not even listen to " (6140 "him") "; the more " (6140 "he") "refused , the more urgently " (6141 "they") "besought " (6140 "him") ". "
         (t6 "There was nothing to be done , so " (6140 "the king") "granted their insistent prayer . "
         (t7 "And so " (6141 "the beautiful princesses") "went out to walk in the garden . "
         (t8 "" (6141 "They") "beheld the red sun , the trees , and the flowers , and were overjoyed that " (6141 "they") "had the freedom of the bright world . "
         (t9 "" (6141 "They") "ran about in the garden and enjoyed " (6141 "themselves") "- when a sudden whirlwind seized " (6141 "them") "and carried " (6141 "them") "off far and high , no one knew whither . "
         (t10 "The alarmed " (6161 "nurses") "and governesses ran to report this to " (6140 "the king") "; " (6140 "the king") "straightway sent his faithful servants in all directions , promising a great reward to " (6166 "him who should find traces of the princesses") "find traces of the princesses . "
         (t11 "The servants traveled and traveled but did not discover anything and came back no wiser than they had set out . "
         (t12 "" (6140 "The king") "called his " (6169 "his grand council") "together and asked his councilors and boyars whether anyone among " (6169 "them") "would undertake to search for his " (6141 "his daughters") ". "
         (t13 "To any man who might find " (6141 "them") ", " (6140 "he") "said , " (6140 "he") "would give " (6174 "the princess of his choice") "" (6174 "the princess of his choice") "and a rich dowry . "
         (t14 "" (6140 "The king") "asked once and " (6171 "the boyars") "were silent ; " (6140 "he") "asked a second time and " (6171 "they") "still did not answer ; " (6140 "he") "asked a third time and no one made a sound ! "
         (t15 "" (6140 "The king") "burst into tears . "
         (t16 "' Apparently " (6140 "I") "have no friends or helpers " (6169 "here") ", ' " (6140 "he") "said , and ordered that a call be issued throughout the kingdom . "
         (t17 "At that time there lived in one village " (6190 "a poor widow who had three sons") "three sons ; they were mighty champions . "
         (t18 "All of them were born in one night - the eldest in the evening , " (6195 "the second") "at midnight , and the youngest in the early dawn , and therefore they were called Evening , " (6195 "Midnight") ", and Dawn . "
         (t19 "When the " (6140 "king") "'s call reached them , they straightway asked for their " (6190 "their mother") "'s blessing , made ready for their journey , and rode to the capital city . "
         (t20 "They came to the king , bowed low , and said : ' Rule for many years , " (6140 "sovereign") "! "
         (t21 "We have come to you not to celebrate a feast , but to perform a task . "
         (t22 "Give us leave to go in search of your " (6141 "your daughters") ". ' "
         (t23 "' Hail , good youths ! "
         (t24 "What are your names ? ' "
         (t25 "' We are three brothers - Evening , " (6195 "Midnight") ", and Dawn . ' "
         (t26 "' What shall " (6140 "I") "give you for your voyage ? ' "
         (t27 "' We do not need anything , " (6140 "sire") "; only do not forget our " (6190 "our mother") ", care for her in her poverty and old age . ' "
         (t28 "" (6140 "The king") "took " (6190 "the old woman") "into his palace , and ordered that " (6190 "she") "be given food and drink from his table and clothes and shoes from his stores . "
         (t29 "The good youths set out on their way . "
         (t30 "They rode one month , a second , and a third ; then they came to a wide desert steppe . "
         (t31 "Beyond that steppe was a thick forest , and close to the forest stood a little hut . "
         (t32 "They knocked at the window and there was no answer ; they entered and no one was in the hut . "
         (t33 "' Well , brothers , ' said one of the three , ' let us stop here for a time and rest from our travels . ' "
         (t34 "They undressed , prayed to " (6230 "God") ", and went to sleep . "
         (t35 "Next morning " (6197 "Dawn, the youngest brother") ", said to Evening , his eldest brother : ' We two shall go hunting , and you stay at home and prepare our dinner . ' "
         (t36 "The eldest brother consented . "
         (t37 "Near the hut there was a shed full of sheep ; without thinking much he took the best ram , slaughtered and cleaned it , and put it onto roast for dinner . "
         (t38 "He prepared everything and lay down to rest on a bench . "
         (t39 "Suddenly there was a rumbling noise , the door opened , and there entered " (6241 "a little man as big as a thumb, with a beard a cubit long") "a beard a cubit long . "
         (t40 "" (6241 "He") "cast an angry look around and cried to Evening : ' How dared you make yourself at home in my house , how dared you slaughter my ram ? ' "
         (t41 "Evening answered : ' First grow up - otherwise " (6241 "you") "can not be seen from the ground ! "
         (t42 "I shall take a spoonful of cabbage soup and a crumb of bread and throw them in your eyes ! ' "
         (t43 "" (6241 "The old man as big as a thumb") "grew more furious : ' " (6241 "I") "am small but strong ! ' "
         (t44 "" (6241 "He") "snatched up a crust of bread and began to beat Evening on the head with it ; " (6241 "he") "beat him till he was half dead and threw him under the bench . "
         (t45 "Then " (6241 "the little old man") "ate the roasted ram and went into the woods . "
         (t46 "Evening tied a rag around his head and lay moaning . "
         (t47 "The brothers returned and asked him : ' What is the matter with you ? ' "
         (t48 "' Eh , brothers , I made a fire in the stove , but because of the great heat I got a headache ; I lay all day like one dazed , I could neither cook nor roast ! ' "
         (t49 "Next day " (6197 "Dawn") "and Evening went hunting , and " (6195 "Midnight") "was left at home to prepare the dinner . "
         (t50 "" (6195 "Midnight") "made a fire , chose the fattest ram , slaughtered it , and put it in the oven ; then " (6195 "he") "lay on the bench . "
         (t51 "Suddenly there was a rumbling noise , and " (6241 "the old man as big as a thumb, with a beard a cubit long") "a beard a cubit long , came in and began to beat and thrash " (6195 "him") "; " (6241 "he") "almost beat " (6195 "him") "to death . "
         (t52 "Then " (6241 "he") "ate the roasted ram and went into the woods . "
         (t53 "" (6195 "Midnight") "tied up his head with a handkerchief and lay under the bench and moaned . "
         (t54 "The brothers returned . "
         (t55 "' What is the matter with " (6195 "you") "? ' " (6197 "Dawn") "asked " (6195 "him") ". "
         (t56 "' " (6195 "I") "have a headache from the fumes of the stove , brothers , and " (6195 "I") "have not prepared your dinner . ' "
         (t57 "On the third day the two elder brothers went hunting and " (6197 "Dawn") "stayed at home ; " (6197 "he") "chose the best ram , slaughtered and cleaned it , and put it on to roast . "
         (t58 "Then " (6197 "he") "lay on the bench . "
         (t59 "Suddenly there was a rumbling noise - and " (6197 "he") "saw " (6241 "the old man as big as a thumb, with a beard a cubit long") "a beard a cubit long , carrying a whole hayrick on his head and holding a huge cask of water in his hand . "
         (t60 "" (6241 "The little old man") "put down the cask of water , spread the hay over the yard , and began to count his sheep . "
         (t61 "" (6241 "He") "saw that another ram was missing , grew angry , ran to the house , jumped at " (6197 "Dawn") ", and hit " (6197 "him") "on the head with all his strength ; " (6197 "Dawn") "jumped up , grabbed " (6241 "the little old man") "by his long beard , and began to drag " (6241 "him") "around , repeating : ' Look before you leap , look before you leap ! ' "
         (t62 "" (6241 "The old man as big as a thumb, with a beard a cubit long") "a beard a cubit long , began to implore " (6197 "him") ": ' Have pity on " (6241 "me") ", " (6197 "mighty champion") ", do not put " (6241 "me") "to death , let my soul repent ! ' "
         (t63 "" (6197 "Dawn") "dragged " (6241 "him") "out into the yard , led " (6241 "him") "to an oaken pillar , and fastened his beard to the pillar with a big iron spike ; then " (6197 "he") "returned to the house and sat down to wait for his brothers . "
         (t64 "The brothers came back from their hunting and were amazed to find " (6197 "him") "safe and sound . "
         (t65 "" (6197 "Dawn") "smiled and said : ' Come with " (6197 "me") ", brothers , " (6197 "I") "have caught your fumes and fastened " (6241 "them") "to a pillar . ' "
         (t66 "They went into the yard , they looked - but " (6241 "the old man as big as a thumb") "had long since run away . "
         (t67 "But half of his beard dangled from the pillar , and blood was spattered over his tracks . "
         (t68 "Following this clue , the brothers came to a deep hole in the ground . "
         (t69 "" (6197 "Dawn") "went to the woods , gathered lime bast , wound a rope , and told his brothers to drop " (6197 "him") "underground . "
         (t70 "Evening and " (6195 "Midnight") "dropped " (6197 "him") "into the hole . "
         (t71 "" (6197 "He") "found " (6197 "himself") "in the other world , released " (6197 "himself") "from the rope , and walked straight ahead . "
         (t72 "" (6197 "He") "walked and walked , and saw a copper castle . "
         (t73 "" (6197 "He") "entered the castle , and " (6294 "the youngest princess, rosier than a pink rose, whiter than white snow") ", came out to meet " (6197 "him") "and asked " (6197 "him") "kindly : ' How have " (6197 "you") "come here , good youth - of your own will or by compulsion ? ' "
         (t74 "' Your " (6140 "Your father") "has sent " (6197 "me") "in search of you , princess . ' "
         (t75 "" (6294 "She") "straightway seated " (6197 "him") "at the table , gave " (6197 "him") "meat and drink , and then handed " (6197 "him") "a phial with the water of strength . "
         (t76 "' Drink of this water , ' " (6294 "she") "said , ' and " (6197 "you") "will have added strength . ' "
         (t77 "" (6197 "Dawn") "drank the phial of water and felt great power in " (6197 "himself") ". "
         (t78 "' Now , ' " (6197 "he") "thought , ' " (6197 "I") "can get the better of anyone . ' "
         (t79 "At this moment a wild wind arose , and " (6294 "the princess") "was frightened . "
         (t80 "' Presently , ' " (6294 "she") "said , ' my " (6305 "my dragon") "will come . ' "
         (t81 "And " (6294 "she") "took " (6197 "Dawn") "by his hand and hid " (6197 "him") "in the adjoining room . "
         (t82 "" (6305 "A three-headed dragon") "came flying , struck the damp earth , turned into " (6305 "a youth") ", and cried : ' Oh , there is a Russian smell in here ! "
         (t83 "Who is visiting " (6294 "you") "? ' "
         (t84 "' Who could be here ? "
         (t85 "" (6305 "You") "have been flying over Russia and " (6305 "you") "have the Russian smell in your nostrils - that is why " (6305 "you") "fancy it is here . ' "
         (t86 "" (6305 "The dragon") "asked for food and drink ; " (6294 "the princess") "brought " (6305 "him") "a variety of meats and drink and poured a sleeping potion into the wine . "
         (t87 "" (6305 "The dragon") "ate and drank his fill and was soon overwhelmed by drowsiness ; " (6305 "he") "made " (6294 "the princess") "pick the lice from his hair , lay on her knees , and fell sound asleep . "
         (t88 "" (6294 "The princess") "called " (6197 "Dawn") ". "
         (t89 "" (6197 "He") "came forth , swung his sword , and cut off all of the " (6305 "dragon") "'s three heads ; then " (6197 "he") "made a bonfire , burned " (6305 "the foul dragon") "and scattered his ashes in the open field . "
         (t90 "' Now farewell , princess ! "
         (t91 "" (6197 "I") "am going to seek your sisters ; and when " (6197 "I") "have found them I shall come back for you , ' said " (6197 "Dawn") ", and set out . "
         (t92 "" (6197 "He") "walked and walked , and came to a silver castle ; in that castle lived " (6332 "the second princess") ". "
         (t93 "" (6197 "Dawn") "killed " (6333 "a six-headed dragon") "there and went on . "
         (t94 "After a long time or a short time , " (6197 "he") "reached a golden castle , and in that castle lived " (6336 "the eldest princess") "; " (6197 "Dawn") "killed " (6337 "a twelve-headed dragon") "and freed " (6336 "that princess") "from captivity . "
         (t95 "" (6336 "The princess") "was overjoyed , made ready to return home , went out into the wide courtyard , waved a red handkerchief , and the golden kingdom rolled up into an egg ; " (6336 "she") "took the egg , put it in her pocket , and went with " (6197 "Dawn") "to seek her sisters . "
         (t96 "These princesses did the same thing : they rolled up their kingdoms into eggs , took them , and all of them went to the hole . "
         (t97 "Evening and " (6195 "Midnight") "pulled their brother and " (6141 "the three princesses") "out into the bright world . "
         (t98 "" (6140 "The king") "was more overjoyed than any tongue can tell ; " (6140 "he") "immediately married Dawn , Evening , and Midnight to his " (6141 "his daughters") ", and at his death made " (6197 "Dawn") "his heir . "

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)
         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m6161 :type FE)
           (m6166 :type GR)
           (m6169 :type GR)
           (m6171 :type GR)
           (m6140 :type MA)
           (m6141 :type FE)
           (m6174 :type FE)
         )
         (:expressions
           ((verb-was m-1 m6141) :name E1)
           ((verb-had m6140 m6141) :name E2)
           ((verb-surpassing m6141 m6141) :name E3)
           ((verb-guarded m6140 m6141) :name E4)
           ((verb-built m6140 m-1) :name E5)
           ((verb-kept m6140 m6141) :name E6)
           ((verb-blow m-1 m6141) :name E7)
           ((verb-scorch m-1 m6141) :name E8)
           ((verb-read m6141 m-1) :name E9)
           ((verb-came m-1 m6141) :name E10)
           ((verb-began m6141 m6140) :name E11)
           ((verb-visit m6140 m6141) :name E12)
           ((verb-implore m6141 m6140) :name E13)
           ((verb-saying m6141 m6141) :name E14)
           ((verb-let m6140 m6141) :name E15)
           ((verb-see m6141 m-1) :name E16)
           ((verb-walk m6141 m-1) :name E17)
           ((verb-tried m6140 m6141) :name E18)
           ((verb-dissuade m6140 m6141) :name E19)
           ((verb-listen m6141 m6140) :name E20)
           ((verb-refused m6140 m-1) :name E21)
           ((verb-besought m6141 m6140) :name E22)
           ((verb-granted m6140 m-1) :name E23)
           ((verb-went m6141 m-1) :name E24)
           ((verb-walk m6141 m-1) :name E25)
           ((verb-beheld m6141 m-1) :name E26)
           ((verb-were m-1 m6141) :name E27)
           ((verb-had m6141 m-1) :name E28)
           ((verb-ran m6141 m-1) :name E29)
           ((verb-enjoyed m6141 m6141) :name E30)
           ((verb-seized m-1 m6141) :name E31)
           ((verb-carried m-1 m6141) :name E32)
           ((verb-ran m6161 m6140) :name E33)
           ((verb-report m6161 m6140) :name E34)
           ((verb-sent m6140 m-1) :name E35)
           ((verb-promising m6140 m6166) :name E36)
           ((verb-find m6166 m6166) :name E37)
           ((verb-called m6140 m6169) :name E38)
           ((verb-asked m6140 m6141) :name E39)
           ((verb-undertake m6169 m6141) :name E40)
           ((verb-search m6169 m6141) :name E41)
           ((verb-said m6140 m6174) :name E42)
           ((verb-find m-1 m6141) :name E43)
           ((verb-give m6140 m6174) :name E44)
           ((verb-asked m6140 m-1) :name E45)
           ((verb-were m-1 m6171) :name E46)
           ((verb-asked m6140 m-1) :name E47)
           ((verb-answer m6171 m-1) :name E48)
           ((verb-asked m6140 m-1) :name E49)
           ((verb-burst m-1 m6140) :name E50)
           ((verb-have m6140 m6169) :name E51)
           ((verb-said m6140 m6169) :name E52)
           ((verb-ordered m6140 m-1) :name E53)
         )
       )
       (phase2
         (:entities
           (m6336 :type FE)
           (m6241 :type MA)
           (m6230 :type MB)
           (m6305 :type MB)
           (m6332 :type FE)
           (m6337 :type MB)
           (m6190 :type FE)
           (m6333 :type MB)
           (m6161 :type FE)
           (m6294 :type FE)
           (m6195 :type MA)
           (m6197 :type MA)
           (m6166 :type GR)
           (m6169 :type GR)
           (m6171 :type GR)
           (m6140 :type MA)
           (m6141 :type FE)
           (m6174 :type FE)
         )
         (:expressions
           ((verb-lived m6190 m-1) :name E54)
           ((verb-had m6190 m-1) :name E55)
           ((verb-born m-1 m6195) :name E56)
           ((verb-called m-1 m6195) :name E57)
           ((verb-reached m6140 m-1) :name E58)
           ((verb-asked m-1 m6190) :name E59)
           ((verb-rode m-1 m6140) :name E60)
           ((verb-said m-1 m6140) :name E61)
           ((verb-Rule m6140 m-1) :name E62)
           ((verb-Give m-1 m6141) :name E63)
           ((verb-go m-1 m6141) :name E64)
           ((verb-are m-1 m6195) :name E65)
           ((verb-give m6140 m-1) :name E66)
           ((verb-need m-1 m6140) :name E67)
           ((verb-forget m-1 m6190) :name E68)
           ((verb-took m6140 m6190) :name E69)
           ((verb-ordered m6140 m6190) :name E70)
           ((verb-given m-1 m6190) :name E71)
           ((verb-given m-1 m6190) :name E72)
           ((verb-prayed m-1 m6230) :name E73)
           ((verb-said m6197 m-1) :name E74)
           ((verb-entered m6241 m-1) :name E75)
           ((verb-cast m6241 m-1) :name E76)
           ((verb-cried m6241 m-1) :name E77)
           ((verb-answered m-1 m6241) :name E78)
           ((verb-seen m-1 m6241) :name E79)
           ((verb-grew m-1 m6241) :name E80)
           ((verb-am m-1 m6241) :name E81)
           ((verb-snatched m6241 m-1) :name E82)
           ((verb-began m6241 m-1) :name E83)
           ((verb-beat m6241 m-1) :name E84)
           ((verb-beat m6241 m-1) :name E85)
           ((verb-threw m6241 m-1) :name E86)
           ((verb-ate m6241 m-1) :name E87)
           ((verb-went m6241 m-1) :name E88)
           ((verb-went m6197 m-1) :name E89)
           ((verb-left m-1 m6195) :name E90)
           ((verb-prepare m6195 m-1) :name E91)
           ((verb-made m6195 m-1) :name E92)
           ((verb-chose m6195 m-1) :name E93)
           ((verb-slaughtered m6195 m-1) :name E94)
           ((verb-put m6195 m-1) :name E95)
           ((verb-lay m-1 m6195) :name E96)
           ((verb-came m-1 m6241) :name E97)
           ((verb-thrash m6241 m6195) :name E98)
           ((verb-began m6241 m6195) :name E99)
           ((verb-beat m6241 m6195) :name E100)
           ((verb-beat m6241 m6195) :name E101)
           ((verb-ate m6241 m-1) :name E102)
           ((verb-went m6241 m-1) :name E103)
           ((verb-tied m6195 m-1) :name E104)
           ((verb-lay m-1 m6195) :name E105)
           ((verb-moaned m6195 m-1) :name E106)
           ((verb-is m-1 m6195) :name E107)
           ((verb-asked m6197 m6195) :name E108)
           ((verb-have m6195 m-1) :name E109)
           ((verb-prepared m6195 m-1) :name E110)
           ((verb-stayed m-1 m6197) :name E111)
           ((verb-chose m6197 m-1) :name E112)
           ((verb-cleaned m6197 m-1) :name E113)
           ((verb-slaughtered m6197 m-1) :name E114)
           ((verb-put m6197 m-1) :name E115)
           ((verb-roast m6197 m-1) :name E116)
           ((verb-lay m-1 m6197) :name E117)
           ((verb-saw m6197 m6241) :name E118)
           ((verb-carrying m6241 m-1) :name E119)
           ((verb-holding m6241 m-1) :name E120)
           ((verb-put m6241 m-1) :name E121)
           ((verb-spread m6241 m-1) :name E122)
           ((verb-count m6241 m-1) :name E123)
           ((verb-began m6241 m-1) :name E124)
           ((verb-saw m6241 m-1) :name E125)
           ((verb-grew m-1 m6241) :name E126)
           ((verb-ran m6241 m-1) :name E127)
           ((verb-jumped m6241 m6197) :name E128)
           ((verb-hit m6241 m6197) :name E129)
           ((verb-jumped m6197 m-1) :name E130)
           ((verb-grabbed m6197 m6241) :name E131)
           ((verb-began m6197 m6241) :name E132)
           ((verb-drag m6197 m6241) :name E133)
           ((verb-repeating m6197 m-1) :name E134)
           ((verb-began m6241 m6197) :name E135)
           ((verb-implore m6241 m6197) :name E136)
           ((verb-Have m6197 m6241) :name E137)
           ((verb-let m6197 m-1) :name E138)
           ((verb-put m-1 m6241) :name E139)
           ((verb-dragged m6197 m6241) :name E140)
           ((verb-led m6197 m6241) :name E141)
           ((verb-fastened m6197 m-1) :name E142)
           ((verb-returned m-1 m6197) :name E143)
           ((verb-sat m-1 m6197) :name E144)
           ((verb-wait m-1 m6197) :name E145)
           ((verb-find m-1 m6197) :name E146)
           ((verb-amazed m6197 m-1) :name E147)
           ((verb-smiled m6197 m-1) :name E148)
           ((verb-said m6197 m6197) :name E149)
           ((verb-Come m-1 m6197) :name E150)
           ((verb-caught m6197 m-1) :name E151)
           ((verb-fastened m6197 m6241) :name E152)
           ((verb-run m6241 m-1) :name E153)
           ((verb-went m6197 m-1) :name E154)
           ((verb-gathered m6197 m-1) :name E155)
           ((verb-wound m6197 m-1) :name E156)
           ((verb-told m6197 m6197) :name E157)
           ((verb-drop m-1 m6197) :name E158)
           ((verb-dropped m6195 m6197) :name E159)
           ((verb-found m6197 m6197) :name E160)
           ((verb-released m6197 m6197) :name E161)
           ((verb-walked m6197 m-1) :name E162)
           ((verb-walked m6197 m-1) :name E163)
           ((verb-walked m6197 m-1) :name E164)
           ((verb-saw m6197 m-1) :name E165)
           ((verb-entered m6197 m-1) :name E166)
           ((verb-came m-1 m6294) :name E167)
           ((verb-meet m6294 m6197) :name E168)
           ((verb-asked m6294 m6197) :name E169)
           ((verb-come m-1 m6197) :name E170)
           ((verb-sent m6140 m6197) :name E171)
           ((verb-seated m6294 m6197) :name E172)
           ((verb-gave m6294 m6197) :name E173)
           ((verb-handed m6294 m6197) :name E174)
           ((verb-said m6294 m6197) :name E175)
           ((verb-have m6197 m-1) :name E176)
           ((verb-drank m6197 m-1) :name E177)
           ((verb-felt m6197 m6197) :name E178)
           ((verb-get m6197 m-1) :name E179)
           ((verb-thought m6197 m6197) :name E180)
           ((verb-was m-1 m6294) :name E181)
           ((verb-come m-1 m6305) :name E182)
           ((verb-said m6294 m6305) :name E183)
           ((verb-took m6294 m6197) :name E184)
           ((verb-hid m6294 m6197) :name E185)
           ((verb-came m-1 m6305) :name E186)
           ((verb-flying m-1 m6305) :name E187)
           ((verb-struck m6305 m-1) :name E188)
           ((verb-turned m-1 m6305) :name E189)
           ((verb-cried m6305 m-1) :name E190)
           ((verb-visiting m-1 m6294) :name E191)
           ((verb-flying m-1 m6305) :name E192)
           ((verb-have m6305 m-1) :name E193)
           ((verb-is m-1 m6305) :name E194)
           ((verb-fancy m6305 m-1) :name E195)
           ((verb-asked m6305 m-1) :name E196)
           ((verb-brought m6294 m6305) :name E197)
           ((verb-poured m6294 m-1) :name E198)
           ((verb-ate m6305 m-1) :name E199)
           ((verb-drank m6305 m-1) :name E200)
           ((verb-overwhelmed m-1 m6305) :name E201)
           ((verb-made m6305 m6294) :name E202)
           ((verb-lay m-1 m6305) :name E203)
           ((verb-pick m6294 m-1) :name E204)
           ((verb-fell m-1 m6294) :name E205)
           ((verb-called m6294 m6197) :name E206)
           ((verb-came m-1 m6197) :name E207)
           ((verb-swung m6197 m-1) :name E208)
           ((verb-cut m6197 m6305) :name E209)
           ((verb-made m6197 m-1) :name E210)
           ((verb-burned m6197 m6305) :name E211)
           ((verb-scattered m6197 m-1) :name E212)
           ((verb-seek m6197 m-1) :name E213)
           ((verb-going m6197 m-1) :name E214)
           ((verb-said m6197 m6197) :name E215)
           ((verb-found m6197 m-1) :name E216)
           ((verb-come m-1 m6197) :name E217)
           ((verb-set m6197 m-1) :name E218)
           ((verb-walked m6197 m-1) :name E219)
           ((verb-walked m6197 m-1) :name E220)
           ((verb-came m-1 m6197) :name E221)
           ((verb-lived m6332 m-1) :name E222)
           ((verb-killed m6197 m6333) :name E223)
           ((verb-went m6197 m-1) :name E224)
           ((verb-reached m6197 m-1) :name E225)
           ((verb-lived m-1 m6336) :name E226)
           ((verb-killed m6197 m6337) :name E227)
           ((verb-freed m6197 m6336) :name E228)
           ((verb-was m-1 m6336) :name E229)
           ((verb-return m-1 m6336) :name E230)
           ((verb-made m-1 m6336) :name E231)
           ((verb-went m6336 m-1) :name E232)
           ((verb-waved m6336 m-1) :name E233)
           ((verb-took m6336 m-1) :name E234)
           ((verb-put m6336 m-1) :name E235)
           ((verb-seek m6336 m-1) :name E236)
           ((verb-went m6336 m6197) :name E237)
           ((verb-pulled m6195 m6141) :name E238)
         )
       )
       (phase3
         (:entities
           (m6336 :type FE)
           (m6241 :type MA)
           (m6230 :type MB)
           (m6305 :type MB)
           (m6332 :type FE)
           (m6337 :type MB)
           (m6190 :type FE)
           (m6333 :type MB)
           (m6161 :type FE)
           (m6294 :type FE)
           (m6195 :type MA)
           (m6197 :type MA)
           (m6166 :type GR)
           (m6169 :type GR)
           (m6171 :type GR)
           (m6140 :type MA)
           (m6141 :type FE)
           (m6174 :type FE)
         )
         (:expressions
           ((verb-was m-1 m6140) :name E239)
           ((verb-married m6140 m6141) :name E240)
           ((verb-made m6140 m6197) :name E241)
         )
       )

     )
   )
)
    