
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-1
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2))

       )
       (:templates
         ;; A dragon appeared near Kiev; he took heavy tribute from the people - a lovely maiden from every house, whom he then devoured.
         ;; Finally, it was the fate of the tsar's daughter to go to the dragon.

         (t1 "A dragon appeared near Kiev ; " (E1 "" (m1084 "he") "took heavy tribute from the people - " (m1088 "a lovely maiden from every house, whom he then devoured") "" (m1084 "he") "" ) "" (m1088 "a lovely maiden from every house, whom he then devoured") "")
         (t2 "Finally , it was the fate of the tsar 's daughter to go to the dragon . ")
         (t1001 (EXTRA1  (m1088 "a lovely maiden from every house, whom he then devoured") " is the " (Other "Other") ) ".")
         (t1002 (EXTRA2  (m1092 "tsar") " is the " (Other "Other") ) ".")
         (t1003 (EXTRA3  (m1091 "the tsar's daughter") " is the " (Prize "Prize") ) ".")
         (t1004 (EXTRA4  (m1084 "he") " is the " (Villain "Villain") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m1088 :type FE)
           (m1092 :type MA)
           (m1091 :type FE)
           (m1084 :type MB)
         )
         (:expressions
           ((levin-11-3 m1084 m1084) :name E1)
           ((roleOther m1088) :name EXTRA0)
           ((roleOther m1092) :name EXTRA1)
           ((rolePrize m1091) :name EXTRA2)
           ((roleVillain m1084) :name EXTRA3)
         )
       )

     )
   )
)
    