
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-3
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2 phase3 phase4))
         (phase1 (:s  t1 t2 t3))
         (phase2 (:s  t4))
         (phase3 (:s  t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21))
         (phase4 (:s  t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42 t43 t44 t45 t46 t47 t48 t49 t50 t51 t52 t53 t54 t55 t56 t57 t58 t59 t60 t61 t62 t63 t64))

       )
       (:templates
         ;; In a certain kingdom in a certain land there lived one Bukhtan Bukhtanovich, who had a stove built on pillars in the middle of a field.
         ;; He lay on the stove in cockroach milk up to his elbows.
         ;; A fox came to him and said: "Bukhtan Bukhtanovich, would you like me to marry you to the tsar's daughter?"
         ;; "Do you have any money?"
         ;; "Hand it over!"
         ;; The fox took the coin, exchanged it for smaller coins - kopeks, pennies, and halfpennies, went to the tsar, and said: "Tsar, give me a quart measure to measure Bukhtan Bukhtanovich's money."
         ;; The tsar said: "Take one!"
         ;; The fox took it home, stuck one kopek behind the hoop around the measure, brought it back to the tsar, and said: "Tsar, a quart measure is not big enough; give me a peck measure to measure Bukhtan Bukhtanovich's money."
         ;; "Take one!"
         ;; The fox took it home, stuck a kopek behind the hoop of the measure, and brought it back to the tsar.
         ;; "Tsar, a peck measure is not big enough; give me a bushel measure."
         ;; "Take one!"
         ;; The Fox took it home, stuck what remained of his coins behind the hoop, and brought it back to the tsar.
         ;; He said: "Have you measured all his money, little fox?"
         ;; The fox answered: "All of it.
         ;; Now, tsar, I have come for a good purpose: give your daughter in marriage to Bukhtan Bukhtanovich."
         ;; "Very well; show me the suitor."
         ;; The fox ran home.
         ;; "Bukhtan Bukhtanovich, have you any clothes?
         ;; Put them on."
         ;; He dressed and, accompanied by the fox, went to the tsar.
         ;; The fox gave Bukhtan a push and he fell into the mud.
         ;; The fox ran to him.
         ;; "What is the matter with you, Bukhtan Bukhtanovich?"
         ;; Saying this, the fox smeared him with mud all over.
         ;; "Wait here, Bukhtan Bukhtanovich, I shall run to the tsar."
         ;; The fox came to the tsar and said: "Tsar, I was walking with Bukhtan Bukhtanovich on a board over a ditch - it was a wretched little board; we were not careful enough and somehow fell into the mud.
         ;; Bukhtan Bukhtanovich is all dirty and unfit to come to town; have you some clothes you could lend him?"
         ;; "Here, take these."
         ;; The fox took the clothes and came to Bukhtan Bukhtanovich.
         ;; "Here, change your clothes, Bukhtan, and let us go."
         ;; They came to the tsar, and at the tsar's palace the table was already set.
         ;; Bukhtan did not look at anything except himself: he had never seen such clothes in his life.
         ;; The tsar winked to the fox: "Little fox, why does this Bukhtan Bukhtanovich look only at himself?"
         ;; "Tsar, I think he is ashamed to be wearing such clothes; never in his life has he worn such mean garments.
         ;; Tsar, give him the garment that you yourself wear on Easter Sunday."
         ;; And to Bukhtan the fox whispered: "Don't look at yourself!"
         ;; Bukhtan Bukhtanovich stared at a chair - it was a gilded one.
         ;; The tsar again whispered to the fox: "Little fox, why does Bukhtan Bukhtanovich look only at that chair?"
         ;; "Tsar, in his house such chairs stand only in the bathhouse."
         ;; The tsar flung the chair out of the room.
         ;; The fox whispered to Bukhtan: "Do not look at one thing; look here a bit and there a bit."
         ;; They began to talk about the purpose of their visit, the match.
         ;; And then they celebrated the wedding -does a wedding take long in a tsar's palace?
         ;; There no beer need be brewed, no wine distilled - everything is ready.
         ;; Three ships were loaded for Bukhtan Bukhtanovich and they traveled homeward.
         ;; Bukhtan Bukhtanovich and his wife were on one of the ships, and the fox ran along the shore.
         ;; Bukhtan saw his stove and cried: "Little fox, little fox, there is my stove."
         ;; "Be quiet, Bukhtan Bukhtanovich, that stove is a disgrace."
         ;; Bukhtan Bukhtanovich sailed on, and the fox ran ahead of him on the shore.
         ;; He came to a hill and climbed it.
         ;; On the hill stood a huge stone house, and around it was an enormous kingdom.
         ;; The fox went into the house and at first saw no one; then he ran into a chamber, and there in the best bed lay Dragon, Son of the Dragon, stretching himself.
         ;; Raven, Son of the Raven, was perched on the chimney, and Cat, Son of the Cat, sat on a throne.
         ;; The fox said: "Why are you sitting here?
         ;; The tsar is coming with fire and the tsarina with lightning, they will scorch and burn you."
         ;; "Little fox, whither shall we go?"
         ;; "Cat, Son of the Cat, go into the barrel."
         ;; And the fox sealed him up in the barrel.
         ;; "Raven, Son of the Raven, go into the mortar!"
         ;; And the fox sealed him up in the mortar; then he wrapped Dragon, Son of the Dragon, in straw and took him out into the street.
         ;; The ships arrived.
         ;; The fox ordered all the beasts to be thrown into the water; the Cossacks threw them in at once.
         ;; Bukhtan Bukhtanovich moved all his possessions into that house; there he lived happily and prospered, ruled and governed, and there he ended his life.

         (t1 "In a certain kingdom in a certain land there lived " (STORY3-m3141 "one Bukhtan Bukhtanovich, who had a stove built on pillars in the middle of a field") " a stove built on pillars in the middle of a field . ")
         (t2 "" (STORY3-m3141 "He") " lay on the stove in cockroach milk up to his elbows . ")
         (t3 "" (STORY3-m3148 "A fox") " came to " (STORY3-m3141 "him") " and said : ' " (STORY3-m3141 "Bukhtan Bukhtanovich") " , would " (STORY3-m3141 "you") " like " (STORY3-m3148 "me") " to marry " (STORY3-m3141 "you") " to " (STORY3-m3149 "the tsar's daughter") " ? ' ")
         (t1001 (STORY3-EXTRA1  (STORY3-m3141 "you") " is the " (Hero "Hero") ) ".")
         (t1002 (STORY3-EXTRA2  (STORY3-m3148 "me") " is the " (Other "Other") ) ".")
         (t1003 (STORY3-EXTRA3  (STORY3-m3149 "the tsar's daughter") " is the " (Prize "Prize") ) ".")
         (t1004 (STORY3-EXTRA4  (STORY3-m3150 "tsar") " is the " (Other "Other") ) ".")
         (t4 "' Do " (STORY3-m3148 "you") " have any money ? ' ")
         (t1005 (STORY3-EXTRA5  (STORY3-m3141 "you") " is the " (Hero "Hero") ) ".")
         (t1006 (STORY3-EXTRA6  (STORY3-m3148 "you") " is the " (Other "Other") ) ".")
         (t1007 (STORY3-EXTRA7  (STORY3-m3149 "the tsar's daughter") " is the " (Prize "Prize") ) ".")
         (t1008 (STORY3-EXTRA8  (STORY3-m3150 "tsar") " is the " (Other "Other") ) ".")
         (t5 "' Hand it over ! ' ")
         (t6 "" (STORY3-m3148 "The fox") " took the coin , exchanged it for smaller coins - kopeks , pennies , and halfpennies , went to " (STORY3-m3150 "the tsar") " , and said : ' " (STORY3-m3150 "Tsar") " , give me a quart measure to measure " (STORY3-m3141 "Bukhtan Bukhtanovich") " 's money . ' ")
         (t7 "" (STORY3-m3150 "The tsar") " said : ' Take one ! ' ")
         (t8 "" (STORY3-m3148 "The fox") " took it home , stuck one kopek behind the hoop around the measure , brought it back to " (STORY3-m3150 "the tsar") " , and said : ' " (STORY3-m3150 "Tsar") " , a quart measure is not big enough ; give " (STORY3-m3148 "me") " a peck measure to measure " (STORY3-m3141 "Bukhtan Bukhtanovich") " 's money . ' ")
         (t9 "' Take one ! ' ")
         (t10 "" (STORY3-m3148 "The fox") " took it home , stuck a kopek behind the hoop of the measure , and brought it back to " (STORY3-m3150 "the tsar") " . ")
         (t11 "' " (STORY3-m3150 "Tsar") " , a peck measure is not big enough ; give " (STORY3-m3148 "me") " a bushel measure . ' ")
         (t12 "' Take one ! ' ")
         (t13 "" (STORY3-m3148 "The Fox") " took it home , stuck what remained of his coins behind the hoop , and brought it back to " (STORY3-m3150 "the tsar") " . ")
         (t14 "" (STORY3-m3150 "He") " said : ' Have " (STORY3-m3148 "you") " measured all his money , " (STORY3-m3148 "little fox") " ? ' ")
         (t15 "" (STORY3-m3148 "The fox") " answered : ' All of it . ")
         (t16 "Now , " (STORY3-m3150 "tsar") " , " (STORY3-m3148 "I") " have come for a good purpose : give your " (STORY3-m3149 "your daughter") " in marriage to " (STORY3-m3141 "Bukhtan Bukhtanovich") " . ' ")
         (t17 "' Very well ; show " (STORY3-m3150 "me") " " (STORY3-m3141 "the suitor") " . ' ")
         (t18 "" (STORY3-m3148 "The fox") " ran home . ")
         (t19 "' " (STORY3-m3141 "Bukhtan Bukhtanovich") " , have " (STORY3-m3141 "you") " any clothes ? ")
         (t20 "Put them on . ' ")
         (t21 "" (STORY3-m3141 "He") " dressed and , accompanied by " (STORY3-m3148 "the fox") " , went to " (STORY3-m3150 "the tsar") " . ")
         (t1009 (STORY3-EXTRA9  (STORY3-m3141 "He") " is the " (Hero "Hero") ) ".")
         (t1010 (STORY3-EXTRA10  (STORY3-m3148 "the fox") " is the " (Other "Other") ) ".")
         (t1011 (STORY3-EXTRA11  (STORY3-m3149 "your daughter") " is the " (Prize "Prize") ) ".")
         (t1012 (STORY3-EXTRA12  (STORY3-m3150 "the tsar") " is the " (Other "Other") ) ".")
         (t22 "" (STORY3-VERB9 "" (STORY3-m3148 "The fox") " gave " (STORY3-m3141 "Bukhtan") " " ) "a push and " (STORY3-m3141 "he") " fell into the mud . ")
         (t23 "" (STORY3-m3148 "The fox") " ran to " (STORY3-m3141 "him") " . ")
         (t24 "' What is the matter with " (STORY3-m3141 "you, Bukhtan Bukhtanovich") " ? ' ")
         (t25 "Saying this , " (STORY3-m3148 "the fox") " smeared " (STORY3-m3141 "him") " with mud all over . ")
         (t26 "' Wait here , " (STORY3-m3141 "Bukhtan Bukhtanovich") " , " (STORY3-m3148 "I") " shall run to " (STORY3-m3150 "the tsar") " . ' ")
         (t27 "" (STORY3-m3148 "The fox") " came to " (STORY3-m3150 "the tsar") " and said : ' " (STORY3-m3150 "Tsar") " , " (STORY3-m3148 "I") " was walking with " (STORY3-m3141 "Bukhtan Bukhtanovich") " on a board over a ditch - it was a wretched little board ; we were not careful enough and somehow fell into the mud . ")
         (t28 "" (STORY3-m3141 "Bukhtan Bukhtanovich") " is all dirty and unfit to come to town ; have " (STORY3-m3150 "you") " some clothes " (STORY3-m3150 "you") " could lend " (STORY3-m3141 "him") " ? ' ")
         (t29 "' Here , take these . ' ")
         (t30 "" (STORY3-m3148 "The fox") " took the clothes and came to " (STORY3-m3141 "Bukhtan Bukhtanovich") " . ")
         (t31 "' Here , change your clothes , " (STORY3-m3141 "Bukhtan") " , and let us go . ' ")
         (t32 "They came to " (STORY3-m3150 "the tsar") " , and at the " (STORY3-m3150 "tsar") " 's palace the table was already set . ")
         (t33 "" (STORY3-m3141 "Bukhtan") " did not look at anything " (STORY3-m3141 "anything except himself") " : " (STORY3-m3141 "he") " had never seen such clothes in his life . ")
         (t34 "" (STORY3-m3150 "The tsar") " winked to " (STORY3-m3148 "the fox") " : ' " (STORY3-m3148 "Little fox") " , why does " (STORY3-m3141 "this Bukhtan Bukhtanovich") " look only at " (STORY3-m3141 "himself") " ? ' ")
         (t35 "' " (STORY3-m3150 "Tsar") " , " (STORY3-m3148 "I") " think " (STORY3-m3141 "he") " is ashamed to be wearing such clothes ; never in his life has " (STORY3-m3141 "he") " worn such mean garments . ")
         (t36 "" (STORY3-m3150 "Tsar") " , give " (STORY3-m3141 "him") " the garment that " (STORY3-m3150 "you yourself") " wear on Easter Sunday . ' ")
         (t37 "And to " (STORY3-m3141 "Bukhtan") " " (STORY3-m3148 "the fox") " whispered : ' Do n't look at " (STORY3-m3141 "yourself") " ! ' ")
         (t38 "" (STORY3-m3141 "Bukhtan Bukhtanovich") " stared at a chair - it was a gilded one . ")
         (t39 "" (STORY3-m3150 "The tsar") " again whispered to " (STORY3-m3148 "the fox") " : ' " (STORY3-m3148 "Little fox") " , why does " (STORY3-m3141 "Bukhtan Bukhtanovich") " look only at that chair ? ' ")
         (t40 "' " (STORY3-m3150 "Tsar") " , in his house such chairs stand only in the bathhouse . ' ")
         (t41 "" (STORY3-m3150 "The tsar") " flung the chair out of the room . ")
         (t42 "" (STORY3-m3148 "The fox") " whispered to " (STORY3-m3141 "Bukhtan") " : ' Do not look at one thing ; look here a bit and there a bit . ' ")
         (t43 "They began to talk about the purpose of their visit , the match . ")
         (t44 "And then they celebrated the wedding - does a wedding take long in a " (STORY3-m3150 "tsar") " 's palace ? ")
         (t45 "There no beer need be brewed , no wine distilled - everything is ready . ")
         (t46 "Three ships were loaded for " (STORY3-m3141 "Bukhtan Bukhtanovich") " and they traveled homeward . ")
         (t47 "" (STORY3-m3141 "Bukhtan Bukhtanovich") " and his wife were on one of the ships , and " (STORY3-m3148 "the fox") " ran along the shore . ")
         (t48 "" (STORY3-m3141 "Bukhtan") " saw his stove and cried : ' " (STORY3-m3148 "Little fox") " , " (STORY3-m3148 "little fox") " , there is my stove . ' ")
         (t49 "' Be quiet , " (STORY3-m3141 "Bukhtan Bukhtanovich") " , that stove is a disgrace . ' ")
         (t50 "" (STORY3-m3141 "Bukhtan Bukhtanovich") " sailed on , and " (STORY3-m3148 "the fox") " ran ahead of " (STORY3-m3141 "him") " on the shore . ")
         (t51 "" (STORY3-m3148 "He") " came to a hill and climbed it . ")
         (t52 "On the hill stood a huge stone house , and around it was an enormous kingdom . ")
         (t53 "" (STORY3-m3148 "The fox") " went into the house and at first saw " (STORY3-m3208 "no one") " ; then " (STORY3-m3148 "he") " ran into a chamber , and there in the best bed lay " (STORY3-m3211 "Dragon, Son of the Dragon") " , stretching " (STORY3-m3211 "himself") " . ")
         (t54 "" (STORY3-m3212 "Raven, Son of the Raven") " , was perched on the chimney , and " (STORY3-m3214 "Cat, Son of the Cat") " , sat on a throne . ")
         (t55 "" (STORY3-m3148 "The fox") " said : ' Why are you sitting here ? ")
         (t56 "" (STORY3-m3150 "The tsar") " is coming with fire and " (STORY3-m3218 "the tsarina") " with lightning , they will scorch and burn you . ' ")
         (t57 "' " (STORY3-m3148 "Little fox") " , whither shall we go ? ' ")
         (t58 "' " (STORY3-m3214 "Cat, Son of the Cat") " , go into the barrel . ' ")
         (t59 "And " (STORY3-m3148 "the fox") " sealed " (STORY3-m3214 "him") " up in the barrel . ")
         (t60 "' " (STORY3-m3212 "Raven, Son of the Raven") " , go into the mortar ! ' ")
         (t61 "And " (STORY3-m3148 "the fox") " sealed " (STORY3-m3212 "him") " up in the mortar ; then " (STORY3-m3148 "he") " wrapped " (STORY3-m3211 "Dragon, Son of the Dragon") " , in straw and took " (STORY3-m3211 "him") " out into the street . ")
         (t62 "The ships arrived . ")
         (t63 "" (STORY3-m3148 "The fox") " ordered all the beasts to be thrown into the water ; " (STORY3-m3226 "the Cossacks") " threw them in at once . ")
         (t64 "" (STORY3-m3141 "Bukhtan Bukhtanovich") " moved all his possessions into that house ; there " (STORY3-m3141 "he") " lived happily and prospered , ruled and governed , and there " (STORY3-m3141 "he") " ended his life . ")
         (t1013 (STORY3-EXTRA13  (STORY3-m3141 "he") " is the " (Hero "Hero") ) ".")
         (t1014 (STORY3-EXTRA14  (STORY3-m3148 "The fox") " is the " (Other "Other") ) ".")
         (t1015 (STORY3-EXTRA15  (STORY3-m3149 "your daughter") " is the " (Prize "Prize") ) ".")
         (t1016 (STORY3-EXTRA16  (STORY3-m3150 "The tsar") " is the " (Other "Other") ) ".")
         (t1017 (STORY3-EXTRA17  (STORY3-m3208 "no one") " is the " (NA "NA") ) ".")
         (t1018 (STORY3-EXTRA18  (STORY3-m3211 "him") " is the " (Villain "Villain") ) ".")
         (t1019 (STORY3-EXTRA19  (STORY3-m3212 "him") " is the " (Other "Other") ) ".")
         (t1020 (STORY3-EXTRA20  (STORY3-m3214 "him") " is the " (Villain "Villain") ) ".")
         (t1021 (STORY3-EXTRA21  (STORY3-m3218 "the tsarina") " is the " (NA "NA") ) ".")
         (t1022 (STORY3-EXTRA22  (STORY3-m3226 "the Cossacks") " is the " (NA "NA") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY3-m3141 :type MA)
           (STORY3-m3148 :type AA)
           (STORY3-m3149 :type FE)
           (STORY3-m3150 :type MA)
         )
         (:expressions
           ((levin-37-7 STORY3-m3148 STORY3-m3141) :name STORY3-VERB1)
           ((levin-31-2 STORY3-m3141 STORY3-m3148) :name STORY3-VERB2)
           ((roleHero STORY3-m3141) :name STORY3-EXTRA0)
           ((roleOther STORY3-m3148) :name STORY3-EXTRA1)
           ((rolePrize STORY3-m3149) :name STORY3-EXTRA2)
           ((roleOther STORY3-m3150) :name STORY3-EXTRA3)
         )
       )
       (phase2
         (:entities
           (STORY3-m3141 :type MA)
           (STORY3-m3148 :type AA)
           (STORY3-m3149 :type FE)
           (STORY3-m3150 :type MA)
         )
         (:expressions
           ((roleHero STORY3-m3141) :name STORY3-EXTRA4)
           ((roleOther STORY3-m3148) :name STORY3-EXTRA5)
           ((rolePrize STORY3-m3149) :name STORY3-EXTRA6)
           ((roleOther STORY3-m3150) :name STORY3-EXTRA7)
         )
       )
       (phase3
         (:entities
           (STORY3-m3141 :type MA)
           (STORY3-m3148 :type AA)
           (STORY3-m3149 :type FE)
           (STORY3-m3150 :type MA)
         )
         (:expressions
           ((levin-37-7 STORY3-m3148 STORY3-m3150) :name STORY3-VERB3)
           ((levin-11-3 STORY3-m3148 STORY3-m3150) :name STORY3-VERB4)
           ((levin-54-1 STORY3-m3148 STORY3-m3141) :name STORY3-VERB5)
           ((levin-37-7 STORY3-m3150 STORY3-m3148) :name STORY3-VERB6)
           ((levin-13-1 STORY3-m3150 STORY3-m3149) :name STORY3-VERB7)
           ((levin-51-7 STORY3-m3148 STORY3-m3141) :name STORY3-VERB8)
           ((roleHero STORY3-m3141) :name STORY3-EXTRA8)
           ((roleOther STORY3-m3148) :name STORY3-EXTRA9)
           ((rolePrize STORY3-m3149) :name STORY3-EXTRA10)
           ((roleOther STORY3-m3150) :name STORY3-EXTRA11)
         )
       )
       (phase4
         (:entities
           (STORY3-m3141 :type MA)
           (STORY3-m3148 :type AA)
           (STORY3-m3149 :type FE)
           (STORY3-m3150 :type MA)
           (STORY3-m3208 :type GR)
           (STORY3-m3211 :type MB)
           (STORY3-m3212 :type AA)
           (STORY3-m3214 :type AA)
           (STORY3-m3218 :type FE)
           (STORY3-m3226 :type GR)
         )
         (:expressions
           ((levin-13-1 STORY3-m3148 STORY3-m3141) :name STORY3-VERB9)
           ((levin-47-5-1 STORY3-m3148 STORY3-m3141) :name STORY3-VERB10)
           ((levin-09-7 STORY3-m3148 STORY3-m3141) :name STORY3-VERB11)
           ((levin-47-5-1 STORY3-m3148 STORY3-m3150) :name STORY3-VERB12)
           ((levin-37-7 STORY3-m3148 STORY3-m3150) :name STORY3-VERB13)
           ((levin-13-1 STORY3-m3150 STORY3-m3141) :name STORY3-VERB14)
           ((levin-30-4 STORY3-m3141 STORY3-m3141) :name STORY3-VERB15)
           ((levin-40-3-1 STORY3-m3150 STORY3-m3148) :name STORY3-VERB16)
           ((levin-29-4 STORY3-m3148 STORY3-m3141) :name STORY3-VERB17)
           ((levin-13-1 STORY3-m3150 STORY3-m3150) :name STORY3-VERB18)
           ((levin-37-3 STORY3-m3148 STORY3-m3141) :name STORY3-VERB19)
           ((levin-37-3 STORY3-m3150 STORY3-m3148) :name STORY3-VERB20)
           ((levin-40-1-2 STORY3-m3141 STORY3-m3148) :name STORY3-VERB21)
           ((levin-30-1 STORY3-m3148 STORY3-m3208) :name STORY3-VERB22)
           ((levin-13-7 STORY3-m3148 STORY3-m3214) :name STORY3-VERB23)
           ((levin-13-7 STORY3-m3148 STORY3-m3212) :name STORY3-VERB24)
           ((levin-09-7 STORY3-m3148 STORY3-m3211) :name STORY3-VERB25)
           ((roleHero STORY3-m3141) :name STORY3-EXTRA12)
           ((roleOther STORY3-m3148) :name STORY3-EXTRA13)
           ((rolePrize STORY3-m3149) :name STORY3-EXTRA14)
           ((roleOther STORY3-m3150) :name STORY3-EXTRA15)
           ((roleNA STORY3-m3208) :name STORY3-EXTRA16)
           ((roleVillain STORY3-m3211) :name STORY3-EXTRA17)
           ((roleOther STORY3-m3212) :name STORY3-EXTRA18)
           ((roleVillain STORY3-m3214) :name STORY3-EXTRA19)
           ((roleNA STORY3-m3218) :name STORY3-EXTRA20)
           ((roleNA STORY3-m3226) :name STORY3-EXTRA21)
         )
       )

     )
   )
)
    