
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-2
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4))
         (phase2 (:s  t5 t6 t7 t8 t9 t10 t11 t12))

       )
       (:templates
         ;; An old man lived with his old wife; they had a daughter and a little son.
         ;; "Daughter, daughter," said the mother, "we are going to work; we shall bring you back a bun, sew you a dress, and buy you a kerchief.
         ;; Be careful, watch over your little brother, do not leave the house."
         ;; The parents went away and the daughter forgot what they had told her; she put her brother on the grass beneath the window, ran out into the street, and became absorbed in games.
         ;; The girl came back and found her brother gone.
         ;; She gasped, and rushed to look in every corner, but could not find him.
         ;; She called him, wept, and lamented that her father and mother would scold her severely; still her little brother did not answer.
         ;; She ran into the open field; the swan geese flashed in the distance and vanished behind a dark forest.
         ;; The swan geese had long had a bad reputation; they had done a great deal of damage and stolen many little children.
         ;; The girl guessed that they had carried off her brother, and rushed after them.
         ;; She ran and ran and saw a stove.
         ;; "Stove, stove, tell me, whither have the geese flown?"

         (t1 "" (E1 "" (m2456 "An old man") " lived with his " (m2457 "his old wife") " " ) "; they had a daughter and a little son . ")
         (t2 "' Daughter , daughter , ' said " (m2457 "the mother") " , ' we are going to work ; we shall bring you back a bun , sew you a dress , and buy " (m2460 "you") " a kerchief . ")
         (t3 "Be careful , watch over your little brother , do not leave the house . ' ")
         (t4 "The parents went away and the daughter forgot what they had told her ; " (m2460 "she") " put her " (m2461 "her brother") " on the grass beneath the window , ran out into the street , and became absorbed in games . ")
         (t1001 (EXTRA1  (m2456 "An old man") " is the " (Other "Other") ) ".")
         (t1002 (EXTRA2  (m2457 "the mother") " is the " (Other "Other") ) ".")
         (t1003 (EXTRA3  (m2460 "she") " is the " (Hero "Hero") ) ".")
         (t1004 (EXTRA4  (m2461 "her brother") " is the " (Other "Other") ) ".")
         (t5 "" (E4 "" (m2460 "The girl") " came back and found her " (m2461 "her brother") " " ) "gone . ")
         (t6 "" (m2460 "She") " gasped , and rushed to look in every corner , but could not find " (m2461 "him") " . ")
         (t7 "" (m2460 "She") " called " (m2461 "him") " , wept , and lamented that her " (m2456 "father") " and mother would scold " (m2460 "her") " severely ; still her little brother did not answer . ")
         (t8 "She ran into the open field ; the swan geese flashed in the distance and vanished behind a dark forest . ")
         (t9 "The swan geese had long had a bad reputation ; " (m2471 "they") " had done a great deal of damage and stolen " (m2479 "many little children") " . ")
         (t10 "" (m2460 "The girl") " guessed that " (m2471 "they") " had carried off her " (m2461 "her brother") " , and rushed after them . ")
         (t11 "" (m2460 "She") " ran and ran and saw " (m2480 "a stove") " . ")
         (t12 "' " (m2480 "Stove") " , stove , tell me , whither have " (m2471 "the geese") " flown ? ' ")
         (t1005 (EXTRA5  (m2471 "the geese") " is the " (Villain "Villain") ) ".")
         (t1006 (EXTRA6  (m2479 "many little children") " is the " (Other "Other") ) ".")
         (t1007 (EXTRA7  (m2480 "Stove") " is the " (Tester "Tester") ) ".")
         (t1008 (EXTRA8  (m2456 "father") " is the " (Other "Other") ) ".")
         (t1009 (EXTRA9  (m2457 "the mother") " is the " (Other "Other") ) ".")
         (t1010 (EXTRA10  (m2460 "She") " is the " (Hero "Hero") ) ".")
         (t1011 (EXTRA11  (m2461 "her brother") " is the " (Other "Other") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m2456 :type MA)
           (m2457 :type FE)
           (m2460 :type FE)
           (m2461 :type MA)
         )
         (:expressions
           ((levin-39-6 m2456 m2457) :name E1)
           ((levin-37-7 m2457 m2460) :name E2)
           ((levin-09-1 m2460 m2461) :name E3)
           ((roleOther m2456) :name EXTRA0)
           ((roleOther m2457) :name EXTRA1)
           ((roleHero m2460) :name EXTRA2)
           ((roleOther m2461) :name EXTRA3)
         )
       )
       (phase2
         (:entities
           (m2471 :type AA)
           (m2479 :type GR)
           (m2480 :type AO)
           (m2456 :type MA)
           (m2457 :type FE)
           (m2460 :type FE)
           (m2461 :type MA)
         )
         (:expressions
           ((levin-29-4 m2460 m2461) :name E4)
           ((levin-29-3 m2460 m2461) :name E5)
           ((levin-33-1 m2456 m2460) :name E6)
           ((levin-13-5-1 m2471 m2479) :name E7)
           ((levin-29-5 m2460 m2471) :name E8)
           ((levin-30-1 m2460 m2480) :name E9)
           ((levin-37-2 m2480 m2471) :name E10)
           ((roleVillain m2471) :name EXTRA4)
           ((roleOther m2479) :name EXTRA5)
           ((roleTester m2480) :name EXTRA6)
           ((roleOther m2456) :name EXTRA7)
           ((roleOther m2457) :name EXTRA8)
           ((roleHero m2460) :name EXTRA9)
           ((roleOther m2461) :name EXTRA10)
         )
       )

     )
   )
)
    