
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-4
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9))
         (phase2 (:s  t10 t11 t12 t13 t14 t15 t16 t17))

       )
       (:templates
         ;; In a certain kingdom in a certain land there lived a king who had three sons.
         ;; One day they said to him: "Father, our gracious sovereign, give us your blessing; we wish to go hunting."
         ;; The father gave them his blessing and they set out in different directions.
         ;; The youngest son rode and rode and lost his way; he came to a clearing, and there lay a dead horse, around which were gathered beasts of many kinds, birds, and reptiles.
         ;; A falcon rose, flew up to the prince, perched on his shoulder, and said: "Prince Ivan, divide that horse among us; it has lain here for thirty years, and we have been quarreling ever since, unable to find a way of sharing it."
         ;; The prince climbed down from his good steed and divided the carcass: he gave the bones to the beasts, the flesh to the birds, the skin to the reptiles, and the head to the ants.
         ;; "Thank you, Prince Ivan," said the falcon.
         ;; "For your kindness you shall be able to turn into a bright falcon or an ant whenever you wish."
         ;; Prince Ivan struck the damp earth, turned into a bright falcon, soared up into the air, and flew to the thrice tenth kingdom.
         ;; The prince flew straight into the royal palace, turned into a goodly youth, and asked the palace guards: "Will your king take me into his service?"
         ;; "Why should he not take such a goodly youth?" they answered.
         ;; Thus he entered the service of that king and lived in his palace for one week, then a second, then a third.
         ;; The king's daughter asked her father: "Father, my sovereign, give me leave to take a ride with Prince Ivan to the crystal mountain."
         ;; The king gave her leave.
         ;; They mounted good steeds and set out.
         ;; When they approached the crystal mountain, a golden goat jumped suddenly out from nowhere.
         ;; The prince chased it; he galloped and galloped, but could not catch the goat, and when he returned the princess had vanished.

         (t1 "In a certain kingdom in a certain land there lived " (STORY4-m2953 "a king who had three sons") " " (STORY4-m2954 "three sons") " . ")
         (t2 "One day " (STORY4-m2956 "they") " said to him : ' " (STORY4-m2958 "Father, our gracious sovereign") " , give " (STORY4-m2960 "us") " your blessing ; " (STORY4-m2963 "we") " wish to go hunting . ' ")
         (t3 "" (STORY4-m2964 "The father") " gave " (STORY4-m2965 "them") " his blessing and " (STORY4-m2968 "they") " set out in different directions . ")
         (t4 "" (STORY4-m2970 "The youngest son") " rode and rode and lost his way ; " (STORY4-m2973 "he") " came to a clearing , and there lay a dead horse , around which were gathered beasts of many kinds , birds , and reptiles . ")
         (t5 "" (STORY4-m2981 "A falcon") " rose , flew up to the prince , perched on his shoulder , and said : ' " (STORY4-m2985 "Prince Ivan") " , divide that horse among " (STORY4-m2987 "us") " ; it has lain here for thirty years , and " (STORY4-m2991 "we") " have been quarreling ever since , unable to find a way of sharing it . ' ")
         (t6 "" (STORY4-m2994 "The prince") " climbed down from his " (STORY4-m2996 "his good steed") " and divided the carcass : " (STORY4-m2998 "he") " gave the bones to the beasts , the flesh to the birds , the skin to the reptiles , and the head to the ants . ")
         (t7 "' Thank " (STORY4-m3007 "you") " , Prince Ivan , ' said " (STORY4-m3009 "the falcon") " . ")
         (t8 "' For your kindness " (STORY4-m3012 "you") " shall be able to turn into a bright falcon or an ant whenever " (STORY4-m3015 "you") " wish . ' ")
         (t9 "" (STORY4-m3016 "Prince Ivan") " struck the damp earth , turned into a bright falcon , soared up into the air , and flew to the thrice tenth kingdom . ")
         (t10 "" (STORY4-VERB6 "" (STORY4-m3024 "The prince") " flew straight into the royal palace , turned into a goodly youth , and asked the palace guards : ' Will your " (STORY4-m3030 "your king") " " ) "take " (STORY4-m3031 "me") " into his service ? ' ")
         (t11 "' Why should " (STORY4-m3034 "he") " not take such a goodly youth ? ' " (STORY4-m3036 "they") " answered . ")
         (t12 "Thus " (STORY4-m3037 "he") " entered the service of " (STORY4-m3039 "that king") " and lived in his palace for one week , then a second , then " (STORY4-m3044 "a third") " . ")
         (t13 "" (STORY4-m3045 "The king's daughter") " asked her father : ' " (STORY4-m3049 "Father, my sovereign") " , give " (STORY4-m3051 "me") " leave to take a ride with " (STORY4-m3054 "Prince Ivan") " to the crystal mountain . ' ")
         (t14 "" (STORY4-m3056 "The king") " gave her leave . ")
         (t15 "" (STORY4-m3059 "They") " mounted " (STORY4-m3060 "good steeds") " and set out . ")
         (t16 "When " (STORY4-m3061 "they") " approached the crystal mountain , " (STORY4-m3063 "a golden goat") " jumped suddenly out from nowhere . ")
         (t17 "" (STORY4-m3065 "The prince") " chased it ; " (STORY4-m3067 "he") " galloped and galloped , but could not catch the goat , and when " (STORY4-m3069 "he") " returned the princess had vanished . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY4-m2953 :type MA)
           (STORY4-m2954 :type MA)
           (STORY4-m2956 :type MA)
           (STORY4-m2958 :type MA)
           (STORY4-m2960 :type MA)
           (STORY4-m2963 :type MA)
           (STORY4-m2964 :type MA)
           (STORY4-m2965 :type MA)
           (STORY4-m2968 :type MA)
           (STORY4-m2970 :type MA)
           (STORY4-m2973 :type MA)
           (STORY4-m2981 :type MA)
           (STORY4-m2985 :type MA)
           (STORY4-m2987 :type MA)
           (STORY4-m2991 :type MA)
           (STORY4-m2994 :type MA)
           (STORY4-m2996 :type MA)
           (STORY4-m2998 :type MA)
           (STORY4-m3007 :type MA)
           (STORY4-m3009 :type MA)
           (STORY4-m3012 :type MA)
           (STORY4-m3015 :type MA)
           (STORY4-m3016 :type MA)
         )
         (:expressions
           ((levin-37-7 STORY4-m2956 STORY4-m2960) :name STORY4-VERB1)
           ((levin-13-1 STORY4-m2964 STORY4-m2965) :name STORY4-VERB2)
           ((levin-37-7 STORY4-m2981 STORY4-m2987) :name STORY4-VERB3)
           ((levin-47-7 STORY4-m2994 STORY4-m2996) :name STORY4-VERB4)
           ((levin-33-1 STORY4-m3009 STORY4-m3007) :name STORY4-VERB5)
         )
       )
       (phase2
         (:entities
           (STORY4-m2953 :type MA)
           (STORY4-m2954 :type MA)
           (STORY4-m2956 :type MA)
           (STORY4-m2958 :type MA)
           (STORY4-m2960 :type MA)
           (STORY4-m2963 :type MA)
           (STORY4-m2964 :type MA)
           (STORY4-m2965 :type MA)
           (STORY4-m2968 :type MA)
           (STORY4-m2970 :type MA)
           (STORY4-m2973 :type MA)
           (STORY4-m2981 :type MA)
           (STORY4-m2985 :type MA)
           (STORY4-m2987 :type MA)
           (STORY4-m2991 :type MA)
           (STORY4-m2994 :type MA)
           (STORY4-m2996 :type MA)
           (STORY4-m2998 :type MA)
           (STORY4-m3007 :type MA)
           (STORY4-m3009 :type MA)
           (STORY4-m3012 :type MA)
           (STORY4-m3015 :type MA)
           (STORY4-m3016 :type MA)
           (STORY4-m3024 :type MA)
           (STORY4-m3030 :type MA)
           (STORY4-m3031 :type MA)
           (STORY4-m3034 :type MA)
           (STORY4-m3036 :type MA)
           (STORY4-m3037 :type MA)
           (STORY4-m3039 :type MA)
           (STORY4-m3044 :type MA)
           (STORY4-m3045 :type MA)
           (STORY4-m3049 :type MA)
           (STORY4-m3051 :type MA)
           (STORY4-m3054 :type MA)
           (STORY4-m3056 :type MA)
           (STORY4-m3059 :type MA)
           (STORY4-m3060 :type MA)
           (STORY4-m3061 :type MA)
           (STORY4-m3063 :type MA)
           (STORY4-m3065 :type MA)
           (STORY4-m3067 :type MA)
           (STORY4-m3069 :type MA)
         )
         (:expressions
           ((levin-37-1 STORY4-m3024 STORY4-m3030) :name STORY4-VERB6)
           ((levin-51-1 STORY4-m3037 STORY4-m3039) :name STORY4-VERB7)
           ((levin-37-1 STORY4-m3045 STORY4-m3054) :name STORY4-VERB8)
           ((levin-09-1 STORY4-m3059 STORY4-m3060) :name STORY4-VERB9)
           ((levin-45-6 STORY4-m3063 STORY4-m3061) :name STORY4-VERB10)
         )
       )

     )
   )
)
    