
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-8
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7))
         (phase2 (:s  t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42 t43 t44 t45 t46 t47 t48 t49 t50 t51 t52 t53 t54 t55 t56 t57 t58 t59 t60 t61 t62 t63 t64 t65 t66 t67 t68 t69 t70 t71 t72 t73 t74 t75 t76))
         (phase3 (:s  t77 t78 t79 t80 t81 t82 t83 t84 t85 t86))

       )
       (:templates
         ;; There was once a king who had three daughters, and such beauties they were as no tongue can tell of nor pen describe.
         ;; Their garden was big and beautiful and they liked to walk there at night.
         ;; A dragon from the Black Sea took to visiting this garden.
         ;; One night the king's daughters tarried in the garden, for they could not tear their eyes away from the flowers; suddenly the dragon appeared and carried them off on his fiery wings.
         ;; The king waited and waited but his daughters did not come back.
         ;; He sent his maidservants to look for them in the garden, but all in vain; the maidservants could not find the princesses.
         ;; The next morning the king proclaimed a state of emergency and a great multitude of people gathered.
         ;; Three men agreed to undertake this task - a soldier who was a drunkard, Frolka Stay-at-Home, and Erema; and they set out to look for the princesses.
         ;; They walked and walked till they came to a deep forest.
         ;; As soon as they entered it they were overwhelmed by drowsiness.
         ;; Frolka Stay-at-Home drew a snuffbox out of his pocket, tapped on it, opened it, shoved a pinch of tobacco into his nose, and cried: "Eh, brothers, let us not sleep, let us not rest, let us keep going."
         ;; So they went on; they walked and walked and finally came to an enormous house, and in that house was a five-headed dragon.
         ;; For a long time they knocked at the gate, but no one answered.
         ;; Then Frolka Stay-at-Home pushed the soldier and Erema away and said: "Let me try, brothers!"
         ;; He snuffed up some tobacco and gave such a knock at the gate that he smashed it.
         ;; They entered the yard, sat in a circle, and were about to eat whatever they had.
         ;; Then a maiden of great beauty came out of the house and said: "Little doves, why have you come here?
         ;; A very wicked dragon lives here, who will devour you.
         ;; You are lucky that he happens to be away."
         ;; Frolka answered her: "It is we who shall devour him."
         ;; He had no sooner said these words than the dragon came flying and roared: "Who has ruined my kingdom?
         ;; Do I have enemies in the world?
         ;; I have only one enemy, but his bones won't even be brought here by a raven."
         ;; "A raven won't bring me," said Frolka, "but a good horse did."
         ;; The dragon upon hearing this said: "Have you come for peaceful purposes or to fight?"
         ;; "I have not come for peaceful purposes," said Frolka, "but to fight."
         ;; They moved apart, faced each other, and clashed, and in one stroke Frolka cut off all the five heads of the dragon.
         ;; Then he put them under a stone and buried the body in the ground.
         ;; The maiden was overjoyed and said to the three brave men: "My little doves, take me with you."
         ;; "But who are you?" they asked.
         ;; She said that she was the king's eldest daughter; Frolka told her what task he had undertaken, and they were both glad.
         ;; The princess invited them into the house, gave them meat and drink, and begged them to rescue her sisters.
         ;; Frolka said: "We were sent for them too!"
         ;; The princess told them where her sisters were.
         ;; "My next sister is even worse off than I was," she said.
         ;; "She is living with a seven-headed dragon."
         ;; "Never mind," said Frolka, "we shall get the better of him too; it may be somewhat harder to deal with a twelve-headed dragon."
         ;; They said farewell and went on.
         ;; Finally they came to the abode of the second sister.
         ;; The house where she was locked up was enormous and all around it there was a high iron fence.
         ;; They approached it and looked for the gate; finally they found it.
         ;; Frolka banged upon the gate with all his strength and it opened; they entered the yard and, as they had done before, sat down to eat.
         ;; Suddenly the seven-headed dragon came flying.
         ;; "I smell Russian breath here," he said.
         ;; "Bah, it is you, Frolka, who have come here!
         ;; What for?"
         ;; "I know what for," answered Frolka.
         ;; He began to fight with the dragon and in one stroke cut off all seven of his heads, put them under a stone, and buried the body in the ground.
         ;; Then they entered the house; they passed through one room, a second, and a third, and in the fourth they found the king's second daughter sitting on a sofa.
         ;; When they told her why and how they had come there, she brightened, offered them food and drink, and begged them to rescue her youngest sister from the twelve-headed dragon.
         ;; Frolka said: "Of course, that is what we were sent for.
         ;; But there is fear in my heart.
         ;; Well, perhaps God will help me!
         ;; Give us each another cup!"
         ;; They drank and left; they walked and walked till they came to a very steep ravine.
         ;; On the other side of the ravine there stood enormous pillars instead of a gate, and on the pillars were chained two ferocious lions that roared so loudly that only Frolka remained standing on his feet; his two companions fell to the ground from fear.
         ;; Frolka said to them: "I have seen worse terrors, and even then I was not frightened.
         ;; Come with me!"
         ;; And they went on.
         ;; Suddenly an old man, who looked to be about seventy, came out of the castle; he saw them, came to meet them, and said: "Whither are you going, my friends?"
         ;; "To this castle," answered Frolka.
         ;; "Ah, my friends," said the old man, "you are going to an evil place; the twelve-headed dragon lives in this castle.
         ;; He is not at home now, else he would have devoured you at once."
         ;; "But he is the very one we have come to see," said Frolka.
         ;; "If so," said the old man, "come with me, I will help you get to him."
         ;; The old man went up to the lions and began to stroke them, and Frolka with his companions got through to the courtyard.
         ;; They entered the castle; the old man brought them to the room where the princess lived.
         ;; Upon seeing them she quickly jumped off her bed and began to question them as to who they were and why they had come.
         ;; They told her.
         ;; The princess offered them food and drink and began to make ready to go.
         ;; As they were preparing to leave the house, they suddenly saw the dragon flying at a verst's distance from them.
         ;; The king's daughter rushed back into the house and Frolka and his companions went out to meet and fight the dragon.
         ;; At first the dragon attacked them with great force, but Frolka, a clever fellow, managed to defeat him, cut off all of his twelve heads, and cast them into the ravine.
         ;; Then they returned to the house and in their joy reveled even more than before.
         ;; Following this feast they set out on their way, stopping only for the other princesses.
         ;; Thus they all came back to their native land.
         ;; Frolka was generous: he brought his big three-flapped cap, the soldier brought his knapsack, and Erema brought a basket.
         ;; Frolka began to fill his cap first: he poured and poured, the cap broke, and the silver fell into the mud.
         ;; Frolka began to pour again; he poured, and the money dropped from the cap!
         ;; "There is nothing to be done," said Frolka.
         ;; "Probably all of the royal treasury will fall to me."
         ;; "And what will be left for us?" asked his companions.
         ;; "The king has enough money for you too," said Frolka.
         ;; While there was still money, Erema began to fill his basket, and the soldier his knapsack; having done this, they went home.
         ;; But Frolka remained near the royal treasury with his cap and to this very day he is still sitting there, pouring out money for himself.
         ;; When his cap is filled, I shall go on with my story, but now I am too tired.

         (t1 "There was once " (4634 "a king who had three daughters") "three daughters , and such beauties they were as no tongue can tell of nor pen describe . "
         (t2 "Their garden was big and beautiful and they liked to walk there at night . "
         (t3 "" (4640 "A dragon") "from the Black Sea took to visiting this garden . "
         (t4 "One night the " (4634 "king") "'s daughters tarried in the garden , for they could not tear their eyes away from the flowers ; suddenly " (4640 "the dragon") "appeared and carried them off on his fiery wings . "
         (t5 "" (4634 "The king") "waited and waited but his daughters did not come back . "
         (t6 "" (4634 "He") "sent his " (4646 "his maidservants") "to look for them in the garden , but all in vain ; " (4646 "the maidservants") "could not find the princesses . "
         (t7 "The next morning " (4634 "the king") "proclaimed a state of emergency and " (4649 "a great multitude of people") "gathered . "
         (t8 "Three men agreed to undertake this task - " (4654 "a soldier who was a drunkard") ", Frolka Stay-at-Home , and Erema ; and they set out to look for the princesses . "
         (t9 "They walked and walked till they came to a deep forest . "
         (t10 "As soon as they entered it they were overwhelmed by drowsiness . "
         (t11 "" (4655 "Frolka Stay-at-Home") "drew a snuffbox out of his pocket , tapped on it , opened it , shoved a pinch of tobacco into his nose , and cried : ' Eh , brothers , let us not sleep , let us not rest , let us keep going . ' "
         (t12 "So they went on ; they walked and walked and finally came to an enormous house , and in that house was " (4665 "a five-headed dragon") ". "
         (t13 "For a long time they knocked at the gate , but " (4668 "no one") "answered . "
         (t14 "Then " (4655 "Frolka Stay-at-Home") "pushed " (4654 "the soldier") "and Erema away and said : ' Let " (4655 "me") "try , brothers ! ' "
         (t15 "" (4655 "He") "snuffed up some tobacco and gave such a knock at the gate that " (4655 "he") "smashed it . "
         (t16 "They entered the yard , sat in a circle , and were about to eat whatever they had . "
         (t17 "Then " (4673 "a maiden of great beauty") "came out of the house and said : ' Little doves , why have you come here ? "
         (t18 "" (4665 "A very wicked dragon") "lives here , " (4665 "who") "will devour you . "
         (t19 "You are lucky that " (4665 "he") "happens to be away . ' "
         (t20 "" (4655 "Frolka") "answered her : ' It is we who shall devour " (4665 "him") ". ' "
         (t21 "" (4655 "He") "had no sooner said these words than " (4665 "the dragon") "came flying and roared : ' Who has ruined my kingdom ? "
         (t22 "Do " (4665 "I") "have " (4675 "enemies") "in the world ? "
         (t23 "" (4665 "I") "have only " (4655 "one enemy") ", but his bones wo n't even be brought here by a raven . ' "
         (t24 "' A raven wo n't bring " (4655 "me") ", ' said Frolka , ' but a good horse did . ' "
         (t25 "" (4665 "The dragon") "upon hearing this said : ' Have " (4655 "you") "come for peaceful purposes or to fight ? ' "
         (t26 "' " (4655 "I") "have not come for peaceful purposes , ' said " (4655 "Frolka") ", ' but to fight . ' "
         (t27 "They moved apart , faced each other , and clashed , and in one stroke " (4655 "Frolka") "cut off all the five heads of " (4665 "the dragon") ". "
         (t28 "Then " (4655 "he") "put them under a stone and buried " (4665 "the body") "in the ground . "
         (t29 "" (4673 "The maiden") "was overjoyed and said to the three brave men : ' My little doves , take " (4673 "me") "with you . ' "
         (t30 "' But who are " (4673 "you") "? ' they asked . "
         (t31 "" (4673 "She") "said that she was " (4673 "the king's eldest daughter") "" (4673 "the king's eldest daughter") "" (4673 "her") "what task " (4655 "he") "had undertaken , and they were both glad . "
         (t32 "" (4673 "The princess") "invited them into the house , gave them meat and drink , and begged them to rescue her sisters . "
         (t33 "" (4655 "Frolka") "said : ' We were sent for them too ! ' "
         (t34 "" (4673 "The princess") "told them where her sisters were . "
         (t35 "' My next sister is even worse off than " (4673 "I") "was , ' " (4673 "she") "said . "
         (t36 "' " (4694 "She") "is living with " (4695 "a seven-headed dragon") ". ' "
         (t37 "' Never mind , ' said " (4655 "Frolka") ", ' we shall get the better of " (4695 "him") "too ; it may be somewhat harder to deal with " (4696 "a twelve-headed dragon") ". ' "
         (t38 "They said farewell and went on . "
         (t39 "Finally they came to the abode of the second sister . "
         (t40 "The house where " (4694 "she") "was locked up was enormous and all around it there was a high iron fence . "
         (t41 "They approached it and looked for the gate ; finally they found it . "
         (t42 "" (4655 "Frolka") "banged upon the gate with all his strength and it opened ; they entered the yard and , as they had done before , sat down to eat . "
         (t43 "Suddenly " (4695 "the seven-headed dragon") "came flying . "
         (t44 "' " (4695 "I") "smell Russian breath here , ' " (4695 "he") "said . "
         (t45 "' Bah , it is " (4655 "you, Frolka, who have come here") "here ! "
         (t46 "What for ? ' "
         (t47 "' " (4655 "I") "know what for , ' answered " (4655 "Frolka") ". "
         (t48 "" (4655 "He") "began to fight with " (4695 "the dragon") "and in one stroke cut off all seven of his heads , put them under a stone , and buried " (4695 "the body") "in the ground . "
         (t49 "Then they entered the house ; they passed through one room , a second , and a third , and in the fourth they found the " (4634 "king") "'s second daughter sitting on a sofa . "
         (t50 "When they told " (4694 "her") "why and how they had come there , " (4694 "she") "brightened , offered them food and drink , and begged them to rescue her youngest sister from " (4716 "the twelve-headed dragon") ". "
         (t51 "" (4655 "Frolka") "said : ' Of course , that is what we were sent for . "
         (t52 "But there is fear in my heart . "
         (t53 "Well , perhaps " (4719 "God") "will help " (4655 "me") "! "
         (t54 "Give us each another cup ! ' "
         (t55 "They drank and left ; they walked and walked till they came to a very steep ravine . "
         (t56 "On the other side of the ravine there stood enormous pillars instead of a gate , and on the pillars were chained two ferocious lions that roared so loudly that " (4655 "only Frolka") "remained standing on his feet ; his two companions fell to the ground from fear . "
         (t57 "" (4655 "Frolka") "said to them : ' " (4655 "I") "have seen worse terrors , and even then " (4655 "I") "was not frightened . "
         (t58 "Come with " (4655 "me") "! ' "
         (t59 "And they went on . "
         (t60 "Suddenly " (4729 "an old man, who looked to be about seventy") "about seventy , came out of the castle ; " (4729 "he") "saw them , came to meet them , and said : ' Whither are you going , my friends ? ' "
         (t61 "' To this castle , ' answered " (4655 "Frolka") ". "
         (t62 "' Ah , my friends , ' said " (4729 "the old man") ", ' you are going to an evil place ; " (4716 "the twelve-headed dragon") "lives in this castle . "
         (t63 "" (4716 "He") "is not at home now , else " (4716 "he") "would have devoured you at once . ' "
         (t64 "' But " (4716 "he") "is " (4716 "the very one we have come to see") "" (4716 "the very one we have come to see") ""
         (t65 "' If so , ' said " (4729 "the old man") ", ' come with " (4729 "me") ", " (4729 "I") "will help you get to " (4716 "him") ". ' "
         (t66 "" (4729 "The old man") "went up to the lions and began to stroke them , and " (4655 "Frolka") "with his companions got through to the courtyard . "
         (t67 "They entered the castle ; " (4729 "the old man") "brought them to the room where " (4715 "the princess") "lived . "
         (t68 "Upon seeing them " (4715 "she") "quickly jumped off her bed and began to question them as to who they were and why they had come . "
         (t69 "They told " (4715 "her") ". "
         (t70 "" (4715 "The princess") "offered them food and drink and began to make ready to go . "
         (t71 "As they were preparing to leave the house , they suddenly saw " (4716 "the dragon") "flying at a verst 's distance from them . "
         (t72 "" (4715 "The king's daughter") "" (4715 "The king's daughter") "into the house and " (4655 "Frolka") "and his companions went out to meet and fight " (4716 "the dragon") ". "
         (t73 "At first " (4716 "the dragon") "attacked them with great force , but " (4655 "Frolka, a clever fellow") ", managed to defeat " (4716 "him") ", cut off all of his twelve heads , and cast them into the ravine . "
         (t74 "Then they returned to the house and in their joy reveled even more than before . "
         (t75 "Following this feast they set out on their way , stopping only for the other princesses . "
         (t76 "Thus they all came back to their native land . "
         (t77 "" (4655 "Frolka") "was generous : " (4655 "he") "brought his big three-flapped cap , " (4654 "the soldier") "brought his knapsack , and " (4656 "Erema") "brought a basket . "
         (t78 "" (4655 "Frolka") "began to fill his cap first : " (4655 "he") "poured and poured , the cap broke , and the silver fell into the mud . "
         (t79 "" (4655 "Frolka") "began to pour again ; " (4655 "he") "poured , and the money dropped from the cap ! "
         (t80 "' There is nothing to be done , ' said " (4655 "Frolka") ". "
         (t81 "' Probably all of the royal treasury will fall to me . ' "
         (t82 "' And what will be left for us ? ' asked his companions . "
         (t83 "' " (4634 "The king") "has enough money for you too , ' said " (4655 "Frolka") ". "
         (t84 "While there was still money , " (4656 "Erema") "began to fill his basket , and " (4654 "the soldier") "his knapsack ; having done this , they went home . "
         (t85 "But " (4655 "Frolka") "remained near the royal treasury with his cap and to this very day " (4655 "he") "is still sitting there , pouring out money for " (4655 "himself") ". "
         (t86 "When his cap is filled , " (4758 "I") "shall go on with my story , but now " (4758 "I") "am too tired . "

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)
         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m4640 :type MB)
           (m4649 :type GR)
           (m4634 :type MA)
           (m4646 :type GR)
         )
         (:expressions
         )
       )
       (phase2
         (:entities
           (m4640 :type MB)
           (m4673 :type FE)
           (m4675 :type GR)
           (m4646 :type GR)
           (m4729 :type MA)
           (m4649 :type GR)
           (m4715 :type FE)
           (m4716 :type MB)
           (m4654 :type MA)
           (m4655 :type MA)
           (m4694 :type FE)
           (m4695 :type MB)
           (m4696 :type MB)
           (m4665 :type MB)
           (m4634 :type MA)
           (m4719 :type MB)
           (m4668 :type GR)
         )
         (:expressions
         )
       )
       (phase3
         (:entities
           (m4640 :type MB)
           (m4673 :type FE)
           (m4675 :type GR)
           (m4758 :type MB)
           (m4646 :type GR)
           (m4729 :type MA)
           (m4649 :type GR)
           (m4715 :type FE)
           (m4716 :type MB)
           (m4654 :type MA)
           (m4655 :type MA)
           (m4656 :type MA)
           (m4694 :type FE)
           (m4695 :type MB)
           (m4696 :type MB)
           (m4665 :type MB)
           (m4634 :type MA)
           (m4719 :type MB)
           (m4668 :type GR)
         )
         (:expressions
         )
       )

     )
   )
)
    