
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-15
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9))

       )
       (:templates
         ;; In a certain kingdom there was a king who had three daughters of surpassing beauty.
         ;; The king guarded them more carefully than his most precious treasure; he built underground chambers and kept his daughters there like birds in a cage, so that rough winds could not blow upon them nor the red sun scorch them with his rays.
         ;; One day the princesses read in a certain book that there was a marvelous bright world, and when the king came to visit them, they straightway began to implore him with tears in their eyes, saying: "Sovereign, our father, let us out to see the bright world and walk in the green garden."
         ;; The king tried to dissuade them but to no avail.
         ;; They would not even listen to him; the more he refused, the more urgently they besought him.
         ;; There was nothing to be done, so the king granted their insistent prayer.
         ;; And so the beautiful princesses went out to walk in the garden.
         ;; They beheld the red sun, the trees, and the flowers, and were overjoyed that they had the freedom of the bright world.
         ;; They ran about in the garden and enjoyed themselves - when a sudden whirlwind seized them and carried them off far and high, no one knew whither.

         (t1 "In a certain kingdom there was " (m6140 "a king who had three daughters of surpassing beauty") " " (m6141 "three daughters of surpassing beauty") " . ")
         (t2 "" (m6140 "The king") " guarded " (m6141 "them") " more carefully than his most precious treasure ; " (E2 "" (m6140 "he") " built underground chambers and kept his daughters there like birds in a cage , so that rough winds could not blow upon them nor the red sun scorch " (m6141 "them") " " ) "with his rays . ")
         (t3 "One day the princesses read in a certain book that there was a marvelous bright world , and when " (m6140 "the king") " came to visit " (m6141 "them") " , " (E4 "" (m6141 "they") " straightway began to implore " (m6140 "him") " " ) "with tears in their eyes , saying : ' " (m6140 "Sovereign, our father") " " (m6140 "Sovereign, our father") " " (m6141 "us") " out to see the bright world and walk in the green garden . ' ")
         (t4 "" (m6140 "The king") " tried to dissuade " (m6141 "them") " but to no avail . ")
         (t5 "" (m6141 "They") " would not even listen to " (m6140 "him") " ; the more he refused , the more urgently " (m6141 "they") " besought " (m6140 "him") " . ")
         (t6 "There was nothing to be done , so the king granted their insistent prayer . ")
         (t7 "And so the beautiful princesses went out to walk in the garden . ")
         (t8 "They beheld the red sun , the trees , and the flowers , and were overjoyed that they had the freedom of the bright world . ")
         (t9 "" (m6141 "They") " ran about in the garden and enjoyed " (m6141 "themselves") " - when a sudden whirlwind seized them and carried them off far and high , no one knew whither . ")
         (t1001 (EXTRA1  (m6140 "the king") " is the " (Other "Other") ) ".")
         (t1002 (EXTRA2  (m6141 "them") " is the " (Other "Other") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m6140 :type MA)
           (m6141 :type FE)
         )
         (:expressions
           ((levin-29-8 m6140 m6141) :name E1)
           ((levin-15-2 m6140 m6141) :name E2)
           ((levin-36-3 m6140 m6141) :name E3)
           ((levin-55-1 m6141 m6140) :name E4)
           ((levin-31-1 m6140 m6141) :name E5)
           ((levin-30-3 m6141 m6140) :name E6)
           ((levin-31-2 m6141 m6141) :name E7)
           ((roleOther m6140) :name EXTRA0)
           ((roleOther m6141) :name EXTRA1)
         )
       )

     )
   )
)
    