
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-14
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22))

       )
       (:templates
         ;; There was once a very wealthy merchant who had a marvelously beautiful daughter.
         ;; This merchant carried goods to various provinces, and one day he came to a certain kingdom and brought precious cloths to the king as a gift.
         ;; The king said to him: "Why can I not find a bride for myself?"
         ;; The merchant answered: "I have a beautiful daughter, and she is so clever that no matter what a man is thinking, she can guess it."
         ;; The king immediately wrote a letter and called his guards.
         ;; "Go to that merchant's house," he told them, "and deliver this letter to the merchant's daughter."
         ;; The letter said: "Make ready to get married."
         ;; The merchant's daughter took the letter, burst into tears, and prepared to go, taking also her maidservant; and no one could distinguish this maid from the merchant's daughter, they were so like each other.
         ;; They dressed in dresses that were alike and went to the king for the marriage.
         ;; The maid was full of spite, and said: "Let us take a walk on the island."
         ;; They went to the island; there the maidservant gave the merchant's daughter sleeping potions, cut out her eyes, and put them in her pocket.
         ;; Then she came to the guards and said: "Gentlemen of the guard, my maid servant has gone to sea."
         ;; They answered: "We need only you, we have no use for that peasant girl."
         ;; They went to the king; he married the maid at once, and they began to live together.
         ;; The king thought to himself: "The merchant must have cheated me; she cannot be a merchant's daughter.
         ;; Why is she so ignorant?
         ;; She does not know how to do anything."
         ;; Meanwhile the merchant's daughter recovered from the illness that her maid had brought upon her.
         ;; She could not see; she could only hear and she heard an old man tending cattle.
         ;; She said to him: "Where are you, grandfather?"
         ;; "I live in a little hut."
         ;; "Please take me into your hut."

         (t1 "There was once " (5848 "a very wealthy merchant who had a marvelously beautiful daughter") "" (5849 "a marvelously beautiful daughter") ". "
         (t2 "" (5848 "This merchant") "carried goods to various provinces , and one day " (5848 "he") "came to a certain kingdom and brought precious cloths to " (5855 "the king") "as a gift . "
         (t3 "" (5855 "The king") "said to " (5848 "him") ": ' Why can " (5855 "I") "not find a bride for " (5855 "myself") "? ' "
         (t4 "" (5848 "The merchant") "answered : ' " (5848 "I") "have " (5849 "a beautiful daughter") ", and she is so clever that no matter what a man is thinking , " (5849 "she") "can guess it . ' "
         (t5 "" (5855 "The king") "immediately wrote a letter and called his " (5859 "his guards") ". "
         (t6 "' Go to that merchant 's house , ' " (5855 "he") "told them , ' and deliver this letter to " (5849 "the merchant's daughter") "" (5849 "the merchant's daughter") ""
         (t7 "The letter said : ' Make ready to get married . ' "
         (t8 "" (5849 "The merchant's daughter") "" (5849 "The merchant's daughter") "letter , burst into tears , and prepared to go , taking also her " (5862 "her maidservant") "; and no one could distinguish this maid from " (5849 "the merchant's daughter") "" (5849 "the merchant's daughter") "were so like each other . "
         (t9 "They dressed in dresses that were alike and went to the king for the marriage . "
         (t10 "" (5862 "The maid") "was full of spite , and said : ' Let us take a walk on the island . ' "
         (t11 "They went to the island ; there " (5862 "the maidservant") "gave the " (5848 "merchant") "'s daughter sleeping potions , cut out her eyes , and put them in her pocket . "
         (t12 "Then " (5862 "she") "came to the guards and said : ' Gentlemen of the guard , my " (5849 "my maid servant") "has gone to sea . ' "
         (t13 "" (5859 "They") "answered : ' " (5859 "We") "need only " (5862 "you") ", " (5859 "we") "have no use for " (5849 "that peasant girl") ". ' "
         (t14 "They went to the king ; he married " (5862 "the maid") "at once , and they began to live together . "
         (t15 "" (5855 "The king") "thought to " (5855 "himself") ": ' " (5848 "The merchant") "must have cheated " (5855 "me") "; " (5862 "she") "can not be a merchant 's daughter . "
         (t16 "Why is " (5862 "she") "so ignorant ? "
         (t17 "" (5862 "She") "does not know how to do anything . ' "
         (t18 "Meanwhile the " (5848 "merchant") "'s daughter recovered from the illness that her " (5862 "her maid") "had brought upon " (5849 "her") ". "
         (t19 "" (5849 "She") "could not see ; " (5849 "she") "could only hear and " (5849 "she") "heard " (5876 "an old man tending cattle") "cattle . "
         (t20 "" (5849 "She") "said to him : ' Where are " (5876 "you, grandfather") "? ' "
         (t21 "' " (5876 "I") "live in a little hut . ' "
         (t22 "' Please take " (5849 "me") "into your hut . ' "

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)
         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m5859 :type GR)
           (m5862 :type FE)
           (m5876 :type MA)
           (m5848 :type MA)
           (m5849 :type FE)
           (m5855 :type MA)
         )
         (:expressions
         )
       )

     )
   )
)
    