
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-13
     (:discourse
       (:clauses
         (c0 (:s phase1))
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18))

       )
       (:templates
         ;; There was once an old princess; she had a son and a daughter, both well built, both handsome.
         ;; A wicked witch disliked them; she pondered and pondered as to how she could lead them into evil ways and destroy them.
         ;; In the end she conceived a plan.
         ;; Like a cunning fox she came to their mother and said: "My little dove, my dear friend, here is a ring for you; put it on your son's finger.
         ;; With its help he will be healthy and wealthy, but he must never take it off, and he must marry only that maiden whom the ring fits."
         ;; The old woman believed her and was overjoyed; before her death she enjoined upon her son that he take to wife a woman whom the ring would be found to fit.
         ;; Time went by and the little son grew up.
         ;; He grew up and began to seek a bride; he would like one girl, then another, but upon trying the ring he always found it to be too big or too small; it did not fit either the one or the other.
         ;; He traveled and traveled through villages and cities, tried the ring on all the lovely maidens, but could not find one whom he could take as his betrothed; he returned home and was pensive and sad.
         ;; "Little brother, why are you grieving?" his sister asked him.
         ;; He told her his trouble.
         ;; "Why is the ring so troublesome?" said the sister.
         ;; "Let me try it."
         ;; She put it on her finger and the ring clasped it, and began to gleam; it fitted her as though made to her size.
         ;; "Ah, my sister," said the brother, "you have been chosen for me by fate, you shall be my wife."
         ;; "What are you saying, my brother?
         ;; Think of God, think of the sin; one does not marry one's own sister."
         ;; But her brother did not heed her; he danced for joy and ordered that preparations be made for the wedding.

         (t1 "There was once " (STORY13-m5346 "an old princess") " ; " (STORY13-m5347 "she") " had a son and " (STORY13-m5350 "a daughter") " , both well built , both handsome . ")
         (t2 "" (STORY13-m5351 "A wicked witch") " disliked " (STORY13-m5352 "them") " ; " (STORY13-m5353 "she") " pondered and pondered as to how " (STORY13-VERB2 "" (STORY13-m5354 "she") " could lead " (STORY13-m5355 "them") " " ) "into evil ways and destroy " (STORY13-m5356 "them") " . ")
         (t3 "In the end " (STORY13-m5357 "she") " conceived a plan . ")
         (t4 "Like a cunning fox " (STORY13-m5359 "she") " came to their mother and said : ' My " (STORY13-m5363 "My little dove") " , my dear friend , here is a ring for " (STORY13-m5367 "you") " ; put it on your " (STORY13-m5370 "your son") " 's finger . ")
         (t5 "With its help " (STORY13-m5374 "he") " will be healthy and wealthy , but " (STORY13-m5375 "he") " must never take it off , and " (STORY13-m5377 "he") " must marry only " (STORY13-m5378 "that maiden whom the ring fits") " . ' ")
         (t6 "" (STORY13-m5380 "The old woman") " believed her and was overjoyed ; before her death " (STORY13-m5383 "she") " enjoined upon her " (STORY13-m5385 "her son") " that " (STORY13-m5386 "he") " take to wife " (STORY13-m5387 "a woman whom the ring would be found to fit") " . ")
         (t7 "Time went by and " (STORY13-m5390 "the little son") " grew up . ")
         (t8 "" (STORY13-m5391 "He") " grew up and began to seek " (STORY13-m5392 "a bride") " ; " (STORY13-m5393 "he") " would like " (STORY13-m5394 "one girl") " , then another , but upon trying the ring " (STORY13-m5397 "he") " always found it to be too big or too small ; it did not fit either " (STORY13-m5400 "the one") " or the other . ")
         (t9 "" (STORY13-m5403 "He") " " (STORY13-m5404 "He traveled and traveled through villages and cities, tried the ring on all the lovely maidens, but could not find one whom he could take as his betrothed") " " (STORY13-m5410 "one whom he could take as his betrothed") " his betrothed ; " (STORY13-m5414 "he") " returned home and was pensive and sad . ")
         (t10 "' " (STORY13-m5416 "Little brother") " , why are " (STORY13-m5417 "you") " grieving ? ' his " (STORY13-m5419 "his sister") " asked him . ")
         (t11 "" (STORY13-m5421 "He") " told " (STORY13-m5422 "her") " his trouble . ")
         (t12 "' Why is the ring so troublesome ? ' said " (STORY13-m5426 "the sister") " . ")
         (t13 "' Let " (STORY13-m5427 "me") " try it . ' ")
         (t14 "" (STORY13-m5429 "She") " put it on her finger and the ring clasped it , and began to gleam ; it fitted " (STORY13-m5436 "her") " as though made to her size . ")
         (t15 "' Ah , my " (STORY13-m5440 "my sister") " , ' said " (STORY13-m5441 "the brother") " , ' " (STORY13-m5442 "you") " have been chosen for me by " (STORY13-m5444 "fate") " , " (STORY13-m5445 "you") " shall be my wife . ' ")
         (t16 "' What are " (STORY13-m5448 "you") " saying , my " (STORY13-m5450 "my brother") " ? ")
         (t17 "Think of God , think of the sin ; one does not marry one 's own sister . ' ")
         (t18 "But her " (STORY13-m5454 "her brother") " did not heed her ; " (STORY13-m5456 "he") " danced for joy and ordered that preparations be made for the wedding . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY13-m5377 :type MA)
           (STORY13-m5378 :type MA)
           (STORY13-m5380 :type MA)
           (STORY13-m5383 :type MA)
           (STORY13-m5385 :type MA)
           (STORY13-m5386 :type MA)
           (STORY13-m5387 :type MA)
           (STORY13-m5390 :type MA)
           (STORY13-m5391 :type MA)
           (STORY13-m5392 :type MA)
           (STORY13-m5393 :type MA)
           (STORY13-m5394 :type MA)
           (STORY13-m5397 :type MA)
           (STORY13-m5400 :type MA)
           (STORY13-m5403 :type MA)
           (STORY13-m5404 :type MA)
           (STORY13-m5409 :type MA)
           (STORY13-m5410 :type MA)
           (STORY13-m5411 :type MA)
           (STORY13-m5414 :type MA)
           (STORY13-m5416 :type MA)
           (STORY13-m5417 :type MA)
           (STORY13-m5419 :type MA)
           (STORY13-m5421 :type MA)
           (STORY13-m5422 :type MA)
           (STORY13-m5426 :type MA)
           (STORY13-m5427 :type MA)
           (STORY13-m5429 :type MA)
           (STORY13-m5436 :type MA)
           (STORY13-m5440 :type MA)
           (STORY13-m5441 :type MA)
           (STORY13-m5442 :type MA)
           (STORY13-m5444 :type MA)
           (STORY13-m5445 :type MA)
           (STORY13-m5448 :type MA)
           (STORY13-m5450 :type MA)
           (STORY13-m5454 :type MA)
           (STORY13-m5456 :type MA)
           (STORY13-m5346 :type MA)
           (STORY13-m5347 :type MA)
           (STORY13-m5350 :type MA)
           (STORY13-m5351 :type MA)
           (STORY13-m5352 :type MA)
           (STORY13-m5353 :type MA)
           (STORY13-m5354 :type MA)
           (STORY13-m5355 :type MA)
           (STORY13-m5356 :type MA)
           (STORY13-m5357 :type MA)
           (STORY13-m5359 :type MA)
           (STORY13-m5363 :type MA)
           (STORY13-m5367 :type MA)
           (STORY13-m5370 :type MA)
           (STORY13-m5374 :type MA)
           (STORY13-m5375 :type MA)
         )
         (:expressions
           ((levin-31-2 STORY13-m5351 STORY13-m5352) :name STORY13-VERB1)
           ((levin-51-7 STORY13-m5354 STORY13-m5355) :name STORY13-VERB2)
           ((levin-37-7 STORY13-m5359 STORY13-m5363) :name STORY13-VERB3)
           ((levin-36-2 STORY13-m5377 STORY13-m5378) :name STORY13-VERB4)
           ((levin-29-4 STORY13-m5386 STORY13-m5387) :name STORY13-VERB5)
           ((levin-55-1 STORY13-m5391 STORY13-m5392) :name STORY13-VERB6)
           ((levin-31-2 STORY13-m5393 STORY13-m5394) :name STORY13-VERB7)
           ((levin-51-3-2 STORY13-m5403 STORY13-m5404) :name STORY13-VERB8)
           ((levin-11-3 STORY13-m5411 STORY13-m5410) :name STORY13-VERB9)
           ((levin-31-3 STORY13-m5417 STORY13-m5416) :name STORY13-VERB10)
           ((levin-37-2 STORY13-m5421 STORY13-m5422) :name STORY13-VERB11)
           ((levin-37-7 STORY13-m5441 STORY13-m5440) :name STORY13-VERB12)
           ((levin-13-5-1 STORY13-m5444 STORY13-m5442) :name STORY13-VERB13)
           ((levin-37-7 STORY13-m5448 STORY13-m5450) :name STORY13-VERB14)
         )
       )

     )
   )
)
    