
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-11
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4 t5 t6))
         (phase2 (:s  t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42 t43 t44))
         (phase3 (:s  t45 t46 t47 t48 t49 t50 t51 t52 t53 t54 t55 t56 t57 t58 t59 t60 t61 t62 t63 t64 t65 t66 t67 t68 t69 t70 t71 t72 t73 t74 t75))

       )
       (:templates
         ;; Once upon a time there was an old couple, and they had three Sons.
         ;; Two of these had their wits about them, but the third was a simpleton, Ivan by name, surnamed Popyalof.
         ;; For twelve whole years Ivan lay among the ashes from the stove; but then he arose, and shook himself, so that six poods of ashes fell off from him.
         ;; Now in the land in which Ivan lived there was never any day, but always night.
         ;; That was a Snake's doing.
         ;; Well, Ivan undertook to kill that Snake, so he said to his father, "Father make me a mace five poods in weight."
         ;; The next day he went out into the fields to the spot from which he had flung the mace on high, and stood there with his head thrown back.
         ;; So when the mace fell down again it hit him on the forehead.
         ;; And the mace broke in two.
         ;; Ivan went home and said to his father, "Father, make me another mace, a ten pood one."
         ;; And when he had got it he went out into the fields, and flung it aloft.
         ;; And the mace went flying through the air for three days and three nights.
         ;; On the fourth day Ivan went out to the same spot, and when the mace came tumbling down, he put his knee in the way, and the mace broke over it into three pieces.
         ;; Ivan went home and told his father to make him a third mace, one of fifteen poods weight.
         ;; And when he had got it, he went out into the fields and flung it aloft.
         ;; And the mace was up in the air six days.
         ;; On the seventh Ivan went to the same spot as before.
         ;; Down fell the mace, and when it struck Ivan's forehead, the forehead bowed under it.
         ;; Thereupon he said, "This mace will do for the Snake!"
         ;; So when he had got everything ready, he went forth with his brothers to fight the Snake.
         ;; He rode and rode, and presently there stood before him a hut on fowl's legs, and in that hut lived the Snake.
         ;; There all the party came to a standstill.
         ;; Then Ivan hung up his gloves, and said to his brothers, "Should blood drop from my gloves, make haste to help me."
         ;; When he had said this he went into the hut and sat down under the boarding.
         ;; Presently there rode up a Snake with three heads.
         ;; His steed stumbled, his hound howled, his falcon clamored.
         ;; Then cried the Snake: "Wherefore hast thou stumbled, O Steed! hast thou howled, O Hound! hast thou clamored, O Falcon?"
         ;; "How can I but stumble," replied the Steed, "when under the boarding sits Ivan Popyalof?"
         ;; Then said the Snake, "Come forth, Ivanushka!
         ;; Let us try our strength together."
         ;; Ivan came forth, and they began to fight.
         ;; And Ivan killed the Snake, and then sat down again beneath the boarding.
         ;; Presently there came another Snake, a six-headed one, and him, too, Ivan killed.
         ;; And then there came a third, which had twelve heads.
         ;; Well, Ivan began to fight with him, and lopped off nine of his heads.
         ;; The Snake had no strength left in him.
         ;; Just then a raven came flying by, and it croaked: "Krof? Krof!"
         ;; Then the Snake cried to the Raven, "Fly, and tell my wife to come and devour Ivan Popyalof."
         ;; But Ivan cried: "Fly, and tell my brothers to come, and then we will kill this Snake, and give his flesh to thee."
         ;; And the Raven gave ear to what Ivan said, and flew to his brothers and began to croak above their heads.
         ;; The brothers awoke, and when they heard the cry of the Raven, they hastened to their brother's aid.
         ;; And they killed the Snake, and then, having taken his heads, they went into his hut and destroyed them.
         ;; And immediately there was bright light throughout the whole land.
         ;; After killing the Snake, Ivan Popyalof and his brothers set off on their way home.
         ;; Now when he had reached the hut and was going to take away his gloves, he heard the voices of the Snake's wife and daughters, who were talking with each other.
         ;; So he turned himself into a cat, and began to mew outside the door.
         ;; They let him in, and he listened to everything they said.
         ;; Then he got his gloves and hastened away.
         ;; As soon as he came to where his brothers were, he mounted his horse, and they all started afresh.
         ;; They rode and rode; presently they saw before them a green meadow, and on that meadow lay silken cushions.
         ;; Then the elder brothers said, "Let's turn out our horses to graze here, while we rest ourselves a little."
         ;; But Ivan said, "Wait a minute, brothers!" and he seized his mace, and struck the cushions with it.
         ;; And out of those cushions there streamed blood.
         ;; So they all went on further.
         ;; They rode and rode; presently there stood before them an apple-tree, and upon it were gold and silver apples.
         ;; Then the elder brothers said. "Let's eat an apple apiece."
         ;; But Ivan said, "Wait a minute, brothers; I'll try them first," and he took his  mace, and struck the apple-tree with it.
         ;; And out of the tree streamed blood.
         ;; So they went on further.
         ;; They rode and rode, and by and by they saw a spring in front of them.
         ;; And the elder brothers cried, "Let's have a drink of water."
         ;; But Ivan Popyalof cried: "Stop, brothers!" and he raised his mace and struck the spring, and its waters became blood.
         ;; For the meadow, the silken cushions, the apple-tree, and the spring, were all of them daughters of the Snake.
         ;; After killing the Snake's daughters, Ivan and his brothers went on homewards.
         ;; Presently came the Snake's Wife flying after them, and she opened her jaws from the sky to the earth, and tried to swallow up Ivan.
         ;; But Ivan and his brothers threw three poods of salt into her mouth.
         ;; She swallowed the salt, thinking it was Ivan Popyalof, but afterwards - when she had tasted the salt, and found out it was not Ivan - she flew after him again.
         ;; Then he perceived that danger was at hand, and so he let his horse go free, and hid himself behind twelve doors in the forge of Kuzma and Demian.
         ;; The Snake's Wife came flying up, and said to Kuzma and Demian, "Give me up Ivan Popyalof."
         ;; But they replied:"Send your tongue through the twelve doors and take him."
         ;; So the Snake's Wife began licking the doors.
         ;; But meanwhile they all heated iron pincers, and as soon as she had sent her tongue through into the smithy, they caught tight hold of her by the tongue, and began thumping her with hammers.
         ;; And when the Snake's Wife was dead they consumed her with fire, and scattered her ashes to the winds.
         ;; And then they went home, and there they lived and enjoyed themselves, feasting and revelling, and drinking mead and wine.
         ;; I was there, too, and had liquor to drink; it didn't go into my mouth, but only ran down my beard.

         (t1 "Once upon a time there was an old couple , and they had three Sons . "
         (t2 "Two of these had their wits about them , but " (4097 "the third") "was a simpleton , Ivan by name , surnamed Popyalof . "
         (t3 "For twelve whole years " (4097 "Ivan") "lay among the ashes from the stove ; but then " (4097 "he") "arose , and shook " (4097 "himself") ", so that six poods of ashes fell off from " (4097 "him") ". "
         (t4 "Now in the land in which " (4097 "Ivan") "lived there was never any day , but always night . "
         (t5 "That was a " (4107 "Snake") "'s doing . "
         (t6 "Well , " (4097 "Ivan") "undertook to kill " (4107 "that Snake") ", so " (4097 "he") "said to his father , ' " (4108 "Father") "make " (4097 "me") "a mace five poods in weight . ' "
         (t7 "The next day " (4097 "he") "went out into the fields to the spot from which " (4097 "he") "had flung the mace on high , and stood there with his head thrown back . "
         (t8 "So when the mace fell down again it hit " (4097 "him") "on the forehead . "
         (t9 "And the mace broke in two . "
         (t10 "" (4097 "Ivan") "went home and said to his father , ' " (4108 "Father") ", make " (4097 "me") "another mace , a ten pood one . ' "
         (t11 "And when " (4097 "he") "had got it " (4097 "he") "went out into the fields , and flung it aloft . "
         (t12 "And the mace went flying through the air for three days and three nights . "
         (t13 "On the fourth day " (4097 "Ivan") "went out to the same spot , and when the mace came tumbling down , " (4097 "he") "put his knee in the way , and the mace broke over it into three pieces . "
         (t14 "" (4097 "Ivan") "went home and told his " (4108 "his father") "to make " (4097 "him") "a third mace , one of fifteen poods weight . "
         (t15 "And when " (4097 "he") "had got it , " (4097 "he") "went out into the fields and flung it aloft . "
         (t16 "And the mace was up in the air six days . "
         (t17 "On the seventh " (4097 "Ivan") "went to the same spot as before . "
         (t18 "Down fell the mace , and when it struck " (4097 "Ivan") "'s forehead , the forehead bowed under it . "
         (t19 "Thereupon " (4097 "he") "said , ' This mace will do for " (4107 "the Snake") "! ' "
         (t20 "So when " (4097 "he") "had got everything ready , " (4097 "he") "went forth with his brothers to fight " (4107 "the Snake") ". "
         (t21 "" (4097 "He") "rode and rode , and presently there stood before " (4097 "him") "a hut on fowl 's legs , and in that hut lived " (4107 "the Snake") ". "
         (t22 "There all the party came to a standstill . "
         (t23 "Then " (4097 "Ivan") "hung up his gloves , and said to his brothers , ' Should blood drop from my gloves , make haste to help " (4097 "me") ". ' "
         (t24 "When " (4097 "he") "had said this " (4097 "he") "went into the hut and sat down under the boarding . "
         (t25 "Presently there rode up " (4138 "a Snake with three heads") "three heads . "
         (t26 "His steed stumbled , his hound howled , his falcon clamored . "
         (t27 "Then cried " (4138 "the Snake") ": ' Wherefore hast thou stumbled , O Steed ! hast thou howled , O Hound ! hast thou clamored , O Falcon ? ' "
         (t28 "' How can I but stumble , ' replied the Steed , ' when under the boarding sits " (4097 "Ivan Popyalof") "? ' "
         (t29 "Then said " (4138 "the Snake") ", ' Come forth , " (4097 "Ivanushka") "! "
         (t30 "Let us try our strength together . ' "
         (t31 "" (4097 "Ivan") "came forth , and they began to fight . "
         (t32 "And " (4097 "Ivan") "killed " (4138 "the Snake") ", and then sat down again beneath the boarding . "
         (t33 "Presently there came " (4145 "another Snake, a six-headed one") ", and " (4145 "him") ", too , " (4097 "Ivan") "killed . "
         (t34 "And then there came " (4107 "a third, which had twelve heads") "twelve heads . "
         (t35 "Well , " (4097 "Ivan") "began to fight with " (4107 "him") ", and lopped off nine of his heads . "
         (t36 "" (4107 "The Snake") "had no strength left in " (4107 "him") ". "
         (t37 "Just then " (4149 "a raven") "came flying by , and " (4149 "it") "croaked : ' Krof ? Krof ! ' "
         (t38 "Then " (4107 "the Snake") "cried to " (4149 "the Raven") ", ' Fly , and tell my " (4150 "my wife") "to come and devour " (4097 "Ivan Popyalof") ". ' "
         (t39 "But " (4097 "Ivan") "cried : ' Fly , and tell my brothers to come , and then we will kill " (4107 "this Snake") ", and give his flesh to " (4149 "thee") ". ' "
         (t40 "And " (4149 "the Raven") "gave ear to what " (4097 "Ivan") "said , and flew to his brothers and began to croak above their heads . "
         (t41 "The brothers awoke , and when they heard the cry of " (4149 "the Raven") ", they hastened to their brother 's aid . "
         (t42 "And they killed " (4107 "the Snake") ", and then , having taken his heads , they went into his hut and destroyed them . "
         (t43 "And immediately there was bright light throughout the whole land . "
         (t44 "After killing " (4107 "the Snake") ", " (4097 "Ivan Popyalof") "and his brothers set off on their way home . "
         (t45 "Now when " (4097 "he") "had reached the hut and was going to take away his gloves , " (4097 "he") "heard the voices of the " (4107 "Snake") "'s wife and daughters , who were talking with each other . "
         (t46 "So " (4097 "he") "turned " (4097 "himself") "into a cat , and began to mew outside the door . "
         (t47 "They let " (4097 "him") "in , and " (4097 "he") "listened to everything they said . "
         (t48 "Then " (4097 "he") "got his gloves and hastened away . "
         (t49 "As soon as " (4097 "he") "came to where his brothers were , " (4097 "he") "mounted his horse , and they all started afresh . "
         (t50 "They rode and rode ; presently they saw before them a green meadow , and on that meadow lay silken cushions . "
         (t51 "Then the elder brothers said , ' Let 's turn out our horses to graze here , while we rest ourselves a little . ' "
         (t52 "But " (4097 "Ivan") "said , ' Wait a minute , brothers ! ' and " (4097 "he") "seized his mace , and struck the cushions with it . "
         (t53 "And out of those cushions there streamed blood . "
         (t54 "So they all went on further . "
         (t55 "They rode and rode ; presently there stood before them an apple-tree , and upon it were gold and silver apples . "
         (t56 "Then the elder brothers said . ' Let 's eat an apple apiece . ' "
         (t57 "But " (4097 "Ivan") "said , ' Wait a minute , brothers ; " (4097 "I") "'ll try them first , ' and " (4097 "he") "took his mace , and struck the apple - tree with it . "
         (t58 "And out of the tree streamed blood . "
         (t59 "So they went on further . "
         (t60 "They rode and rode , and by and by they saw a spring in front of them . "
         (t61 "And the elder brothers cried , ' Let 's have a drink of water . ' "
         (t62 "But " (4097 "Ivan Popyalof") "cried : ' Stop , brothers ! ' and " (4097 "he") "raised his mace and struck the spring , and its waters became blood . "
         (t63 "For the meadow " (4160 "the meadow, the silken cushions, the apple-tree, and the spring") "" (4160 "the meadow, the silken cushions, the apple-tree, and the spring") "" (4160 "the meadow, the silken cushions, the apple-tree, and the spring") "were all of them daughters of the Snake . "
         (t64 "After killing " (4160 "the Snake's daughters") "" (4160 "the Snake's daughters") "and his brothers went on homewards . "
         (t65 "Presently came " (4150 "the Snake's Wife") "" (4150 "the Snake's Wife") "them , and " (4150 "she") "opened her jaws from the sky to the earth , and tried to swallow up " (4097 "Ivan") ". "
         (t66 "But " (4097 "Ivan") "and his brothers threw three poods of salt into her mouth . "
         (t67 "" (4150 "She") "swallowed the salt , thinking it was " (4097 "Ivan Popyalof") ", but afterwards - when " (4150 "she") "had tasted the salt , and found out it was not " (4097 "Ivan") "- she flew after him again . "
         (t68 "Then " (4097 "he") "perceived that danger was at hand , and so " (4097 "he") "let his " (4164 "his horse") "go free , and hid " (4097 "himself") "behind twelve doors in the forge of Kuzma and Demian . "
         (t69 "The " (4107 "Snake") "'s Wife came flying up , and said to " (4189 "Kuzma") "and " (4191 "Demian") ", ' Give me up " (4097 "Ivan Popyalof") ". ' "
         (t70 "But they replied : ' Send your tongue through the twelve doors and take " (4097 "him") ". ' "
         (t71 "So the " (4107 "Snake") "'s Wife began licking the doors . "
         (t72 "But meanwhile they all heated iron pincers , and as soon as " (4150 "she") "had sent her tongue through into the smithy , they caught tight hold of her by the tongue , and began thumping her with hammers . "
         (t73 "And when " (4150 "the Snake's Wife") "" (4150 "the Snake's Wife") "they consumed " (4150 "her") "with fire , and scattered her ashes to the winds . "
         (t74 "And then they went home , and there they lived and enjoyed themselves , feasting and revelling , and drinking mead and wine . "
         (t75 "" (4203 "I") "was there , too , and had liquor to drink ; it did n't go into my mouth , but only ran down my beard . "

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)
         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m4097 :type MA)
           (m4107 :type MB)
           (m4108 :type MA)
         )
         (:expressions
           ((verb-was m-1 m4097) :name E1)
           ((verb-surnamed m-1 m4097) :name E2)
           ((verb-lay m-1 m4097) :name E3)
           ((verb-arose m-1 m4097) :name E4)
           ((verb-shook m4097 m4097) :name E5)
           ((verb-fell m-1 m4097) :name E6)
           ((verb-lived m4097 m-1) :name E7)
           ((verb-was m-1 m4097) :name E8)
           ((verb-was m-1 m4097) :name E9)
           ((verb-was m-1 m4107) :name E10)
           ((verb-undertook m4097 m4107) :name E11)
           ((verb-kill m4097 m4107) :name E12)
           ((verb-said m4097 m4097) :name E13)
           ((verb-make m4108 m4097) :name E14)
         )
       )
       (phase2
         (:entities
           (m4097 :type MA)
           (m4138 :type MB)
           (m4107 :type MB)
           (m4108 :type MA)
           (m4145 :type MB)
           (m4149 :type AA)
           (m4150 :type MB)
         )
         (:expressions
           ((verb-went m4097 m-1) :name E15)
           ((verb-stood m-1 m4097) :name E16)
           ((verb-flung m4097 m-1) :name E17)
           ((verb-hit m-1 m4097) :name E18)
           ((verb-went m4097 m-1) :name E19)
           ((verb-said m4097 m4097) :name E20)
           ((verb-make m4108 m4097) :name E21)
           ((verb-got m4097 m-1) :name E22)
           ((verb-went m4097 m4097) :name E23)
           ((verb-flung m4097 m-1) :name E24)
           ((verb-went m4097 m-1) :name E25)
           ((verb-put m4097 m-1) :name E26)
           ((verb-went m4097 m-1) :name E27)
           ((verb-told m4097 m4097) :name E28)
           ((verb-make m4108 m4097) :name E29)
           ((verb-got m4097 m-1) :name E30)
           ((verb-went m4097 m4097) :name E31)
           ((verb-flung m4097 m-1) :name E32)
           ((verb-went m4097 m-1) :name E33)
           ((verb-struck m-1 m4097) :name E34)
           ((verb-bowed m-1 m4097) :name E35)
           ((verb-said m4097 m4107) :name E36)
           ((verb-do m-1 m4107) :name E37)
           ((verb-got m4097 m-1) :name E38)
           ((verb-went m4097 m4107) :name E39)
           ((verb-fight m4097 m4107) :name E40)
           ((verb-rode m4097 m-1) :name E41)
           ((verb-rode m4097 m-1) :name E42)
           ((verb-stood m-1 m4097) :name E43)
           ((verb-lived m4107 m-1) :name E44)
           ((verb-hung m4097 m-1) :name E45)
           ((verb-said m4097 m4097) :name E46)
           ((verb-make m-1 m4097) :name E47)
           ((verb-help m-1 m4097) :name E48)
           ((verb-said m4097 m-1) :name E49)
           ((verb-went m4097 m4097) :name E50)
           ((verb-sat m-1 m4097) :name E51)
           ((verb-rode m4138 m-1) :name E52)
           ((verb-cried m4138 m-1) :name E53)
           ((verb-replied m-1 m4097) :name E54)
           ((verb-sits m-1 m4097) :name E55)
           ((verb-said m4138 m4097) :name E56)
           ((verb-Come m-1 m4097) :name E57)
           ((verb-came m-1 m4097) :name E58)
           ((verb-killed m4097 m4138) :name E59)
           ((verb-sat m-1 m4097) :name E60)
           ((verb-came m-1 m4145) :name E61)
           ((verb-killed m4097 m4145) :name E62)
           ((verb-came m-1 m4107) :name E63)
           ((verb-had m4107 m-1) :name E64)
           ((verb-began m4097 m4107) :name E65)
           ((verb-fight m4097 m4107) :name E66)
           ((verb-lopped m4097 m-1) :name E67)
           ((verb-had m4107 m4107) :name E68)
           ((verb-left m-1 m4107) :name E69)
           ((verb-came m-1 m4149) :name E70)
           ((verb-flying m-1 m4149) :name E71)
           ((verb-croaked m4149 m-1) :name E72)
           ((verb-cried m4107 m4149) :name E73)
           ((verb-Fly m-1 m4149) :name E74)
           ((verb-tell m4149 m4150) :name E75)
           ((verb-come m-1 m4150) :name E76)
           ((verb-devor m4150 m4097) :name E77)
           ((verb-cried m4097 m4107) :name E78)
           ((verb-kill m-1 m4107) :name E79)
           ((verb-give m-1 m4149) :name E80)
           ((verb-gave m4149 m4097) :name E81)
           ((verb-said m4097 m4149) :name E82)
           ((verb-flew m-1 m4149) :name E83)
           ((verb-began m4149 m-1) :name E84)
           ((verb-croak m4149 m-1) :name E85)
           ((verb-heard m-1 m4149) :name E86)
           ((verb-hastened m-1 m4149) :name E87)
           ((verb-killed m-1 m4107) :name E88)
           ((verb-set m4097 m4107) :name E89)
           ((verb-killing m4097 m4107) :name E90)
         )
       )
       (phase3
         (:entities
           (m4160 :type MB)
           (m4097 :type MA)
           (m4203 :type MB)
           (m4164 :type AA)
           (m4138 :type MB)
           (m4107 :type MB)
           (m4108 :type MA)
           (m4145 :type MB)
           (m4149 :type AA)
           (m4150 :type MB)
           (m4189 :type MA)
           (m4191 :type MA)
         )
         (:expressions
           ((verb-reached m4097 m-1) :name E91)
           ((verb-take m4097 m-1) :name E92)
           ((verb-heard m4097 m4107) :name E93)
           ((verb-turned m4097 m4097) :name E94)
           ((verb-began m4097 m-1) :name E95)
           ((verb-mew m4097 m-1) :name E96)
           ((verb-let m-1 m4097) :name E97)
           ((verb-listened m4097 m-1) :name E98)
           ((verb-got m4097 m-1) :name E99)
           ((verb-hastened m4097 m-1) :name E100)
           ((verb-mounted m4097 m4097) :name E101)
           ((verb-came m-1 m4097) :name E102)
           ((verb-said m4097 m-1) :name E103)
           ((verb-seized m4097 m-1) :name E104)
           ((verb-struck m4097 m-1) :name E105)
           ((verb-said m4097 m4097) :name E106)
           ((verb-took m4097 m4097) :name E107)
           ((verb-struck m4097 m-1) :name E108)
           ((verb-Wait m-1 m4097) :name E109)
           ((verb-try m4097 m-1) :name E110)
           ((verb-cried m4097 m-1) :name E111)
           ((verb-raised m4097 m-1) :name E112)
           ((verb-struck m4097 m-1) :name E113)
           ((verb-were m-1 m4160) :name E114)
           ((verb-went m4097 m4160) :name E115)
           ((verb-killing m4097 m4107) :name E116)
           ((verb-came m-1 m4150) :name E117)
           ((verb-flying m-1 m4150) :name E118)
           ((verb-opened m4150 m-1) :name E119)
           ((verb-swallow m4150 m4097) :name E120)
           ((verb-tried m4150 m4097) :name E121)
           ((verb-threw m4097 m-1) :name E122)
           ((verb-thinking m4150 m4097) :name E123)
           ((verb-swallowed m4150 m4097) :name E124)
           ((verb-was m-1 m4097) :name E125)
           ((verb-tasted m4150 m-1) :name E126)
           ((verb-found m4150 m4097) :name E127)
           ((verb-flew m-1 m4150) :name E128)
           ((verb-was m-1 m4097) :name E129)
           ((verb-perceived m4097 m-1) :name E130)
           ((verb-let m4097 m4164) :name E131)
           ((verb-hid m4097 m4097) :name E132)
           ((verb-go m4164 m-1) :name E133)
           ((verb-came m-1 m4107) :name E134)
           ((verb-flying m-1 m4107) :name E135)
           ((verb-said m4107 m4191) :name E136)
           ((verb-Give m4189 m4097) :name E137)
           ((verb-replied m-1 m4097) :name E138)
           ((verb-take m-1 m4097) :name E139)
           ((verb-began m4107 m-1) :name E140)
           ((verb-licking m4107 m-1) :name E141)
           ((verb-sent m4150 m-1) :name E142)
           ((verb-caught m-1 m4150) :name E143)
           ((verb-began m-1 m4150) :name E144)
           ((verb-was m-1 m4150) :name E145)
           ((verb-consumed m-1 m4150) :name E146)
           ((verb-was m-1 m4203) :name E147)
           ((verb-drink m4203 m-1) :name E148)
           ((verb-had m4203 m-1) :name E149)
         )
       )

     )
   )
)
    