
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-1
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1 t2))
         (phase2 (:s  t3 t4 t5 t6 t7 t8 t9 t10 t11 t12))

       )
       (:templates
         ;; A dragon appeared near Kiev; he took heavy tribute from the people - a lovely maiden from every house, whom he then devoured.
         ;; Finally, it was the fate of the tsar's daughter to go to the dragon.
         ;; Instead, he took her to wife.
         ;; Whenever he went out, he boarded up his house to prevent the princess from escaping.
         ;; The princess had a little dog that had followed her to the dragon's lair.
         ;; The princess often wrote to her father and mother.
         ;; She would attach her letter to the dog's neck, and the dog would take it to them and even bring back the answer.
         ;; One day the tsar and tsarina wrote to their daughter, asking her to find out who in this world was stronger than the dragon.
         ;; The princess became kindlier toward the dragon and began to question him.
         ;; For a long time he did not answer, but one day he said inadvertently that a tanner in the city of Kiev was stronger than he.
         ;; When the princess heard this, she wrote her father to find Nikita the Tanner in Kiev and to send him to deliver her from captivity.
         ;; Upon receiving this letter, the tsar went in person to beg Nikita the Tanner to free his land from the wicked dragon and rescue the princess.

         (t1 "" (STORY1-m1084 "A dragon") " appeared near Kiev ; " (STORY1-VERB1 "" (STORY1-m1084 "he") " took heavy tribute from " (STORY1-m1087 "the people") " - " (STORY1-m1088 "a lovely maiden from every house, whom he then devoured") " " ) ". ")
         (t2 "Finally , it was the fate of " (STORY1-m1091 "the tsar's daughter") " to go to " (STORY1-m1084 "the dragon") " . ")
         (t1001 (STORY1-EXTRA1  (STORY1-m1088 "a lovely maiden from every house, whom he then devoured") " is the " (Other "Other") ) ".")
         (t1002 (STORY1-EXTRA2  (STORY1-m1092 "tsar") " is the " (Other "Other") ) ".")
         (t1003 (STORY1-EXTRA3  (STORY1-m1091 "the tsar's daughter") " is the " (Prize "Prize") ) ".")
         (t1004 (STORY1-EXTRA4  (STORY1-m1084 "the dragon") " is the " (Villain "Villain") ) ".")
         (t1005 (STORY1-EXTRA5  (STORY1-m1087 "the people") " is the " (Other "Other") ) ".")
         (t3 "Instead , " (STORY1-VERB2 "" (STORY1-m1084 "he") " took " (STORY1-m1091 "her") " " ) "to wife . ")
         (t4 "Whenever " (STORY1-m1084 "he") " went out , " (STORY1-m1084 "he") " boarded up his house to prevent " (STORY1-m1091 "the princess") " from escaping . ")
         (t5 "" (STORY1-m1091 "The princess") " had a little dog that had followed her to the " (STORY1-m1084 "dragon") " 's lair . ")
         (t6 "" (STORY1-m1091 "The princess") " often wrote to her " (STORY1-m1092 "father") " and " (STORY1-m1096 "mother") " . ")
         (t7 "" (STORY1-m1091 "She") " would attach her letter to the dog 's neck , and the dog would take it to them and even bring back the answer . ")
         (t8 "One day the " (STORY1-m1092 "tsar") " and " (STORY1-m1096 "tsarina") " wrote to their " (STORY1-m1091 "their daughter") " , asking her to find out " (STORY1-m1101 "who in this world was stronger than the dragon") " " (STORY1-m1084 "the dragon") " . ")
         (t9 "" (STORY1-m1091 "The princess") " became kindlier toward " (STORY1-m1084 "the dragon") " and began to question " (STORY1-m1084 "him") " . ")
         (t10 "For a long time " (STORY1-m1084 "he") " did not answer , but one day " (STORY1-m1084 "he") " said inadvertently that " (STORY1-m1106 "a tanner in the city of Kiev") " the city of Kiev was stronger than " (STORY1-m1084 "he") " . ")
         (t11 "When " (STORY1-m1091 "the princess") " heard this , " (STORY1-m1091 "she") " wrote her " (STORY1-m1092 "her father") " to find " (STORY1-m1106 "Nikita the Tanner") " in Kiev and to send " (STORY1-m1106 "him") " to deliver her from captivity . ")
         (t12 "Upon receiving this letter , " (STORY1-m1092 "the tsar") " went in person to beg " (STORY1-m1106 "Nikita the Tanner") " to free his land from " (STORY1-m1084 "the wicked dragon") " and rescue " (STORY1-m1091 "the princess") " . ")
         (t1006 (STORY1-EXTRA6  (STORY1-m1088 "a lovely maiden from every house, whom he then devoured") " is the " (Other "Other") ) ".")
         (t1007 (STORY1-EXTRA7  (STORY1-m1091 "the princess") " is the " (Prize "Prize") ) ".")
         (t1008 (STORY1-EXTRA8  (STORY1-m1092 "the tsar") " is the " (Other "Other") ) ".")
         (t1009 (STORY1-EXTRA9  (STORY1-m1096 "tsarina") " is the " (Other "Other") ) ".")
         (t1010 (STORY1-EXTRA10  (STORY1-m1101 "who in this world was stronger than the dragon") " is the " (NA "NA") ) ".")
         (t1011 (STORY1-EXTRA11  (STORY1-m1106 "Nikita the Tanner") " is the " (Hero "Hero") ) ".")
         (t1012 (STORY1-EXTRA12  (STORY1-m1084 "the wicked dragon") " is the " (Villain "Villain") ) ".")
         (t1013 (STORY1-EXTRA13  (STORY1-m1087 "the people") " is the " (Other "Other") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY1-m1088 :type FE)
           (STORY1-m1092 :type MA)
           (STORY1-m1091 :type FE)
           (STORY1-m1084 :type MB)
           (STORY1-m1087 :type GR)
         )
         (:expressions
           ((levin-11-3 STORY1-m1084 STORY1-m1084) :name STORY1-VERB1)
           ((roleOther STORY1-m1088) :name STORY1-EXTRA0)
           ((roleOther STORY1-m1092) :name STORY1-EXTRA1)
           ((rolePrize STORY1-m1091) :name STORY1-EXTRA2)
           ((roleVillain STORY1-m1084) :name STORY1-EXTRA3)
           ((roleOther STORY1-m1087) :name STORY1-EXTRA4)
         )
       )
       (phase2
         (:entities
           (STORY1-m1088 :type FE)
           (STORY1-m1091 :type FE)
           (STORY1-m1092 :type MA)
           (STORY1-m1096 :type FE)
           (STORY1-m1101 :type GR)
           (STORY1-m1106 :type MA)
           (STORY1-m1084 :type MB)
           (STORY1-m1087 :type GR)
         )
         (:expressions
           ((levin-11-3 STORY1-m1084 STORY1-m1091) :name STORY1-VERB2)
           ((levin-46 STORY1-m1084 STORY1-m1091) :name STORY1-VERB3)
           ((levin-37-1 STORY1-m1091 STORY1-m1092) :name STORY1-VERB4)
           ((levin-37-1 STORY1-m1092 STORY1-m1091) :name STORY1-VERB5)
           ((levin-55-1 STORY1-m1091 STORY1-m1084) :name STORY1-VERB6)
           ((levin-37-7 STORY1-m1084 STORY1-m1084) :name STORY1-VERB7)
           ((levin-37-1 STORY1-m1091 STORY1-m1106) :name STORY1-VERB8)
           ((levin-47-7 STORY1-m1092 STORY1-m1084) :name STORY1-VERB9)
           ((roleOther STORY1-m1088) :name STORY1-EXTRA5)
           ((rolePrize STORY1-m1091) :name STORY1-EXTRA6)
           ((roleOther STORY1-m1092) :name STORY1-EXTRA7)
           ((roleOther STORY1-m1096) :name STORY1-EXTRA8)
           ((roleNA STORY1-m1101) :name STORY1-EXTRA9)
           ((roleHero STORY1-m1106) :name STORY1-EXTRA10)
           ((roleVillain STORY1-m1084) :name STORY1-EXTRA11)
           ((roleOther STORY1-m1087) :name STORY1-EXTRA12)
         )
       )

     )
   )
)
    