
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-5
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4))
         (phase2 (:s  t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42))

       )
       (:templates
         ;; Shall I amuse you with a little tale?
         ;; It's a wonderful tale.
         ;; There are marvelous marvels, wondrous wonders, and the laborer Shabarsha, Shabarsha who is a rogue among rogues: oh, well, in for a penny, in for a pound!
         ;; So Shabarsha set off to work as a laborer, and times were bad.
         ;; But one owner thought, a deep thought.
         ;; How could he chase away his misery, what could he live on, where could he get some money?
         ;; "Don't worry about it," said Shabarsha to him.
         ;; "There'll come a day and there will be both grain and money!"
         ;; And Shabarsha set off for the millpond.
         ;; "At any rate I can catch some fish.
         ;; I'll sell them and I'll have some money.
         ;; But I've no line and no hook.
         ;; Wait a minute and I'll make one."
         ;; He asked the miller for a handful of hemp, sat down on the shore, and started weaving his tackle.
         ;; He wove and wove, and then a boy in a black shirt and red hat jumped out of the water.
         ;; "Grandfather!
         ;; What are you doing here?" he asked.
         ;; "I'm weaving a line."
         ;; "Why?"
         ;; "I intend to cleanse this pond of all you devils by pulling you out of the water."
         ;; "Oh, no!
         ;; Wait a little.
         ;; I'll go and tell grandfather."
         ;; The imp dove deep down and Shabarsha went back to his work.
         ;; "Wait a minute," he thought, "I'll play a trick on you, you cursed ones.
         ;; You'll bring me some gold and silver."
         ;; And Shabarsha began digging a pit and when he had dug it, he placed his hat with a cutout hole over it.
         ;; "Shabarsha, oh Shabarsha!
         ;; Grandfather says that you and I should trade.
         ;; What will you take not to drag us out of the water?"
         ;; "Fill that hat full of gold and silver."
         ;; The imp dove back into the water.
         ;; He came back and said, "Grandfather says that you and I should first wrestle."
         ;; "What do you mean, milksop; why should I wrestle with the likes of you?
         ;; You couldn't even deal with my middle brother, Misha."
         ;; "And where is your Misha?"
         ;; "Look over there.
         ;; He's resting in that ravine under a bush."
         ;; "How can I call him out?"
         ;; "Go up to him and hit him in the side.
         ;; Then he'll get up of his own accord."
         ;; The imp went into the ravine, found the bear, and whacked him in the side with his club.

         (t1 "Shall " (E1 "" (m4305 "I") " amuse " (m4306 "you") " " ) "with a little tale ? ")
         (t2 "It 's a wonderful tale . ")
         (t3 "There are marvelous marvels , wondrous wonders , and the laborer Shabarsha , Shabarsha who is a rogue among rogues : oh , well , in for a penny , in for a pound ! ")
         (t4 "So " (m4311 "Shabarsha") " set off to work as " (m4313 "a laborer") " , and times were bad . ")
         (t1001 (EXTRA1  (m4305 "I") " is the " (NA "NA") ) ".")
         (t1002 (EXTRA2  (m4306 "you") " is the " (NA "NA") ) ".")
         (t1003 (EXTRA3  (m4313 "a laborer") " is the " (NA "NA") ) ".")
         (t1004 (EXTRA4  (m4311 "Shabarsha") " is the " (Hero "Hero") ) ".")
         (t5 "But one owner thought , a deep thought . ")
         (t6 "How could he chase away his misery , what could he live on , where could he get some money ? ")
         (t7 "' Do n't worry about it , ' said " (m4311 "Shabarsha") " to " (m4317 "him") " . ")
         (t8 "' There 'll come a day and there will be both grain and money ! ' ")
         (t9 "And Shabarsha set off for the millpond . ")
         (t10 "' At any rate I can catch some fish . ")
         (t11 "I 'll sell them and I 'll have some money . ")
         (t12 "But I 've no line and no hook . ")
         (t13 "Wait a minute and I 'll make one . ' ")
         (t14 "" (m4311 "He") " asked " (m4330 "the miller") " for a handful of hemp , sat down on the shore , and started weaving his tackle . ")
         (t15 "He wove and wove , and then a boy in a black shirt and red hat jumped out of the water . ")
         (t16 "' Grandfather ! ")
         (t17 "What are " (m4311 "you") " doing here ? ' " (m4334 "he") " asked . ")
         (t18 "' I 'm weaving a line . ' ")
         (t19 "' Why ? ' ")
         (t20 "' " (m4311 "I") " intend to cleanse this pond of all you devils by pulling " (m4337 "you") " out of the water . ' ")
         (t21 "' Oh , no ! ")
         (t22 "Wait a little . ")
         (t23 "" (m4334 "I") " 'll go and tell " (m4339 "grandfather") " . ' ")
         (t24 "The imp dove deep down and Shabarsha went back to his work . ")
         (t25 "' Wait a minute , ' he thought , ' " (m4311 "I") " 'll play a trick on " (m4337 "you, you cursed ones") " . ")
         (t26 "" (m4337 "You") " 'll bring " (m4311 "me") " some gold and silver . ' ")
         (t27 "And Shabarsha began digging a pit and when " (m4311 "he") " had dug it , " (m4311 "he") " placed his hat with a cutout hole over it . ")
         (t28 "' Shabarsha , oh Shabarsha ! ")
         (t29 "" (m4339 "Grandfather") " says that you and " (m4334 "I") " should trade . ")
         (t30 "What will " (m4311 "you") " take not to drag " (m4337 "us") " out of the water ? ' ")
         (t31 "' Fill that hat full of gold and silver . ' ")
         (t32 "The imp dove back into the water . ")
         (t33 "" (m4334 "He") " came back and said , ' " (m4339 "Grandfather") " says that " (m4311 "you") " and " (m4334 "I") " should first wrestle . ' ")
         (t34 "' What do " (m4334 "you") " mean , " (m4334 "milksop") " ; why should " (m4311 "I") " wrestle with " (m4334 "the likes of you") " ? ")
         (t35 "" (m4334 "You") " could n't even deal with my " (m4348 "my middle brother, Misha") " . ' ")
         (t36 "' And where is your Misha ? ' ")
         (t37 "' Look over there . ")
         (t38 "He 's resting in that ravine under a bush . ' ")
         (t39 "' How can " (m4334 "I") " call " (m4348 "him") " out ? ' ")
         (t40 "' Go up to him and hit him in the side . ")
         (t41 "Then he 'll get up of his own accord . ' ")
         (t42 "" (m4334 "The imp") " went into the ravine , found " (m4348 "the bear") " , and whacked " (m4348 "him") " in the side with his club . ")
         (t1005 (EXTRA5  (m4337 "us") " is the " (NA "NA") ) ".")
         (t1006 (EXTRA6  (m4330 "the miller") " is the " (NA "NA") ) ".")
         (t1007 (EXTRA7  (m4334 "The imp") " is the " (Villain "Villain") ) ".")
         (t1008 (EXTRA8  (m4305 "I") " is the " (NA "NA") ) ".")
         (t1009 (EXTRA9  (m4306 "you") " is the " (NA "NA") ) ".")
         (t1010 (EXTRA10  (m4339 "Grandfather") " is the " (Villain "Villain") ) ".")
         (t1011 (EXTRA11  (m4311 "I") " is the " (Hero "Hero") ) ".")
         (t1012 (EXTRA12  (m4313 "a laborer") " is the " (NA "NA") ) ".")
         (t1013 (EXTRA13  (m4348 "him") " is the " (NA "NA") ) ".")
         (t1014 (EXTRA14  (m4317 "him") " is the " (NA "NA") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m4305 :type MB)
           (m4306 :type MB)
           (m4313 :type MA)
           (m4311 :type MA)
         )
         (:expressions
           ((levin-31-1 m4305 m4306) :name E1)
           ((levin-09-1 m4311 m4313) :name E2)
           ((roleNA m4305) :name EXTRA0)
           ((roleNA m4306) :name EXTRA1)
           ((roleNA m4313) :name EXTRA2)
           ((roleHero m4311) :name EXTRA3)
         )
       )
       (phase2
         (:entities
           (m4337 :type GR)
           (m4330 :type MA)
           (m4334 :type MB)
           (m4305 :type MB)
           (m4306 :type MB)
           (m4339 :type MB)
           (m4311 :type MA)
           (m4313 :type MA)
           (m4348 :type AA)
           (m4317 :type MA)
         )
         (:expressions
           ((levin-37-7 m4311 m4317) :name E3)
           ((levin-37-1 m4311 m4330) :name E4)
           ((levin-37-1 m4334 m4311) :name E5)
           ((levin-12 m4311 m4337) :name E6)
           ((levin-37-2 m4334 m4339) :name E7)
           ((levin-36-3 m4311 m4337) :name E8)
           ((levin-11-3 m4337 m4311) :name E9)
           ((levin-09-1 m4311 m4311) :name E10)
           ((levin-37-7 m4339 m4334) :name E11)
           ((levin-11-3 m4311 m4337) :name E12)
           ((levin-37-7 m4334 m4334) :name E13)
           ((levin-29-5 m4334 m4334) :name E14)
           ((levin-29-3 m4334 m4348) :name E15)
           ((levin-29-4 m4334 m4348) :name E16)
           ((roleNA m4337) :name EXTRA4)
           ((roleNA m4330) :name EXTRA5)
           ((roleVillain m4334) :name EXTRA6)
           ((roleNA m4305) :name EXTRA7)
           ((roleNA m4306) :name EXTRA8)
           ((roleVillain m4339) :name EXTRA9)
           ((roleHero m4311) :name EXTRA10)
           ((roleNA m4313) :name EXTRA11)
           ((roleNA m4348) :name EXTRA12)
           ((roleNA m4317) :name EXTRA13)
         )
       )

     )
   )
)
    