
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-7
     (:discourse
       (:clauses
         (phase1 (:s  t1))

       )
       (:templates
         ;; This soldier got permission to go on leave.

         (t1 "This soldier got permission to go on leave . ")
         (t1001 (EXTRA1  (m5965 "This soldier") " is the " (Hero "Hero") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m5965 :type MA)
         )
         (:expressions
           ((roleHero m5965) :name EXTRA0)
         )
       )

     )
   )
)
    