
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-17
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2))
         (phase2 (:s  t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42 t43 t44 t45 t46 t47 t48 t49 t50 t51 t52 t53 t54 t55 t56 t57 t58 t59 t60 t61 t62 t63 t64 t65 t66 t67 t68 t69 t70 t71 t72 t73 t74 t75 t76 t77 t78 t79 t80 t81 t82 t83 t84 t85 t86 t87 t88 t89 t90 t91 t92 t93 t94 t95 t96 t97 t98 t99 t100 t101 t102 t103 t104 t105 t106 t107 t108))
         (phase3 (:s  t109 t110 t111 t112 t113 t114 t115 t116 t117 t118 t119 t120 t121 t122 t123 t124 t125 t126 t127 t128 t129 t130 t131 t132 t133 t134 t135 t136 t137 t138 t139 t140 t141 t142 t143 t144 t145 t146 t147 t148 t149))

       )
       (:templates
         ;; For many years a certain tsar had kept under lock and key a little peasant all made of copper, with iron hands and a steel head - a cunning man, a wizard of a man!
         ;; Prince Ivan, the tsar's son who was still a little boy, walked by the prison.
         ;; Prince Ivan did not know anything yet, he was very little, so he drew some water and gave it to him; with the help of the water the old man vanished from the prison.
         ;; This was reported to the tsar, who ordered Prince Ivan to be driven from the kingdom.
         ;; The tsar's word was law.
         ;; Prince Ivan was banished and he left home not knowing where to go.
         ;; He walked for a long time; at last he arrived in another kingdom, presented himself to the king, and asked to be taken into his service.
         ;; The king accepted him and appointed him stableboy.
         ;; But all he did in the stable was sleep; he did not tend the horses, and the stable master beat him more than once.
         ;; Prince Ivan bore all this patiently.
         ;; Meanwhile another king had asked for the hand of this king's daughter, was rebuffed, and declared war.
         ;; The king departed with his troops, and Princess Martha, his daughter, was left to rule the kingdom.
         ;; Even before this she had noticed that Prince Ivan was not of lowly origin; now she appointed him governor of one of her provinces.
         ;; Prince Ivan left for his province and governed it.
         ;; One day he went hunting; he had no sooner left the town than the peasant all made of copper, with iron hands and a steel head, appeared from nowhere.
         ;; "Good day, Prince Ivan!"
         ;; he said.
         ;; Prince Ivan returned his greeting.
         ;; The old man said: "Come, pay me a visit."
         ;; They walked together.
         ;; The old man led him into a rich house and called to his little daughter: "Hey, give us food and drink and a half-gallon cup of wine!"
         ;; They began to eat; suddenly the daughter brought in a half-gallon cup of wine and presented it to Prince Ivan.
         ;; He refused, saying: "I cannot drink all that!"
         ;; The old man told him to try.
         ;; The young prince took the cup and suddenly felt great strength in him; in one draught he drank all the wine.
         ;; Then the old man asked him to go for a walk with him; they came to a stone that weighed about twenty thousand pounds.
         ;; The old man said: "Lift that stone, Prince Ivan!"
         ;; He thought: "I surely cannot lift that stone, but I will try."
         ;; He picked it up, tossed it easily, and said to himself: "Whence comes all this new strength?
         ;; Probably the old man has given it to me with the wine."
         ;; They walked some time, then returned home.
         ;; The old man told his second daughter to bring a gallon of wine.
         ;; Prince Ivan boldly took the cup and drank it in one draught.
         ;; Then again they went for a walk and came to a stone that weighed forty thousand pounds.
         ;; The old man said to Prince Ivan: "Try to toss this stone."
         ;; Prince Ivan snatched it at once, tossed it, and thought to himself: "What strength there is in me!"
         ;; Again they returned home, and the old man told his youngest daughter to bring a gallon and a half of green wine.
         ;; Prince Ivan drank that, too, in one draught, went again to walk with the old man, and this time easily tossed a stone that weighed sixty thousand pounds.
         ;; Then the old man gave him a self-serving tablecloth and said: "Now, Prince Ivan, you have such strength that no horse will carry you!
         ;; Have the porch of your house made over, else it will not support you; you also need other chairs, and more rafters under the floor.
         ;; God speed you!"
         ;; All the people laughed when they saw the governor returning from the hunt on foot and leading his horse by the bridle.
         ;; He came home, had supports put under the floors, had his chairs made over, dismissed all his cooks and chambermaids, and lived alone like a hermit.
         ;; Everyone wondered how he could live without eating: no one cooked for him, for he was fed by his self-serving tablecloth.
         ;; He ceased visiting anyone, because none of the chairs in other people's houses could support his weight.
         ;; The king returned from his campaign, learned that Prince Ivan was governor of a province, ordered that he be replaced, and again made him a stableboy.
         ;; There was nothing Prince Ivan could do about it, and he began once more to live as a stableboy.
         ;; One day the groom ordered him to do something and struck him; Prince Ivan could not restrain himself; he struck back and knocked off the groom's head.
         ;; This affair reached the ears of the king; Prince Ivan was brought before him.
         ;; "Why did you kill the groom?"
         ;; asked the king.
         ;; "He struck me first; I hit back, not very hard, but somehow his head fell off."
         ;; The other stableboys said the same thing - that the groom had hit first and that Prince Ivan had not hit him back hard.
         ;; No punishment was meted out to Prince Ivan; but he was sent from the stables to the army and began to live as a soldier.
         ;; A short time afterward a little man no bigger than a nail, with a beard a cubit long, came to the king and handed him a letter from the Water King with three black seals on it.
         ;; The letter ran as follows: "If the king does not put his daughter, Princess Martha, on such and such an island on such and such a day to be given in marriage to the Water King's son, he will kill all the people and burn the whole kingdom, and a three-headed dragon will come for Princess Martha."
         ;; The king read this letter, and wrote a letter to the Water King saying that he would give him his daughter; he politely escorted the little old man to the door of the palace, then summoned his senators and councilors to hold council as to how they might defend his daughter against the three-headed dragon.
         ;; If he failed to send her to the island, the Water King would devastate the whole kingdom.
         ;; A call was issued: "Will someone volunteer to rescue Princess Martha from the dragon?"
         ;; To him the king would give her in marriage.
         ;; A boastful nobleman responded to the call, took a company of soldiers, and brought Princess Martha to the island; he left her in a hut, and he himself waited for the dragon outside.
         ;; Meanwhile Prince Ivan learned that Princess Martha had been taken to the Water King, so he too armed himself and went to the island.
         ;; He came into the hut and found Princess Martha weeping.
         ;; "Don't weep, princess," he said to her.
         ;; "God is merciful."
         ;; He lay on a bench, put his head on Princess Martha's knees, and fell asleep.
         ;; Suddenly the dragon appeared and water rushed in after him to a height of three yards.
         ;; When the water began to rise, the boastful nobleman who was stationed there with his soldiers ordered: "March to the woods!"
         ;; All the soldiers hid in the woods.
         ;; The dragon came out and made straight for the hut.
         ;; Princess Martha saw the dragon coming for her and awakened Prince Ivan.
         ;; He jumped down from the bench, in one stroke cut off all the three heads of the dragon, and left.
         ;; The nobleman took Princess Martha home to the king, her father.
         ;; After a short time, the little old man no bigger than a nail, with a beard a cubit long, again came out of the water and brought a letter from the Water King with six black seals on it, summoning the king to put his daughter on the same island, to be taken by a six-headed dragon; if the king refused to surrender her, the Water King threatened to flood the whole kingdom.
         ;; The king wrote in answer that he agreed to surrender Princess Martha.
         ;; The little old man left.
         ;; The king issued a call, and messengers were sent everywhere: could not a man be found to rescue the princess from the dragon?
         ;; The same nobleman presented himself again, saying: "Your Majesty, I will rescue her; only give me a company of soldiers."
         ;; "Don't you need more than a company?
         ;; This time it is a dragon with six heads."
         ;; "No, a company is enough, I don't need more."
         ;; The party gathered and they took Princess Martha away.
         ;; When Prince Ivan learned that the princess was again in danger, remembering the kindness that she had done him by appointing him governor, he went to the island; again he found Princess Martha in the hut, and entered.
         ;; She was waiting for him and rejoiced to see him.
         ;; He lay down and fell asleep.
         ;; Suddenly the six-headed dragon began to emerge, and six yards of water rushed in.
         ;; This time the nobleman and his soldiers had posted themselves in the woods immediately.
         ;; The dragon entered the hut, and Princess Martha awakened Prince Ivan.
         ;; The dragon and Prince Ivan came to blows, and fought and fought; Prince Ivan cut off one head of the dragon, a second, a third, and finally all six heads, and cast them into the water, and went away as though nothing had happened.
         ;; The nobleman and his soldiers came out of the woods, and went home and reported to the king that God had helped them to rescue Princess Martha.
         ;; And it seems that this same nobleman threatened the princess in some manner, for she did not dare to say that it was not he who had rescued her.
         ;; The nobleman began to insist upon marrying her, but Princess Martha told him to wait.
         ;; "Let me recover from my fear," she said.
         ;; "I was terribly frightened!"
         ;; Suddenly once more the same little old man no bigger than a nail, with a beard a cubit long, emerged from the water and brought a letter with nine black seals, demanding that the king straightway send Princess Martha to such and such an island on such and such a day, to be carried off by a nine-headed dragon, and threatening, if he did not send her, to flood the whole kingdom.
         ;; Again the king wrote in answer that he agreed, and began to seek a man who could rescue the princess from the nine-headed dragon.
         ;; The same nobleman again presented himself and left with a company of soldiers and Princess Martha.
         ;; Prince Ivan heard about it, armed himself and went to the island too, and Princess Martha was waiting for him.
         ;; She was overjoyed to see him and began to question him as to his place of birth, his father's name, and his own name.
         ;; He did not answer, but lay down and fell asleep.
         ;; The nine-headed dragon began to emerge, and brought with him a flood of water nine yards high.
         ;; Again the nobleman ordered the soldiers to march to the woods, and they hid there.
         ;; Princess Martha began to rouse Prince Ivan, but could not awaken him.
         ;; The dragon was nearing the threshold.
         ;; She wept, but still could not awaken Prince Ivan.
         ;; The dragon began to crawl close, ready to snatch Prince Ivan, but still he slept.
         ;; Princess Martha had a penknife, and with it she cut Prince Ivan's cheek.
         ;; He woke, jumped up, and began to shout insults at the dragon.
         ;; Out of nowhere appeared the little peasant all made of copper, with iron hands and a steel head, and he gripped the dragon; the two together cut off all his heads, cast them into the water, and left.
         ;; The nobleman was happier than ever, came rushing out of the woods, went home to his kingdom, and began to press the king to celebrate the wedding.
         ;; Princess Martha refused.
         ;; "Wait a little while, let me recover," she said.
         ;; "I was terribly frightened."
         ;; Again the little man no bigger than a nail, with a beard a cubit long, brought a letter.
         ;; The Water King demanded the dragon's slayer.
         ;; The nobleman did not feel like going to the Water King, but there was nothing that he could do.
         ;; He was ordered to go there.
         ;; A ship was rigged out and they set sail (Prince Ivan was now serving in the fleet, and somehow happened to be on this ship).
         ;; They were sailing along briskly when a ship came toward them.
         ;; It flew like a bird and from it came cries as it rushed by: "The culprit!
         ;; The culprit!"
         ;; They sailed on a little farther and met another ship, and again cries came from it: "The culprit!
         ;; The culprit!"
         ;; Prince Ivan pointed at the nobleman; he was thrashed and thrashed until he was half dead.
         ;; The ship went by.
         ;; Now they came to the Water King.
         ;; He ordered that a bath of iron or steel be heated red hot and the culprit put in it.
         ;; The nobleman was terrified his heart went into his boots - little father death was coming!
         ;; But one man on the ship had become attached to Prince Ivan and served him faithfully, realizing that he was not of lowly birth.
         ;; Prince Ivan sent him, saying: "Do you go and sit in that bath."
         ;; He went at once, and, wonder of wonders, nothing happened to him; he came back unharmed.
         ;; Again the culprit was sent for, this time to be brought before the Water King himself.
         ;; The Water King abused him roundly, thrashed him, and had him driven out.
         ;; Then they all went home.
         ;; Upon his return the nobleman began to boast even louder than before.
         ;; He did not leave the king's side for a moment, so impatient was he to have the wedding celebrated.
         ;; The king agreed, and a day was set for the nuptials.
         ;; Now the nobleman was very proud - so proud, no one dared to touch him or come near him!
         ;; But the princess said to her father: "Father, command all the soldiers to assemble; I want to look at them."
         ;; Straightway the soldiers were assembled.
         ;; Princess Martha reviewed them all.
         ;; When she came to Prince Ivan, she glanced at his cheek and saw the scar she had made when she cut him with her penknife.
         ;; She took him by the hand and led him to her father.
         ;; "Here is the man who rescued me from the dragon, father," she said.
         ;; "I did not know who he was, but now I recognize him by the scar on his cheek.
         ;; The nobleman just sat in the woods with his soldiers."
         ;; All the soldiers were asked whether they had sat in the woods while the dragon was slain, and they answered: "That is the truth, Your Royal Majesty!"
         ;; The nobleman was half dead from shame.
         ;; He was disgraced and banished; but Prince Ivan married Princess Martha, and they began to live and chew bread together.

         (t1 "For many years " (4126 "a certain tsar") "had kept under lock and key " (4127 "a little peasant all made of copper, with iron hands and a steel head - a cunning man, a wizard of a man") "" (4127 "a little peasant all made of copper, with iron hands and a steel head - a cunning man, a wizard of a man") ""
         (t2 "" (4132 "Prince Ivan, the tsar's son who was still a little boy") "" (4132 "Prince Ivan, the tsar's son who was still a little boy") ""
         (t3 "" (4132 "Prince Ivan") "did not know anything yet , " (4132 "he") "was very little , so " (4132 "he") "drew some water and gave it to him ; with the help of the water " (4127 "the old man") "vanished from the prison . "
         (t4 "This was reported to " (4126 "the tsar, who ordered Prince Ivan to be driven from the kingdom") "" (4126 "the tsar, who ordered Prince Ivan to be driven from the kingdom") ""
         (t5 "The " (4126 "tsar") "'s word was law . "
         (t6 "" (4132 "Prince Ivan") "was banished and " (4132 "he") "left home not knowing where to go . "
         (t7 "" (4132 "He") "walked for a long time ; at last " (4132 "he") "arrived in another kingdom , presented " (4132 "himself") "to the king , and asked to be taken into his service . "
         (t8 "" (4143 "The king") "accepted " (4132 "him") "and appointed " (4132 "him") "stableboy . "
         (t9 "But all " (4132 "he") "did in the stable was sleep ; " (4132 "he") "did not tend the horses , and the stable " (4147 "the stable master") "beat " (4132 "him") "more than once . "
         (t10 "" (4132 "Prince Ivan") "bore " (4148 "all this") "patiently . "
         (t11 "Meanwhile " (4149 "another king") "had asked for the hand of this king 's daughter , was rebuffed , and declared war . "
         (t12 "" (4143 "The king") "departed with his " (4154 "his troops") ", and " (4151 "Princess Martha, his daughter") "" (4151 "Princess Martha, his daughter") "to rule the kingdom . "
         (t13 "Even before this " (4151 "she") "had noticed that " (4132 "Prince Ivan") "was not of lowly origin ; now " (4151 "she") "appointed him governor of one of her provinces . "
         (t14 "" (4132 "Prince Ivan") "left for his province and governed it . "
         (t15 "One day " (4132 "he") "went hunting ; " (4132 "he") "had no sooner left the town than " (4127 "the peasant all made of copper, with iron hands and a steel head") "" (4127 "the peasant all made of copper, with iron hands and a steel head") ", appeared from nowhere . "
         (t16 "' Good day , Prince Ivan ! ' "
         (t17 "" (4127 "he") "said . "
         (t18 "" (4132 "Prince Ivan") "returned his greeting . "
         (t19 "" (4127 "The old man") "said : ' Come , pay " (4127 "me") "a visit . ' "
         (t20 "They walked together . "
         (t21 "" (4127 "The old man") "led " (4132 "him") "into a rich house and called to his " (4164 "his little daughter") ": ' Hey , give us food and drink and a half-gallon cup of wine ! ' "
         (t22 "They began to eat ; suddenly " (4164 "the daughter") "brought in a half-gallon cup of wine and presented it to " (4132 "Prince Ivan") ". "
         (t23 "" (4132 "He") "refused , saying : ' " (4132 "I") "can not drink all that ! ' "
         (t24 "" (4127 "The old man") "told " (4132 "him") "to try . "
         (t25 "" (4132 "The young prince") "took the cup and suddenly felt great strength in " (4132 "him") "; in one draught " (4132 "he") "drank all the wine . "
         (t26 "Then " (4127 "the old man") "asked " (4132 "him") "to go for a walk with him ; they came to a stone that weighed about twenty thousand pounds . "
         (t27 "" (4127 "The old man") "said : ' Lift that stone , " (4132 "Prince Ivan") "! ' "
         (t28 "" (4132 "He") "thought : ' " (4132 "I") "surely can not lift that stone , but " (4132 "I") "will try . ' "
         (t29 "" (4132 "He") "picked it up , tossed it easily , and said to " (4132 "himself") ": ' Whence comes all this new strength ? "
         (t30 "Probably " (4127 "the old man") "has given it to " (4132 "me") "with the wine . ' "
         (t31 "They walked some time , then returned home . "
         (t32 "" (4127 "The old man") "told his " (4175 "his second daughter") "to bring a gallon of wine . "
         (t33 "" (4132 "Prince Ivan") "boldly took the cup and drank it in one draught . "
         (t34 "Then again they went for a walk and came to a stone that weighed forty thousand pounds . "
         (t35 "" (4127 "The old man") "said to " (4132 "Prince Ivan") ": ' Try to toss this stone . ' "
         (t36 "" (4132 "Prince Ivan") "snatched it at once , tossed it , and thought to " (4132 "himself") ": ' What strength there is in me ! ' "
         (t37 "Again they returned home , and " (4127 "the old man") "told his " (4182 "his youngest daughter") "to bring a gallon and a half of green wine . "
         (t38 "" (4132 "Prince Ivan") "drank that , too , in one draught , went again to walk with " (4127 "the old man") ", and this time easily tossed a stone that weighed sixty thousand pounds . "
         (t39 "Then " (4127 "the old man") "gave " (4132 "him") "a self-serving tablecloth and said : ' Now , Prince Ivan , " (4132 "you") "have such strength that no horse will carry " (4132 "you") "! "
         (t40 "Have the porch of your house made over , else it will not support " (4132 "you") "; " (4132 "you") "also need other chairs , and " (4194 "more rafters") "under the floor . "
         (t41 "God speed " (4132 "you") "! ' "
         (t42 "" (4197 "All the people") "laughed when " (4197 "they") "saw " (4132 "the governor") "returning from the hunt on foot and leading his horse by the bridle . "
         (t43 "" (4132 "He") "came home , had " (4194 "supports") "put under the floors , had his chairs made over , dismissed " (4201 "all his cooks and chambermaids") "cooks " (4201 "all his cooks and chambermaids") ", and lived alone like a hermit . "
         (t44 "" (4197 "Everyone") "wondered how " (4132 "he") "could live without eating : no one cooked for " (4132 "him") ", for " (4132 "he") "was fed by his self-serving tablecloth . "
         (t45 "" (4132 "He") "ceased visiting " (4197 "anyone") ", because none of the chairs in " (4206 "other people") "'s houses could support his weight . "
         (t46 "" (4143 "The king") "returned from his campaign , learned that " (4132 "Prince Ivan") "was " (4132 "governor of a province") "a province , ordered that " (4132 "he") "be replaced , and again made " (4132 "him") "a stableboy . "
         (t47 "There was nothing " (4132 "Prince Ivan") "could do about " (4209 "it") ", and " (4132 "he") "began once more to live as " (4132 "a stableboy") ". "
         (t48 "One day " (4212 "the groom") "ordered " (4132 "him") "to do something and struck " (4132 "him") "; " (4132 "Prince Ivan") "could not restrain " (4132 "himself") "; " (4132 "he") "struck back and knocked off the " (4212 "groom") "'s head . "
         (t49 "This affair reached the ears of " (4143 "the king") "; " (4132 "Prince Ivan") "was brought before him . "
         (t50 "' Why did " (4132 "you") "kill " (4212 "the groom") "? ' "
         (t51 "asked " (4143 "the king") ". "
         (t52 "' " (4212 "He") "struck " (4132 "me") "first ; " (4132 "I") "hit back , not very hard , but somehow his head fell off . ' "
         (t53 "" (4218 "The other stableboys") "said the same thing - that " (4212 "the groom") "had hit first and that " (4132 "Prince Ivan") "had not hit " (4212 "him") "back hard . "
         (t54 "No punishment was meted out to Prince Ivan ; but " (4132 "he") "was sent from the stables to the army and began to live as " (4132 "a soldier") ". "
         (t55 "A short time afterward " (4222 "a little man no bigger than a nail, with a beard a cubit long") "a beard a cubit long , came to " (4143 "the king") "and handed him a letter from " (4225 "the Water King") "with three black seals on it . "
         (t56 "The letter ran as follows : ' If " (4143 "the king") "does not put his " (4151 "his daughter, Princess Martha") ", on such and such an island on such and such a day to be given in marriage to " (4230 "the Water King's son") "" (4230 "the Water King's son") "" (4225 "he") "will kill " (4197 "all the people") "and burn the whole kingdom , and " (4231 "a three-headed dragon") "will come for Princess Martha . ' "
         (t57 "" (4143 "The king") "read this letter , and wrote a letter to the Water King saying that " (4143 "he") "would give " (4225 "him") "his " (4151 "his daughter") "; " (4143 "he") "politely escorted " (4222 "the little old man") "to the door of the palace , then summoned his " (4236 "senators") "and councilors to hold council as to how " (4238 "they") "might defend his daughter against " (4231 "the three-headed dragon") ". "
         (t58 "If " (4143 "he") "failed to send her to the island , " (4225 "the Water King") "would devastate the whole kingdom . "
         (t59 "A call was issued : ' Will " (4240 "someone") "volunteer to rescue Princess Martha from " (4231 "the dragon") "? ' "
         (t60 "To him " (4143 "the king") "would give her in marriage . "
         (t61 "" (4241 "A boastful nobleman") "responded to the call , took " (4242 "a company of soldiers") ", and brought " (4151 "Princess Martha") "to the island ; " (4241 "he") "left " (4151 "her") "in a hut , and " (4241 "he himself") "waited for the dragon outside . "
         (t62 "Meanwhile " (4132 "Prince Ivan") "learned that " (4151 "Princess Martha") "had been taken to the Water King , so " (4132 "he") "too armed " (4132 "himself") "and went to the island . "
         (t63 "" (4132 "He") "came into the hut and found " (4151 "Princess Martha") "weeping . "
         (t64 "' Do n't weep , " (4151 "princess") ", ' " (4132 "he") "said to her . "
         (t65 "' " (4196 "God") "is merciful . ' "
         (t66 "" (4132 "He") "lay on a bench , put his head on " (4151 "Princess Martha") "'s knees , and fell asleep . "
         (t67 "Suddenly the dragon appeared and water rushed in after him to a height of three yards . "
         (t68 "When the water began to rise , " (4241 "the boastful nobleman who was stationed there with his soldiers") "" (4241 "the boastful nobleman who was stationed there with his soldiers") "to the woods ! ' "
         (t69 "" (4242 "All the soldiers") "hid in the woods . "
         (t70 "" (4231 "The dragon") "came out and made straight for the hut . "
         (t71 "" (4151 "Princess Martha") "saw " (4231 "the dragon") "coming for her and awakened Prince Ivan . "
         (t72 "" (4132 "He") "jumped down from the bench , in one stroke cut off all the three heads of " (4231 "the dragon") ", and left . "
         (t73 "" (4241 "The nobleman") "took " (4151 "Princess Martha") "home to the king , her father . "
         (t74 "After a short time , " (4222 "the little old man no bigger than a nail, with a beard a cubit long") "a beard a cubit long , again came out of the water and brought a letter from the Water King with six black seals on it , summoning " (4143 "the king") "to put his " (4151 "his daughter") "on the same island , to be taken by " (4256 "a six-headed dragon") "; if " (4143 "the king") "refused to surrender " (4151 "her") ", " (4225 "the Water King") "threatened to flood the whole kingdom . "
         (t75 "" (4143 "The king") "wrote in answer that " (4143 "he") "agreed to surrender " (4151 "Princess Martha") ". "
         (t76 "" (4222 "The little old man") "left . "
         (t77 "" (4143 "The king") "issued a call , and " (4258 "messengers") "were sent everywhere : could not " (4260 "a man") "be found to rescue " (4151 "the princess") "from " (4256 "the dragon") "? "
         (t78 "" (4241 "The same nobleman") "presented " (4241 "himself") "again , saying : ' Your Majesty , " (4241 "I") "will rescue her ; only give " (4241 "me") "" (4261 "a company of soldiers") ". ' "
         (t79 "' Do n't " (4241 "you") "need " (4262 "more than a company") "a company ? "
         (t80 "This time it is " (4256 "a dragon with six heads") "six heads . ' "
         (t81 "' No , " (4261 "a company") "is enough , " (4241 "I") "do n't need " (4262 "more") ". ' "
         (t82 "" (4265 "The party") "gathered and " (4265 "they") "took " (4151 "Princess Martha") "away . "
         (t83 "When " (4132 "Prince Ivan") "learned that " (4151 "the princess") "was again in danger , remembering the kindness that " (4151 "she") "had done him by appointing " (4132 "him") "governor , " (4132 "he") "went to the island ; again " (4132 "he") "found " (4151 "Princess Martha") "in the hut , and entered . "
         (t84 "" (4151 "She") "was waiting for him and rejoiced to see " (4132 "him") ". "
         (t85 "" (4132 "He") "lay down and fell asleep . "
         (t86 "Suddenly " (4256 "the six-headed dragon") "began to emerge , and six yards of water rushed in . "
         (t87 "This time the " (4241 "nobleman") "and his soldiers had posted " (4265 "themselves") "in the woods immediately . "
         (t88 "" (4256 "The dragon") "entered the hut , and Princess Martha awakened Prince Ivan . "
         (t89 "" (4256 "The dragon") "and Prince Ivan came to blows , and fought and fought ; " (4132 "Prince Ivan") "cut off one head of " (4256 "the dragon") ", a second , a third , and finally all six heads , and cast them into the water , and went away as though nothing had happened . "
         (t90 "The nobleman " (4265 "The nobleman and his soldiers") "" (4265 "The nobleman and his soldiers") "out of the woods , and went home and reported to the king that " (4196 "God") "had helped " (4265 "them") "to rescue " (4151 "Princess Martha") ". "
         (t91 "And it seems that " (4241 "this same nobleman") "threatened the princess in some manner , for " (4151 "she") "did not dare to say that it was not " (4241 "he who had rescued her") "" (4151 "her") ". "
         (t92 "" (4241 "The nobleman") "began to insist upon marrying " (4151 "her") ", but " (4151 "Princess Martha") "told " (4241 "him") "to wait . "
         (t93 "' Let " (4151 "me") "recover from my fear , ' " (4151 "she") "said . "
         (t94 "' " (4151 "I") "was terribly frightened ! ' "
         (t95 "Suddenly once more " (4222 "the same little old man no bigger than a nail, with a beard a cubit long") "a beard a cubit long , emerged from the water and brought a letter with nine black seals , demanding that " (4143 "the king") "straightway send " (4151 "Princess Martha") "to such and such an island on such and such a day , to be carried off by " (4279 "a nine-headed dragon") ", and threatening , if " (4143 "he") "did not send " (4151 "her") ", to flood the whole kingdom . "
         (t96 "Again " (4143 "the king") "wrote in answer that " (4143 "he") "agreed , and began to seek a man who could rescue " (4151 "the princess") "from " (4279 "the nine-headed dragon") ". "
         (t97 "" (4241 "The same nobleman") "again presented " (4241 "himself") "and left with a company of soldiers and Princess Martha . "
         (t98 "" (4132 "Prince Ivan") "heard about it , armed " (4132 "himself") "and went to the island too , and " (4151 "Princess Martha") "was waiting for him . "
         (t99 "" (4151 "She") "was overjoyed to see " (4132 "him") "and began to question him as to his place of birth , his " (4126 "his father") "'s name , and his own name . "
         (t100 "" (4132 "He") "did not answer , but lay down and fell asleep . "
         (t101 "" (4279 "The nine-headed dragon") "began to emerge , and brought with " (4279 "him") "a flood of water nine yards high . "
         (t102 "Again " (4241 "the nobleman") "ordered " (4282 "the soldiers") "to march to the woods , and " (4288 "they") "hid there . "
         (t103 "" (4151 "Princess Martha") "began to rouse " (4132 "Prince Ivan") ", but could not awaken " (4132 "him") ". "
         (t104 "" (4279 "The dragon") "was nearing the threshold . "
         (t105 "" (4151 "She") "wept , but still could not awaken " (4132 "Prince Ivan") ". "
         (t106 "" (4279 "The dragon") "began to crawl close , ready to snatch " (4132 "Prince Ivan") ", but still " (4132 "he") "slept . "
         (t107 "" (4151 "Princess Martha") "had a penknife , and with it " (4151 "she") "cut " (4132 "Prince Ivan") "'s cheek . "
         (t108 "" (4132 "He") "woke , jumped up , and began to shout insults at " (4279 "the dragon") ". "
         (t109 "Out of nowhere appeared " (4127 "the little peasant all made of copper, with iron hands and a steel head") "" (4127 "the little peasant all made of copper, with iron hands and a steel head") "and " (4127 "he") "gripped " (4279 "the dragon") "; the two together cut off all his heads , cast them into the water , and left . "
         (t110 "" (4241 "The nobleman") "was happier than ever , came rushing out of the woods , went home to his kingdom , and began to press " (4143 "the king") "to celebrate the wedding . "
         (t111 "" (4151 "Princess Martha") "refused . "
         (t112 "' Wait a little while , let " (4151 "me") "recover , ' " (4151 "she") "said . "
         (t113 "' " (4151 "I") "was terribly frightened . ' "
         (t114 "Again " (4222 "the little man no bigger than a nail, with a beard a cubit long") "a beard a cubit long , brought a letter . "
         (t115 "" (4225 "The Water King") "demanded " (4132 "the dragon's slayer") "" (4132 "the dragon's slayer") ""
         (t116 "" (4241 "The nobleman") "did not feel like going to " (4225 "the Water King") ", but there was nothing that " (4241 "he") "could do . "
         (t117 "" (4241 "He") "was ordered to go there . "
         (t118 "A ship was rigged out and " (4303 "they") "set sail ( " (4132 "Prince Ivan") "was now serving in " (4304 "the fleet") ", and somehow happened to be on this ship ) . "
         (t119 "" (4303 "They") "were sailing along briskly when a ship came toward " (4303 "them") ". "
         (t120 "It flew like a bird and from it came cries as it rushed by : ' " (4241 "The culprit") "! "
         (t121 "The culprit ! ' "
         (t122 "" (4303 "They") "sailed on a little farther and met another ship , and again cries came from it : ' The culprit ! "
         (t123 "The culprit ! ' "
         (t124 "" (4132 "Prince Ivan") "pointed at " (4241 "the nobleman") "; " (4241 "he") "was thrashed and thrashed until " (4241 "he") "was half dead . "
         (t125 "The ship went by . "
         (t126 "Now " (4303 "they") "came to the Water King . "
         (t127 "" (4225 "He") "ordered that a bath of iron or steel be heated red hot and " (4241 "the culprit") "put in it . "
         (t128 "" (4241 "The nobleman") "was terrified his heart went into his boots - " (4315 "little father death") "was coming ! "
         (t129 "But " (4316 "one man on the ship") "the ship had become attached to " (4132 "Prince Ivan") "and served " (4132 "him") "faithfully , realizing that " (4132 "he") "was not of lowly birth . "
         (t130 "" (4132 "Prince Ivan") "sent " (4316 "him") ", saying : ' Do " (4316 "you") "go and sit in that bath . ' "
         (t131 "" (4316 "He") "went at once , and , wonder of wonders , nothing happened to " (4316 "him") "; " (4316 "he") "came back unharmed . "
         (t132 "Again " (4241 "the culprit") "was sent for , this time to be brought before " (4225 "the Water King himself") ". "
         (t133 "" (4225 "The Water King") "abused " (4316 "him") "roundly , thrashed " (4316 "him") ", and had " (4316 "him") "driven out . "
         (t134 "Then " (4303 "they all") "went home . "
         (t135 "Upon his return " (4241 "the nobleman") "began to boast even louder than before . "
         (t136 "" (4241 "He") "did not leave the " (4143 "king") "'s side for a moment , so impatient was " (4241 "he") "to have the wedding celebrated . "
         (t137 "" (4143 "The king") "agreed , and a day was set for the nuptials . "
         (t138 "Now " (4241 "the nobleman") "was very proud - so proud , " (4323 "no one") "dared to touch " (4241 "him") "or come near " (4241 "him") "! "
         (t139 "But the princess said to her " (4143 "her father") ": ' " (4143 "Father") ", command " (4324 "all the soldiers") "to assemble ; " (4151 "I") "want to look at " (4324 "them") ". ' "
         (t140 "Straightway " (4324 "the soldiers") "were assembled . "
         (t141 "" (4151 "Princess Martha") "reviewed " (4324 "them all") ". "
         (t142 "When " (4151 "she") "came to Prince Ivan , " (4151 "she") "glanced at his cheek and saw the scar " (4151 "she") "had made when " (4151 "she") "cut " (4132 "him") "with her penknife . "
         (t143 "" (4151 "She") "took " (4132 "him") "by the hand and led " (4132 "him") "to her father . "
         (t144 "' Here is " (4132 "the man who rescued me from the dragon") "" (4132 "the man who rescued me from the dragon") ", ' " (4151 "she") "said . "
         (t145 "' " (4151 "I") "did not know who " (4132 "he") "was , but now " (4151 "I") "recognize " (4132 "him") "by the scar on his cheek . "
         (t146 "The nobleman just sat in the woods with his " (4282 "his soldiers") ". ' "
         (t147 "" (4324 "All the soldiers") "were asked whether " (4324 "they") "had sat in the woods while " (4279 "the dragon") "was slain , and " (4324 "they") "answered : ' That is the truth , " (4143 "Your Royal Majesty") "! ' "
         (t148 "" (4241 "The nobleman") "was half dead from shame . "
         (t149 "" (4241 "He") "was disgraced and banished ; but " (4132 "Prince Ivan") "married " (4151 "Princess Martha") ", and they began to live and chew bread together . "

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)
         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m4132 :type MA)
           (m4126 :type MA)
           (m4127 :type MA)
         )
         (:expressions
         )
       )
       (phase2
         (:entities
           (m4225 :type MB)
           (m4230 :type MA)
           (m4231 :type MB)
           (m4236 :type GR)
           (m4238 :type GR)
           (m4240 :type GR)
           (m4241 :type MA)
           (m4242 :type GR)
           (m4126 :type MA)
           (m4127 :type MA)
           (m4256 :type MB)
           (m4258 :type GR)
           (m4132 :type MA)
           (m4261 :type GR)
           (m4262 :type GR)
           (m4265 :type GR)
           (m4143 :type MA)
           (m4147 :type MA)
           (m4148 :type MA)
           (m4149 :type MA)
           (m4151 :type FE)
           (m4154 :type GR)
           (m4288 :type GR)
           (m4164 :type FE)
           (m4279 :type MB)
           (m4175 :type FE)
           (m4182 :type FE)
           (m4260 :type MA)
           (m4282 :type GR)
           (m4194 :type GR)
           (m4196 :type MB)
           (m4197 :type GR)
           (m4201 :type GR)
           (m4206 :type GR)
           (m4209 :type MA)
           (m4212 :type MA)
           (m4218 :type GR)
           (m4222 :type MB)
         )
         (:expressions
         )
       )
       (phase3
         (:entities
           (m4225 :type MB)
           (m4230 :type MA)
           (m4231 :type MB)
           (m4236 :type GR)
           (m4238 :type GR)
           (m4240 :type GR)
           (m4241 :type MA)
           (m4242 :type GR)
           (m4126 :type MA)
           (m4127 :type MA)
           (m4256 :type MB)
           (m4258 :type GR)
           (m4315 :type MB)
           (m4132 :type MA)
           (m4261 :type GR)
           (m4262 :type GR)
           (m4265 :type GR)
           (m4143 :type MA)
           (m4147 :type MA)
           (m4148 :type MA)
           (m4149 :type MA)
           (m4151 :type FE)
           (m4154 :type GR)
           (m4288 :type GR)
           (m4164 :type FE)
           (m4324 :type GR)
           (m4279 :type MB)
           (m4175 :type FE)
           (m4304 :type GR)
           (m4182 :type FE)
           (m4260 :type MA)
           (m4303 :type GR)
           (m4316 :type MA)
           (m4282 :type GR)
           (m4194 :type GR)
           (m4323 :type GR)
           (m4196 :type MB)
           (m4197 :type GR)
           (m4201 :type GR)
           (m4206 :type GR)
           (m4209 :type MA)
           (m4212 :type MA)
           (m4218 :type GR)
           (m4222 :type MB)
         )
         (:expressions
         )
       )

     )
   )
)
    