
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-17
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1 t2 t3 t4))
         (phase2 (:s  t5 t6 t7))

       )
       (:templates
         ;; For many years a certain tsar had kept under lock and key a little peasant all made of copper, with iron hands and a steel head - a cunning man, a wizard of a man!
         ;; Prince Ivan, the tsar's son who was still a little boy, walked by the prison.
         ;; The old man called him and began to beg: "Prince Ivan, please give me a drink!"
         ;; Prince Ivan did not know anything yet, he was very little, so he drew some water and gave it to him; with the help of the water the old man vanished from the prison.
         ;; The tsar's word was law.
         ;; Prince Ivan was banished and he left home not knowing where to go.
         ;; He walked for a long time; at last he arrived in another kingdom, presented himself to the king, and asked to be taken into his service.

         (t1 "For many years " (STORY17-m3362 "a certain tsar") " had kept under lock and key " (STORY17-m3363 "a little peasant all made of copper, with iron hands and a steel head - a cunning man, a wizard of a man") " ! ")
         (t2 "" (STORY17-m3368 "Prince Ivan, the tsar's son who was still a little boy") " , walked by the prison . ")
         (t3 "" (STORY17-m3371 "The old man") " called " (STORY17-m3372 "him") " and began to beg : ' Prince Ivan , please give " (STORY17-m3374 "me") " a drink ! ' ")
         (t4 "" (STORY17-m3376 "Prince Ivan") " did not know " (STORY17-m3378 "anything") " yet , " (STORY17-m3379 "he") " was very little , so " (STORY17-m3380 "he") " drew some water and gave it to him ; with the help of the water " (STORY17-m3386 "the old man") " vanished from the prison . ")
         (t5 "The " (STORY17-m3393 "tsar") " 's word was law . ")
         (t6 "Prince Ivan was banished and " (STORY17-m3396 "he") " left home not knowing where to go . ")
         (t7 "" (STORY17-m3398 "He") " walked for a long time ; at last " (STORY17-m3400 "he") " arrived in another kingdom , presented " (STORY17-m3402 "himself") " to the king , and asked to be taken into his service . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY17-m3362 :type MA)
           (STORY17-m3363 :type MA)
           (STORY17-m3368 :type MA)
           (STORY17-m3371 :type MA)
           (STORY17-m3372 :type MA)
           (STORY17-m3374 :type MA)
           (STORY17-m3376 :type MA)
           (STORY17-m3378 :type MA)
           (STORY17-m3379 :type MA)
           (STORY17-m3380 :type MA)
           (STORY17-m3386 :type MA)
         )
         (:expressions
           ((levin-13-1 STORY17-m3371 STORY17-m3374) :name STORY17-VERB1)
           ((levin-29-5 STORY17-m3376 STORY17-m3378) :name STORY17-VERB2)
         )
       )
       (phase2
         (:entities
           (STORY17-m3393 :type MA)
           (STORY17-m3362 :type MA)
           (STORY17-m3363 :type MA)
           (STORY17-m3396 :type MA)
           (STORY17-m3398 :type MA)
           (STORY17-m3368 :type MA)
           (STORY17-m3402 :type MA)
           (STORY17-m3371 :type MA)
           (STORY17-m3372 :type MA)
           (STORY17-m3374 :type MA)
           (STORY17-m3376 :type MA)
           (STORY17-m3400 :type MA)
           (STORY17-m3378 :type MA)
           (STORY17-m3379 :type MA)
           (STORY17-m3380 :type MA)
           (STORY17-m3386 :type MA)
         )
         (:expressions
         )
       )

     )
   )
)
    