
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-1
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13))

       )
       (:templates
         ;; A dragon appeared near Kiev; he took heavy tribute from the people - a lovely maiden from every house, whom he then devoured.
         ;; Finally, it was the fate of the tsar's daughter to go to the dragon.
         ;; He seized her and dragged her to his lair but did not devour her, because she was a beauty.
         ;; Instead, he took her to wife.
         ;; Whenever he went out, he boarded up his house to prevent the princess from escaping.
         ;; The princess had a little dog that had followed her to the dragon's lair.
         ;; The princess often wrote to her father and mother.
         ;; She would attach her letter to the dog's neck, and the dog would take it to them and even bring back the answer.
         ;; One day the tsar and tsarina wrote to their daughter, asking her to find out who in this world was stronger than the dragon.
         ;; The princess became kindlier toward the dragon and began to question him.
         ;; For a long time he did not answer, but one day he said inadvertently that a tanner in the city of Kiev was stronger than he.
         ;; When the princess heard this, she wrote her father to find Nikita the Tanner in Kiev and to send him to deliver her from captivity.
         ;; Upon receiving this letter, the tsar went in person to beg Nikita the Tanner to free his land from the wicked dragon and rescue the princess.

         (t1 "" (1084 "A dragon") "appeared near Kiev ; " (1084 "he") "took heavy tribute from the people - " (1088 "a lovely maiden from every house, whom he then devoured") "" (1084 "he") "" (1088 "a lovely maiden from every house, whom he then devoured") ""
         (t2 "Finally , it was the fate of " (1091 "the tsar's daughter") "" (1091 "the tsar's daughter") "to the dragon . "
         (t3 "" (1084 "He") "seized her and dragged " (1091 "her") "to his lair but did not devour her , because " (1091 "she") "was a beauty . "
         (t4 "Instead , " (1084 "he") "took " (1091 "her") "to wife . "
         (t5 "Whenever " (1084 "he") "went out , " (1084 "he") "boarded up his house to prevent " (1091 "the princess") "from escaping . "
         (t6 "" (1091 "The princess") "had a little dog that had followed her to the " (1084 "dragon") "'s lair . "
         (t7 "" (1091 "The princess") "often wrote to her " (1092 "father") "and mother . "
         (t8 "" (1091 "She") "would attach her letter to the dog 's neck , and the dog would take it to them and even bring back the answer . "
         (t9 "One day the " (1092 "tsar") "and tsarina wrote to their " (1091 "their daughter") ", asking her to find out who in this world was stronger than " (1084 "the dragon") ". "
         (t10 "" (1091 "The princess") "became kindlier toward " (1084 "the dragon") "and began to question " (1084 "him") ". "
         (t11 "For a long time " (1084 "he") "did not answer , but one day " (1084 "he") "said inadvertently that " (1106 "a tanner in the city of Kiev") "the city of Kiev was stronger than " (1084 "he") ". "
         (t12 "When " (1091 "the princess") "heard this , " (1091 "she") "wrote her " (1092 "her father") "to find " (1106 "Nikita the Tanner") "in Kiev and to send " (1106 "him") "to deliver her from captivity . "
         (t13 "Upon receiving this letter , " (1092 "the tsar") "went in person to beg " (1106 "Nikita the Tanner") "to free his land from " (1084 "the wicked dragon") "and rescue " (1091 "the princess") ". "

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)
         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m1088 :type FE)
           (m1092 :type MA)
           (m1106 :type MA)
           (m1091 :type FE)
           (m1084 :type MB)
         )
         (:expressions
         )
       )

     )
   )
)
    