
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-6
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 t30 t31 t32 t33 t34 t35 t36 t37 t38 t39 t40 t41 t42 t43 t44 t45 t46 t47 t48))

       )
       (:templates
         ;; In a certain village there lived a wealthy peasant and his wife.
         ;; One day the wife went to the forest for mushrooms, lost her way, and stumbled into a bear's den.
         ;; The bear kept her with him, and after some time, a long time or a short time, she had a son by him.
         ;; This son was a man down to the waist and a bear below the waist; his mother called him Ivanko the Bearlet.
         ;; Years went by, and when Ivan grew up he wanted to go away with his mother and live with the peasants in the village; they waited until the bear went to a beehive, made ready, and ran away.
         ;; They ran and ran and finally came to their own village.
         ;; The peasant saw his wife and was overjoyed - he had given up hope that she would ever return.
         ;; Then he beheld her son and asked: "And who is this freak?"
         ;; His wife told him all that had happened, how she had lived in the bear's den and had a son by him and that this son was human to the waist and a bear from the waist down.
         ;; "Well, Bearlet," said the peasant, "go to the back yard and slaughter a sheep; we must make dinner for you."
         ;; "And which one shall I slaughter?"
         ;; "Whichever one stares at you."
         ;; Ivanko the Bearlet took a knife, went out to the yard, and called the sheep; all of them began to stare at him.
         ;; He forthwith slaughtered them all, skinned them, and went to ask the peasant where he should store the skins and the meat.
         ;; "What's this?" yelled the peasant.
         ;; "I told you to slaughter one sheep, and you have slaughtered them all!"
         ;; "No, father, you told me to slaughter whichever one stared at me; but when I came out into the yard all of them, without exception, began to stare at me."
         ;; "You certainly are a clever fellow.
         ;; Take the meat and skins into the barn, and at night guard the door against thieves and dogs."
         ;; "Very well, I will guard it."
         ;; It so happened that on that night a storm broke and the rain fell in buckets.
         ;; Ivanko the Bearlet broke the door off the barn, took it into the bath house, and spent the night there.
         ;; Thieves took advantage of the darkness; they found the barn open and without a guard, so they took whatever they pleased.
         ;; Next morning the peasant arose, went to see whether everything was in order, and found that nothing was left: what the thieves had not taken, the dogs had eaten up.
         ;; He looked for the guard, found him in the bath house, and began to chide him even more severely than the first time.
         ;; "But, father, it is not my fault," said Ivanko.
         ;; "You yourself told me to guard the door, and I did guard it.
         ;; Here it is; the thieves did not steal it, nor did the dogs eat it up."
         ;; "What can I do with this fool?" thought the peasant to himself.
         ;; "If this goes on for a month or two, he will ruin me completely.
         ;; I wonder how I can get rid of him."
         ;; Then he hit upon an idea; the next day he sent Ivanko to the lake and told him to wind ropes of sand.
         ;; In that lake dwelt many devils, and the peasant hoped that they would drag him into the water.
         ;; Ivanko the Bearlet went to the lake, sat on the shore, and began to wind ropes of sand.
         ;; Suddenly a little devil jumped out of the water and asked: "What are you doing here, Bearlet?"
         ;; "Can't you see?
         ;; I'm winding ropes; I want to thrash the lake and torment you devils, because you live in our lake but do not pay any rent."
         ;; "Wait a while, Bearlet, I'll run and tell my grandfather," said the little devil, and - flop! - he jumped into the water.
         ;; Five minutes later he was out again and said: "Grandfather said that if you can run faster than I, we'll pay the rent; if not, he told me to drag you down into the lake."
         ;; "Aren't you a nimble fellow!" said Ivanko.
         ;; "But you cannot hope to run faster than I.
         ;; Why, I have a grandson who was born only yesterday, and even he can outrun you.
         ;; Do you want to race with him?"
         ;; "What grandson?"
         ;; "He is lying there behind a bush," said the Bearlet, and cried to a hare, "Hey, hare, do not fail me!"
         ;; The hare darted off into the open field like mad and in a trice vanished from sight; the devil rushed after him, but it was of no use - he was half a verst behind.
         ;; "Now, if you wish," said Ivanko, "race with me.
         ;; But on one condition - if you lag behind, I will kill you."

         (t1 "In a certain village there lived " (4174 "a wealthy peasant") "and his wife . "
         (t2 "One day " (4175 "the wife") "went to the forest for mushrooms , lost her way , and stumbled into a " (4181 "bear") "'s den . "
         (t3 "" (4181 "The bear") "kept " (4175 "her") "with him , and after some time , a long time or a short time , " (4175 "she") "had a son by " (4181 "him") ". "
         (t4 "This son was " (4183 "a man down to the waist and a bear below the waist") "" (4183 "a man down to the waist and a bear below the waist") "" (4183 "him") "Ivanko the Bearlet . "
         (t5 "Years went by , and when " (4183 "Ivan") "grew up " (4183 "he") "wanted to go away with his " (4175 "his mother") "and live with " (4186 "the peasants") "in the village ; they waited until " (4181 "the bear") "went to a beehive , made ready , and ran away . "
         (t6 "They ran and ran and finally came to their own village . "
         (t7 "" (4174 "The peasant") "saw his " (4175 "his wife") "and was overjoyed - " (4174 "he") "had given up hope that " (4175 "she") "would ever return . "
         (t8 "Then " (4174 "he") "beheld her " (4183 "her son") "and asked : ' And who is " (4183 "this freak") "? ' "
         (t9 "His " (4175 "His wife") "told him all that had happened , how " (4175 "she") "had lived in the " (4181 "bear") "'s den and had " (4183 "a son") "by him and that " (4183 "this son") "was human to the waist and a bear from the waist down . "
         (t10 "' Well , " (4183 "Bearlet") ", ' said " (4174 "the peasant") ", ' go to the back yard and slaughter a sheep ; we must make dinner for " (4183 "you") ". ' "
         (t11 "' And which one shall " (4183 "I") "slaughter ? ' "
         (t12 "' Whichever one stares at " (4183 "you") ". ' "
         (t13 "" (4183 "Ivanko the Bearlet") "took a knife , went out to the yard , and called " (4195 "the sheep") "; " (4195 "all of them") "began to stare at " (4183 "him") ". "
         (t14 "" (4183 "He") "forthwith slaughtered " (4195 "them all") ", skinned " (4195 "them") ", and went to ask the peasant where " (4183 "he") "should store the skins and the meat . "
         (t15 "' What 's this ? ' yelled " (4174 "the peasant") ". "
         (t16 "' " (4174 "I") "told " (4183 "you") "to slaughter one sheep , and " (4183 "you") "have slaughtered " (4195 "them all") "! ' "
         (t17 "' No , father , " (4174 "you") "told " (4183 "me") "to slaughter whichever one stared at " (4183 "me") "; but when " (4183 "I") "came out into the yard " (4195 "all of them, without exception") ", began to stare at " (4183 "me") ". ' "
         (t18 "' " (4183 "You") "certainly are a clever fellow . "
         (t19 "Take the meat and skins into the barn , and at night guard the door against " (4204 "thieves") "and dogs . ' "
         (t20 "' Very well , " (4183 "I") "will guard it . ' "
         (t21 "It so happened that on that night a storm broke and the rain fell in buckets . "
         (t22 "" (4183 "Ivanko the Bearlet") "broke the door off the barn , took it into the bath house , and spent the night there . "
         (t23 "" (4204 "Thieves") "took advantage of the darkness ; " (4204 "they") "found the barn open and without " (4183 "a guard") ", so " (4204 "they") "took whatever " (4204 "they") "pleased . "
         (t24 "Next morning " (4174 "the peasant") "arose , went to see whether everything was in order , and found that nothing was left : what " (4204 "the thieves") "had not taken , the dogs had eaten up . "
         (t25 "" (4174 "He") "looked for " (4183 "the guard") ", found " (4183 "him") "in the bath house , and began to chide " (4183 "him") "even more severely than the first time . "
         (t26 "' But , " (4174 "father") ", it is not my fault , ' said " (4183 "Ivanko") ". "
         (t27 "' " (4174 "You yourself") "told " (4183 "me") "to guard the door , and " (4183 "I") "did guard it . "
         (t28 "Here it is ; " (4204 "the thieves") "did not steal it , nor did the dogs eat it up . ' "
         (t29 "' What can " (4174 "I") "do with " (4183 "this fool") "? ' thought " (4174 "the peasant") "to " (4174 "himself") ". "
         (t30 "' If this goes on for a month or two , " (4183 "he") "will ruin " (4174 "me") "completely . "
         (t31 "" (4174 "I") "wonder how " (4174 "I") "can get rid of " (4183 "him") ". ' "
         (t32 "Then " (4174 "he") "hit upon an idea ; the next day " (4174 "he") "sent " (4183 "Ivanko") "to the lake and told " (4183 "him") "to wind ropes of sand . "
         (t33 "In that lake dwelt " (4219 "many devils") ", and " (4174 "the peasant") "hoped that " (4219 "they") "would drag " (4183 "him") "into the water . "
         (t34 "" (4183 "Ivanko the Bearlet") "went to the lake , sat on the shore , and began to wind ropes of sand . "
         (t35 "Suddenly " (4221 "a little devil") "jumped out of the water and asked : ' What are " (4183 "you") "doing here , " (4183 "Bearlet") "? ' "
         (t36 "' Ca n't " (4221 "you") "see ? "
         (t37 "" (4183 "I") "'m winding ropes ; " (4183 "I") "want to thrash the lake and torment " (4219 "you devils") ", because " (4219 "you") "live in our lake but do not pay any rent . ' "
         (t38 "' Wait a while , " (4183 "Bearlet") ", " (4221 "I") "'ll run and tell my " (4224 "my grandfather") ", ' said " (4221 "the little devil") ", and - flop ! - " (4221 "he") "jumped into the water . "
         (t39 "Five minutes later " (4221 "he") "was out again and said : ' " (4224 "Grandfather") "said that if " (4183 "you") "can run faster than " (4221 "I") ", " (4219 "we") "'ll pay the rent ; if not , " (4224 "he") "told " (4221 "me") "to drag " (4183 "you") "down into the lake . ' "
         (t40 "' Are n't " (4221 "you") "" (4221 "a nimble fellow") "! ' said " (4183 "Ivanko") ". "
         (t41 "' But " (4221 "you") "can not hope to run faster than " (4183 "I") ". "
         (t42 "Why , " (4183 "I") "have " (4226 "a grandson who was born only yesterday") "yesterday , and even " (4226 "he") "can outrun " (4221 "you") ". "
         (t43 "Do " (4221 "you") "want to race with " (4226 "him") "? ' "
         (t44 "' What grandson ? ' "
         (t45 "' " (4226 "He") "is lying there behind a bush , ' said " (4183 "the Bearlet") ", and cried to a hare , ' Hey , hare , do not fail " (4183 "me") "! ' "
         (t46 "The hare darted off into the open field like mad and in a trice vanished from sight ; " (4221 "the devil") "rushed after him , but it was of no use - " (4221 "he") "was half a verst behind . "
         (t47 "' Now , if " (4221 "you") "wish , ' said " (4183 "Ivanko") ", ' race with " (4183 "me") ". "
         (t48 "But on one condition - if " (4221 "you") "lag behind , " (4183 "I") "will kill " (4221 "you") ". ' "

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)
         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m4224 :type MB)
           (m4226 :type MA)
           (m4195 :type GR)
           (m4204 :type GR)
           (m4174 :type MA)
           (m4175 :type FE)
           (m4181 :type AA)
           (m4183 :type MA)
           (m4186 :type GR)
           (m4219 :type GR)
           (m4221 :type MB)
         )
         (:expressions
           ((verb-lived m4174 m-1) :name E1)
           ((verb-went m4175 m-1) :name E2)
           ((verb-lost m4175 m-1) :name E3)
           ((verb-stumbled m4175 m4181) :name E4)
           ((verb-kept m4181 m4175) :name E5)
           ((verb-had m4175 m4181) :name E6)
           ((verb-was m-1 m4183) :name E7)
           ((verb-was m-1 m4183) :name E8)
           ((verb-called m4175 m4183) :name E9)
           ((verb-grew m-1 m4183) :name E10)
           ((verb-wanted m4183 m4186) :name E11)
           ((verb-go m4183 m4175) :name E12)
           ((verb-live m4183 m4186) :name E13)
           ((verb-waited m-1 m4181) :name E14)
           ((verb-went m4181 m-1) :name E15)
           ((verb-saw m4174 m4175) :name E16)
           ((verb-was m-1 m4174) :name E17)
           ((verb-given m4174 m4175) :name E18)
           ((verb-return m-1 m4175) :name E19)
           ((verb-beheld m4174 m4183) :name E20)
           ((verb-asked m4174 m4183) :name E21)
           ((verb-is m-1 m4183) :name E22)
           ((verb-told m4175 m4175) :name E23)
           ((verb-lived m4175 m4181) :name E24)
           ((verb-had m4175 m4183) :name E25)
           ((verb-was m-1 m4183) :name E26)
           ((verb-was m-1 m4183) :name E27)
           ((verb-go m4183 m-1) :name E28)
           ((verb-said m4174 m4183) :name E29)
           ((verb-slaughter m4183 m-1) :name E30)
           ((verb-make m-1 m4183) :name E31)
           ((verb-slaughter m4183 m-1) :name E32)
           ((verb-stares m-1 m4183) :name E33)
           ((verb-took m4183 m-1) :name E34)
           ((verb-went m4183 m-1) :name E35)
           ((verb-called m4183 m4195) :name E36)
           ((verb-began m4195 m4183) :name E37)
           ((verb-stare m4195 m4183) :name E38)
           ((verb-slaughtered m4183 m4195) :name E39)
           ((verb-skinned m4183 m4195) :name E40)
           ((verb-went m4183 m4183) :name E41)
           ((verb-ask m4183 m4183) :name E42)
           ((verb-store m4183 m-1) :name E43)
           ((verb-yelled m4174 m-1) :name E44)
           ((verb-told m4174 m4183) :name E45)
           ((verb-slaughter m4183 m-1) :name E46)
           ((verb-slaughtered m4183 m4195) :name E47)
           ((verb-told m4174 m4183) :name E48)
           ((verb-slaughter m4183 m4183) :name E49)
           ((verb-stared m-1 m4183) :name E50)
           ((verb-came m-1 m4183) :name E51)
           ((verb-began m4195 m4183) :name E52)
           ((verb-stare m4195 m4183) :name E53)
           ((verb-are m-1 m4183) :name E54)
           ((verb-guard m-1 m4204) :name E55)
           ((verb-guard m4183 m-1) :name E56)
           ((verb-broke m4183 m-1) :name E57)
           ((verb-took m4183 m-1) :name E58)
           ((verb-spent m4183 m-1) :name E59)
           ((verb-took m4204 m-1) :name E60)
           ((verb-found m4204 m4183) :name E61)
           ((verb-took m4204 m4204) :name E62)
           ((verb-pleased m4204 m-1) :name E63)
           ((verb-arose m-1 m4174) :name E64)
           ((verb-went m4174 m-1) :name E65)
           ((verb-found m4174 m-1) :name E66)
           ((verb-taken m4204 m-1) :name E67)
           ((verb-eaten m-1 m4204) :name E68)
           ((verb-looked m4174 m4183) :name E69)
           ((verb-found m4174 m4183) :name E70)
           ((verb-began m4174 m4183) :name E71)
           ((verb-chide m4174 m4183) :name E72)
           ((verb-is m-1 m4174) :name E73)
           ((verb-said m4183 m4174) :name E74)
           ((verb-told m4174 m4183) :name E75)
           ((verb-guard m4183 m-1) :name E76)
           ((verb-guard m4183 m-1) :name E77)
           ((verb-steal m4204 m-1) :name E78)
           ((verb-do m4174 m4183) :name E79)
           ((verb-thought m4174 m4174) :name E80)
           ((verb-ruin m4183 m4174) :name E81)
           ((verb-wonder m4174 m4183) :name E82)
           ((verb-get m-1 m4183) :name E83)
           ((verb-rid m4174 m4183) :name E84)
           ((verb-hit m4174 m-1) :name E85)
           ((verb-sent m4174 m4183) :name E86)
           ((verb-told m4174 m4183) :name E87)
           ((verb-wind m4183 m-1) :name E88)
           ((verb-dwelt m4219 m-1) :name E89)
           ((verb-hoped m4174 m4219) :name E90)
           ((verb-drag m4219 m4183) :name E91)
           ((verb-went m4183 m-1) :name E92)
           ((verb-sat m-1 m4183) :name E93)
           ((verb-wind m4183 m-1) :name E94)
           ((verb-began m4183 m-1) :name E95)
           ((verb-jumped m4221 m-1) :name E96)
           ((verb-asked m4221 m4183) :name E97)
           ((verb-doing m4183 m4183) :name E98)
           ((verb-see m4221 m-1) :name E99)
           ((verb-winding m4183 m-1) :name E100)
           ((verb-thrash m4183 m-1) :name E101)
           ((verb-torment m4183 m4219) :name E102)
           ((verb-want m4183 m4219) :name E103)
           ((verb-live m4219 m-1) :name E104)
           ((verb-pay m4219 m-1) :name E105)
           ((verb-Wait m-1 m4183) :name E106)
           ((verb-said m4221 m4183) :name E107)
           ((verb-run m4221 m-1) :name E108)
           ((verb-tell m4221 m4224) :name E109)
           ((verb-jumped m4221 m-1) :name E110)
           ((verb-was m-1 m4221) :name E111)
           ((verb-said m4221 m4224) :name E112)
           ((verb-said m4224 m4224) :name E113)
           ((verb-run m4183 m4221) :name E114)
           ((verb-pay m4219 m-1) :name E115)
           ((verb-told m4224 m4183) :name E116)
           ((verb-drag m4221 m4183) :name E117)
           ((verb-Are m-1 m4221) :name E118)
           ((verb-said m4183 m4221) :name E119)
           ((verb-hope m4221 m4183) :name E120)
           ((verb-run m4221 m4183) :name E121)
           ((verb-have m4183 m4226) :name E122)
           ((verb-born m-1 m4226) :name E123)
           ((verb-outrun m4226 m4221) :name E124)
           ((verb-want m4221 m4226) :name E125)
           ((verb-race m4221 m4226) :name E126)
           ((verb-lying m-1 m4226) :name E127)
           ((verb-said m4183 m4226) :name E128)
           ((verb-cried m4183 m4183) :name E129)
           ((verb-fail m-1 m4183) :name E130)
           ((verb-rushed m-1 m4221) :name E131)
           ((verb-was m-1 m4221) :name E132)
           ((verb-wish m4221 m4183) :name E133)
           ((verb-said m4183 m4183) :name E134)
           ((verb-race m4221 m4183) :name E135)
           ((verb-lag m4221 m-1) :name E136)
           ((verb-kill m4183 m4221) :name E137)
         )
       )

     )
   )
)
    