
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-9
     (:discourse
       (:clauses
         (c0 (:s phase1))
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 t22 t23 t24 t25 t26))

       )
       (:templates
         ;; There once lived an old couple who had one son called Ivashko; one can tell how fond they were of him!
         ;; Well, one day, Ivashko said to his father and mother: "I'll go out fishing if you'll let me."
         ;; "What are you thinking about!
         ;; you're still very small; suppose you get drowned, what good will there be in that?"
         ;; "No, no, I shan't get drowned.
         ;; I'll catch you some fish; do let me go!"
         ;; So his mother put a white shirt on him, tied a red girdle round him, and let him go.
         ;; Out in a boat he sat and said: Canoe, canoe, float a little farther,Canoe, canoe, float a little farther!
         ;; Then the canoe floated on farther and farther, and Ivashko began to fish.
         ;; When some little time had passed by, the old woman hobbled down to the river side and called to her son:Ivashechko, Ivashechko, my boy,Float up, float up unto the waterside;I bring thee food and drink.
         ;; And Ivashko said:Canoe, canoe, float to the waterside;That is my mother calling me.
         ;; The boat floated to the shore: the woman took the fish, gave her boy food and drink, changed his shirt for him and his girdle, and sent him back to his fishing.
         ;; Again he sat in his boat and said:Canoe, canoe, float a little farther,Canoe, canoe, float a little farther.
         ;; Then the canoe floated on farther and farther, and Ivashko began to fish.
         ;; After a little time had passed by, the old man also hobbled down to the bank and called to his son:Ivashechko, Ivashechko, my boy,Float up, float up, onto the waterside;I bring thee food and drink.
         ;; And Ivashko replied:Canoe, canoe, float to the waterside;That is my father calling me.
         ;; The canoe floated to the shore.
         ;; The old man took the fish, gave his boy food and drink, changed his shirt for him and his girdle, and sent him back to his fishing.
         ;; Now a certain witch had heard what Ivashko's parents had cried aloud to him, and she longed to get hold of the boy.
         ;; So she went down to the bank and cried with a hoarse voice: Ivashechko, Ivashechko, my boy,Float up, float up, onto the watersideI bring thee food and drink.
         ;; Ivashko perceived that the voice was not his mother's, but was that of a witch, and he sang:Canoe, canoe, float a little farther,Canoe, canoe, float a little farther;That is not my mother, but a witch who calls me.
         ;; The witch saw that she must call Ivashko with just such a voice as his mother had.
         ;; So she hastened to a smith and said to him: "Smith, smith make me just such a thin little voice as Ivashko's mother has: if you don't, I'll eat you."
         ;; So the smith forged her a little voice just like Ivashko's mother's.
         ;; Then the witch went down by night to the shore and sang:Ivashechko, Ivashechko, my boy,Float up, float up, unto the waterside;I bring thee food and drink.
         ;; Ivashko came, and she took the fish, and seized the boy and carried him home with her.

         (t1 "There once lived " (STORY9-m4502 "an old couple who had one son") " " (STORY9-m4503 "one son called Ivashko") " ; one can tell how fond " (STORY9-m4504 "they") " were of " (STORY9-m4505 "him") " ! ")
         (t2 "Well , one day , " (STORY9-m4507 "Ivashko") " said to his father and mother : ' " (STORY9-m4512 "I") " 'll go out fishing if " (STORY9-m4514 "you") " 'll let " (STORY9-m4515 "me") " . ' ")
         (t3 "' What are " (STORY9-m4516 "you") " thinking about ! ")
         (t4 "" (STORY9-m4517 "you") " 're still very small ; suppose " (STORY9-m4518 "you") " get drowned , what good will there be in that ? ' ")
         (t5 "' No , no , " (STORY9-m4521 "I") " sha n't get drowned . ")
         (t6 "" (STORY9-m4523 "I") " 'll catch you some fish ; do let " (STORY9-m4527 "me") " go ! ' ")
         (t7 "So his " (STORY9-m4529 "his mother") " put a white shirt on " (STORY9-m4531 "him") " , tied a red girdle round " (STORY9-m4533 "him") " , and let " (STORY9-m4534 "him") " go . ")
         (t8 "Out in a boat " (STORY9-m4536 "he") " sat and said : Canoe , canoe , float " (STORY9-m4539 "a little farther") " , Canoe , canoe , float " (STORY9-m4542 "a little farther") " ! ")
         (t9 "Then the canoe floated on farther and farther , and " (STORY9-m4544 "Ivashko") " began " (STORY9-m4545 "to fish") " . ")
         (t10 "When some little time had passed by , " (STORY9-m4547 "the old woman") " hobbled down to the river side and called to her " (STORY9-m4550 "her son") " : " (STORY9-m4551 "Ivashechko") " , " (STORY9-m4552 "Ivashechko, my boy") " , Float up , float up unto the waterside ; " (STORY9-m4555 "I") " bring " (STORY9-m4556 "thee") " food and drink . ")
         (t11 "And " (STORY9-m4560 "Ivashko") " said : Canoe , canoe , float to the waterside ; That is my " (STORY9-m4566 "my mother") " calling " (STORY9-m4567 "me") " . ")
         (t12 "The boat floated to the shore : " (STORY9-m4570 "the woman") " took the fish , gave her " (STORY9-m4573 "her boy") " food and drink , changed his shirt for him and his girdle , and sent " (STORY9-m4582 "him") " back to his fishing . ")
         (t13 "Again " (STORY9-m4585 "he") " sat in his boat and said : Canoe , canoe , float " (STORY9-m4590 "a little farther") " , Canoe , canoe , float " (STORY9-m4593 "a little farther") " . ")
         (t14 "Then the canoe floated on farther and farther , and " (STORY9-m4595 "Ivashko") " began " (STORY9-m4596 "to fish") " . ")
         (t15 "After a little time had passed by , " (STORY9-m4598 "the old man") " also hobbled down to the bank and called to his son : " (STORY9-m4602 "Ivashechko") " , " (STORY9-m4603 "Ivashechko, my boy") " , Float up , float up , onto the waterside ; " (STORY9-m4606 "I") " bring " (STORY9-m4607 "thee") " food and drink . ")
         (t16 "And " (STORY9-m4611 "Ivashko") " replied : Canoe , canoe , float to the waterside ; That is my " (STORY9-m4617 "my father") " calling " (STORY9-m4618 "me") " . ")
         (t17 "The canoe floated to the shore . ")
         (t18 "" (STORY9-m4621 "The old man") " took the fish , gave his " (STORY9-m4624 "his boy") " food and drink , changed his shirt for him and his girdle , and sent " (STORY9-m4633 "him") " back to his fishing . ")
         (t19 "Now " (STORY9-m4636 "a certain witch") " had heard what " (STORY9-m4637 "Ivashko") " " (STORY9-m4638 "Ivashko's parents") " had cried aloud to " (STORY9-m4639 "him") " , and " (STORY9-m4640 "she") " longed to get hold of " (STORY9-m4641 "the boy") " . ")
         (t20 "So " (STORY9-m4642 "she") " went down to the bank and cried with a hoarse voice : " (STORY9-m4645 "Ivashechko") " , " (STORY9-m4646 "Ivashechko, my boy") " , Float up , float up , onto the waterside " (STORY9-m4649 "I") " bring " (STORY9-m4650 "thee") " food and drink . ")
         (t21 "" (STORY9-m4654 "Ivashko") " perceived that the voice was not his " (STORY9-m4657 "his mother") " 's , but was " (STORY9-m4659 "that of a witch") " a witch , and " (STORY9-m4661 "he") " sang : Canoe , canoe , float " (STORY9-m4664 "a little farther") " , Canoe , canoe , float " (STORY9-m4667 "a little farther") " ; That is not my " (STORY9-m4670 "my mother") " , but " (STORY9-m4671 "a witch who calls me") " " (STORY9-m4672 "me") " . ")
         (t22 "" (STORY9-m4673 "The witch") " saw that " (STORY9-m4674 "she") " must call " (STORY9-m4675 "Ivashko") " with just such a voice as his " (STORY9-m4678 "his mother") " had . ")
         (t23 "So " (STORY9-m4679 "she") " hastened to a smith and said to him : ' " (STORY9-m4682 "Smith") " , smith make me just such a thin little voice as " (STORY9-m4686 "Ivashko") " 's mother has : if " (STORY9-m4688 "you") " do n't , " (STORY9-VERB23 "" (STORY9-m4689 "I") " 'll eat " (STORY9-m4690 "you") " " ) ". ' ")
         (t24 "So " (STORY9-m4691 "the smith") " forged her a little voice just like Ivashko " (STORY9-m4695 "Ivashko's mother") " 's . ")
         (t25 "Then " (STORY9-m4697 "the witch") " went down by night to the shore and sang : " (STORY9-m4700 "Ivashechko") " , " (STORY9-m4701 "Ivashechko, my boy") " , Float up , float up , unto the waterside ; " (STORY9-m4704 "I") " bring " (STORY9-m4705 "thee") " food and drink . ")
         (t26 "Ivashko came , and " (STORY9-m4710 "she") " took the fish , and seized " (STORY9-m4712 "the boy") " and carried " (STORY9-m4713 "him") " home with her . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY9-m4611 :type MA)
           (STORY9-m4617 :type MA)
           (STORY9-m4618 :type MA)
           (STORY9-m4621 :type MA)
           (STORY9-m4624 :type MA)
           (STORY9-m4633 :type MA)
           (STORY9-m4636 :type MA)
           (STORY9-m4637 :type MA)
           (STORY9-m4638 :type MA)
           (STORY9-m4639 :type MA)
           (STORY9-m4640 :type MA)
           (STORY9-m4641 :type MA)
           (STORY9-m4642 :type MA)
           (STORY9-m4645 :type MA)
           (STORY9-m4646 :type MA)
           (STORY9-m4649 :type MA)
           (STORY9-m4650 :type MA)
           (STORY9-m4654 :type MA)
           (STORY9-m4657 :type MA)
           (STORY9-m4659 :type MA)
           (STORY9-m4661 :type MA)
           (STORY9-m4664 :type MA)
           (STORY9-m4667 :type MA)
           (STORY9-m4670 :type MA)
           (STORY9-m4671 :type MA)
           (STORY9-m4672 :type MA)
           (STORY9-m4673 :type MA)
           (STORY9-m4674 :type MA)
           (STORY9-m4675 :type MA)
           (STORY9-m4678 :type MA)
           (STORY9-m4679 :type MA)
           (STORY9-m4682 :type MA)
           (STORY9-m4686 :type MA)
           (STORY9-m4688 :type MA)
           (STORY9-m4689 :type MA)
           (STORY9-m4690 :type MA)
           (STORY9-m4691 :type MA)
           (STORY9-m4695 :type MA)
           (STORY9-m4697 :type MA)
           (STORY9-m4700 :type MA)
           (STORY9-m4701 :type MA)
           (STORY9-m4704 :type MA)
           (STORY9-m4705 :type MA)
           (STORY9-m4710 :type MA)
           (STORY9-m4712 :type MA)
           (STORY9-m4713 :type MA)
           (STORY9-m4502 :type MA)
           (STORY9-m4503 :type MA)
           (STORY9-m4504 :type MA)
           (STORY9-m4505 :type MA)
           (STORY9-m4507 :type MA)
           (STORY9-m4512 :type MA)
           (STORY9-m4514 :type MA)
           (STORY9-m4515 :type MA)
           (STORY9-m4516 :type MA)
           (STORY9-m4517 :type MA)
           (STORY9-m4518 :type MA)
           (STORY9-m4521 :type MA)
           (STORY9-m4523 :type MA)
           (STORY9-m4527 :type MA)
           (STORY9-m4529 :type MA)
           (STORY9-m4531 :type MA)
           (STORY9-m4533 :type MA)
           (STORY9-m4534 :type MA)
           (STORY9-m4536 :type MA)
           (STORY9-m4539 :type MA)
           (STORY9-m4542 :type MA)
           (STORY9-m4544 :type MA)
           (STORY9-m4545 :type MA)
           (STORY9-m4547 :type MA)
           (STORY9-m4550 :type MA)
           (STORY9-m4551 :type MA)
           (STORY9-m4552 :type MA)
           (STORY9-m4555 :type MA)
           (STORY9-m4556 :type MA)
           (STORY9-m4560 :type MA)
           (STORY9-m4566 :type MA)
           (STORY9-m4567 :type MA)
           (STORY9-m4570 :type MA)
           (STORY9-m4573 :type MA)
           (STORY9-m4582 :type MA)
           (STORY9-m4585 :type MA)
           (STORY9-m4590 :type MA)
           (STORY9-m4593 :type MA)
           (STORY9-m4595 :type MA)
           (STORY9-m4596 :type MA)
           (STORY9-m4598 :type MA)
           (STORY9-m4602 :type MA)
           (STORY9-m4603 :type MA)
           (STORY9-m4606 :type MA)
           (STORY9-m4607 :type MA)
         )
         (:expressions
           ((levin-37-7 STORY9-m4507 STORY9-m4512) :name STORY9-VERB1)
           ((levin-09-1 STORY9-m4529 STORY9-m4531) :name STORY9-VERB2)
           ((levin-37-7 STORY9-m4536 STORY9-m4542) :name STORY9-VERB3)
           ((levin-55-1 STORY9-m4544 STORY9-m4545) :name STORY9-VERB4)
           ((levin-29-3 STORY9-m4547 STORY9-m4550) :name STORY9-VERB5)
           ((levin-11-2 STORY9-m4551 STORY9-m4552) :name STORY9-VERB6)
           ((levin-11-3 STORY9-m4555 STORY9-m4556) :name STORY9-VERB7)
           ((levin-37-7 STORY9-m4560 STORY9-m4566) :name STORY9-VERB8)
           ((levin-13-1 STORY9-m4570 STORY9-m4573) :name STORY9-VERB9)
           ((levin-37-7 STORY9-m4585 STORY9-m4590) :name STORY9-VERB10)
           ((levin-55-1 STORY9-m4595 STORY9-m4596) :name STORY9-VERB11)
           ((levin-11-2 STORY9-m4602 STORY9-m4603) :name STORY9-VERB12)
           ((levin-11-3 STORY9-m4606 STORY9-m4607) :name STORY9-VERB13)
           ((levin-29-3 STORY9-m4617 STORY9-m4618) :name STORY9-VERB14)
           ((levin-13-1 STORY9-m4621 STORY9-m4624) :name STORY9-VERB15)
           ((levin-30-1 STORY9-m4636 STORY9-m4638) :name STORY9-VERB16)
           ((levin-13-5-1 STORY9-m4640 STORY9-m4641) :name STORY9-VERB17)
           ((levin-40-1-2 STORY9-m4642 STORY9-m4650) :name STORY9-VERB18)
           ((levin-30-2 STORY9-m4654 STORY9-m4659) :name STORY9-VERB19)
           ((levin-26-7 STORY9-m4661 STORY9-m4672) :name STORY9-VERB20)
           ((levin-30-1 STORY9-m4673 STORY9-m4675) :name STORY9-VERB21)
           ((levin-37-7 STORY9-m4679 STORY9-m4686) :name STORY9-VERB22)
           ((levin-39-1 STORY9-m4689 STORY9-m4690) :name STORY9-VERB23)
           ((levin-25-4 STORY9-m4691 STORY9-m4695) :name STORY9-VERB24)
           ((levin-26-7 STORY9-m4697 STORY9-m4705) :name STORY9-VERB25)
           ((levin-13-5-2 STORY9-m4710 STORY9-m4712) :name STORY9-VERB26)
         )
       )

     )
   )
)
    