
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-14
     (:discourse
       (:clauses
         (c0 (:s phase1))
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11))

       )
       (:templates
         ;; There was once a very wealthy merchant who had a marvelously beautiful daughter.
         ;; This merchant carried goods to various provinces, and one day he came to a certain kingdom and brought precious cloths to the king as a gift.
         ;; The king said to him: "Why can I not find a bride for myself?"
         ;; The merchant answered: "I have a beautiful daughter, and she is so clever that no matter what a man is thinking, she can guess it."
         ;; The king immediately wrote a letter and called his guards.
         ;; "Go to that merchant's house," he told them, "and deliver this letter to the merchant's daughter."
         ;; The letter said: "Make ready to get married."
         ;; The merchant's daughter took the letter, burst into tears, and prepared to go, taking also her maidservant; and no one could distinguish this maid from the merchant's daughter, they were so like each other.
         ;; They dressed in dresses that were alike and went to the king for the marriage.
         ;; The maid was full of spite, and said: "Let us take a walk on the island."
         ;; They went to the island; there the maidservant gave the merchant's daughter sleeping potions, cut out her eyes, and put them in her pocket.

         (t1 "There was once " (STORY14-m5178 "a very wealthy merchant who had a marvelously beautiful daughter") " " (STORY14-m5179 "a marvelously beautiful daughter") " . ")
         (t2 "" (STORY14-m5180 "This merchant") " carried goods to various provinces , and one day " (STORY14-m5184 "he") " came to a certain kingdom and brought precious cloths to " (STORY14-m5187 "the king") " as a gift . ")
         (t3 "" (STORY14-m5189 "The king") " said to " (STORY14-m5190 "him") " : ' Why can " (STORY14-VERB3 "" (STORY14-m5191 "I") " not find a bride for " (STORY14-m5193 "myself") " " ) "? ' ")
         (t4 "" (STORY14-m5194 "The merchant") " answered : ' " (STORY14-m5195 "I") " have " (STORY14-m5196 "a beautiful daughter") " , and she is so clever that no matter " (STORY14-m5198 "what a man is thinking") " , " (STORY14-m5199 "she") " can guess it . ' ")
         (t5 "" (STORY14-m5201 "The king") " immediately wrote a letter and called his " (STORY14-m5204 "his guards") " . ")
         (t6 "' Go to that merchant 's house , ' " (STORY14-m5207 "he") " told " (STORY14-m5208 "them") " , ' and deliver this letter to " (STORY14-m5210 "the merchant's daughter") " . ' ")
         (t7 "The letter said : ' Make ready to get married . ' ")
         (t8 "" (STORY14-m5213 "The merchant's daughter") " took the letter , burst into tears , and prepared to go , taking also her " (STORY14-m5218 "her maidservant") " ; and no one could distinguish this maid from " (STORY14-m5220 "the merchant's daughter") " , " (STORY14-m5222 "they") " were so like each other . ")
         (t9 "" (STORY14-m5224 "They") " dressed in dresses that were alike and went to the king for the marriage . ")
         (t10 "" (STORY14-m5228 "The maid") " was full of spite , and said : ' Let " (STORY14-m5229 "us") " take a walk on the island . ' ")
         (t11 "" (STORY14-m5232 "They") " went to the island ; there " (STORY14-m5235 "the maidservant") " gave the " (STORY14-m5237 "merchant") " 's daughter sleeping potions , cut out her eyes , and put " (STORY14-m5241 "them") " in her pocket . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY14-m5178 :type MA)
           (STORY14-m5179 :type MA)
           (STORY14-m5180 :type MA)
           (STORY14-m5184 :type MA)
           (STORY14-m5187 :type MA)
           (STORY14-m5189 :type MA)
           (STORY14-m5190 :type MA)
           (STORY14-m5191 :type MA)
           (STORY14-m5193 :type MA)
           (STORY14-m5194 :type MA)
           (STORY14-m5195 :type MA)
           (STORY14-m5196 :type MA)
           (STORY14-m5198 :type MA)
           (STORY14-m5199 :type MA)
           (STORY14-m5201 :type MA)
           (STORY14-m5204 :type MA)
           (STORY14-m5207 :type MA)
           (STORY14-m5208 :type MA)
           (STORY14-m5210 :type MA)
           (STORY14-m5213 :type MA)
           (STORY14-m5218 :type MA)
           (STORY14-m5220 :type MA)
           (STORY14-m5222 :type MA)
           (STORY14-m5224 :type MA)
           (STORY14-m5228 :type MA)
           (STORY14-m5229 :type MA)
           (STORY14-m5232 :type MA)
           (STORY14-m5235 :type MA)
           (STORY14-m5237 :type MA)
           (STORY14-m5241 :type MA)
         )
         (:expressions
           ((levin-11-3 STORY14-m5184 STORY14-m5187) :name STORY14-VERB1)
           ((levin-37-7 STORY14-m5189 STORY14-m5190) :name STORY14-VERB2)
           ((levin-29-4 STORY14-m5191 STORY14-m5193) :name STORY14-VERB3)
           ((levin-29-4 STORY14-m5198 STORY14-m5198) :name STORY14-VERB4)
           ((levin-29-3 STORY14-m5201 STORY14-m5204) :name STORY14-VERB5)
           ((levin-37-2 STORY14-m5207 STORY14-m5208) :name STORY14-VERB6)
           ((levin-11-3 STORY14-m5213 STORY14-m5218) :name STORY14-VERB7)
           ((levin-37-7 STORY14-m5228 STORY14-m5229) :name STORY14-VERB8)
           ((levin-13-1 STORY14-m5235 STORY14-m5237) :name STORY14-VERB9)
         )
       )

     )
   )
)
    