
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-8
     (:discourse
       (:clauses
         (phase1 (:s  t1 t2 t3 t4 t5 t6 t7))

       )
       (:templates
         ;; There was once a king who had three daughters, and such beauties they were as no tongue can tell of nor pen describe.
         ;; Their garden was big and beautiful and they liked to walk there at night.
         ;; A dragon from the Black Sea took to visiting this garden.
         ;; One night the king's daughters tarried in the garden, for they could not tear their eyes away from the flowers; suddenly the dragon appeared and carried them off on his fiery wings.
         ;; The king waited and waited but his daughters did not come back.
         ;; He sent his maidservants to look for them in the garden, but all in vain; the maidservants could not find the princesses.
         ;; The next morning the king proclaimed a state of emergency and a great multitude of people gathered.

         (t1 "There was once " (4634 "a king who had three daughters") "three daughters , and such beauties they were as no tongue can tell of nor pen describe . "
         (t2 "Their garden was big and beautiful and they liked to walk there at night . "
         (t3 "" (4640 "A dragon") "from the Black Sea took to visiting this garden . "
         (t4 "One night the " (4634 "king") "'s daughters tarried in the garden , for they could not tear their eyes away from the flowers ; suddenly " (4640 "the dragon") "appeared and carried them off on his fiery wings . "
         (t5 "" (4634 "The king") "waited and waited but his daughters did not come back . "
         (t6 "" (4634 "He") "sent his " (4646 "his maidservants") "to look for them in the garden , but all in vain ; " (4646 "the maidservants") "could not find the princesses . "
         (t7 "The next morning " (4634 "the king") "proclaimed a state of emergency and " (4649 "a great multitude of people") "gathered . "

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)
         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (m4640 :type MB)
           (m4649 :type GR)
           (m4634 :type MA)
           (m4646 :type GR)
         )
         (:expressions
           ((verb-was m-1 m4634) :name E1)
           ((verb-had m4634 m-1) :name E2)
           ((verb-visiting m4640 m-1) :name E3)
           ((verb-took m4640 m-1) :name E4)
           ((verb-tarried m-1 m4634) :name E5)
           ((verb-appeared m-1 m4640) :name E6)
           ((verb-carried m4640 m-1) :name E7)
           ((verb-waited m-1 m4634) :name E8)
           ((verb-waited m-1 m4634) :name E9)
           ((verb-sent m4634 m4646) :name E10)
           ((verb-look m4646 m-1) :name E11)
           ((verb-find m4646 m-1) :name E12)
           ((verb-proclaimed m4634 m-1) :name E13)
           ((verb-gathered m-1 m4649) :name E14)
         )
       )

     )
   )
)
    