clisp voz-complete-1-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-1-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-2-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-2-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-3-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-3-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-4-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-4-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-5-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-5-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-6-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-6-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-7-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-7-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-8-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-8-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-9-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-9-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-10-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-10-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-11-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-11-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-12-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-12-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-13-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-13-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-14-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-14-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-15-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-15-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-16-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-16-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-17-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-17-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-18-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-18-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-19-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-19-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-20-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-20-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-21-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-21-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-22-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-22-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-23-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-23-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-24-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-24-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-25-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-25-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-26-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-26-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-27-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-27-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-28-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-28-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-29-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-29-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-30-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-30-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-31-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-31-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-32-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-32-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-33-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-33-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-34-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-34-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-35-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-35-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-36-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-36-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-37-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-37-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-38-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-38-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-39-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-39-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-40-levinverb_nofunc_roleexp_prep_syn.lisp > voz-complete-40-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-complete-1-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-1-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-2-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-2-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-3-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-3-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-4-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-4-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-5-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-5-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-6-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-6-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-7-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-7-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-8-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-8-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-9-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-9-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-10-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-10-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-11-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-11-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-12-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-12-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-13-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-13-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-14-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-14-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-15-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-15-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-16-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-16-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-17-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-17-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-18-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-18-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-19-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-19-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-20-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-20-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-21-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-21-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-22-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-22-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-23-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-23-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-24-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-24-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-25-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-25-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-26-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-26-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-27-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-27-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-28-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-28-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-29-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-29-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-30-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-30-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-31-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-31-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-32-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-32-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-33-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-33-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-34-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-34-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-35-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-35-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-36-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-36-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-37-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-37-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-38-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-38-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-39-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-39-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-40-levinverb_functs_roleexp_prep_syn.lisp > voz-complete-40-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-complete-1-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-1-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-2-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-2-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-3-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-3-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-4-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-4-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-5-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-5-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-6-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-6-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-7-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-7-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-8-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-8-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-9-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-9-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-10-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-10-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-11-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-11-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-12-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-12-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-13-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-13-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-14-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-14-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-15-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-15-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-16-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-16-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-17-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-17-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-18-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-18-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-19-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-19-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-20-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-20-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-21-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-21-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-22-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-22-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-23-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-23-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-24-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-24-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-25-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-25-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-26-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-26-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-27-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-27-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-28-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-28-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-29-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-29-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-30-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-30-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-31-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-31-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-32-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-32-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-33-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-33-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-34-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-34-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-35-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-35-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-36-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-36-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-37-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-37-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-38-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-38-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-39-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-39-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-40-levinverb_nofunc_roleexp_prep_voz.lisp > voz-complete-40-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-complete-1-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-1-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-2-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-2-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-3-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-3-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-4-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-4-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-5-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-5-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-6-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-6-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-7-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-7-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-8-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-8-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-9-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-9-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-10-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-10-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-11-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-11-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-12-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-12-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-13-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-13-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-14-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-14-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-15-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-15-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-16-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-16-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-17-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-17-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-18-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-18-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-19-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-19-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-20-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-20-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-21-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-21-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-22-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-22-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-23-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-23-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-24-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-24-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-25-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-25-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-26-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-26-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-27-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-27-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-28-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-28-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-29-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-29-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-30-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-30-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-31-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-31-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-32-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-32-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-33-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-33-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-34-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-34-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-35-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-35-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-36-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-36-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-37-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-37-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-38-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-38-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-39-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-39-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-complete-40-levinverb_functs_roleexp_prep_voz.lisp > voz-complete-40-levinverb_functs_roleexp_prep_voz.lisp.txt &
