clisp voz-eval-1-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-1-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-2-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-2-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-3-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-3-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-4-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-4-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-5-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-5-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-6-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-6-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-7-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-7-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-8-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-8-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-9-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-9-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-10-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-10-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-11-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-11-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-12-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-12-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-13-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-13-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-14-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-14-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-15-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-15-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-16-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-16-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-17-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-17-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-18-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-18-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-19-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-19-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-20-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-20-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-21-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-21-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-22-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-22-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-23-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-23-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-24-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-24-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-25-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-25-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-26-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-26-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-27-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-27-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-28-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-28-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-29-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-29-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-30-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-30-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-31-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-31-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-32-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-32-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-33-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-33-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-34-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-34-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-35-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-35-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-36-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-36-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-37-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-37-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-38-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-38-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-39-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-39-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-40-levinverb_nofunc_roleexp_prep_syn.lisp > voz-eval-40-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-1-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-1-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-2-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-2-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-3-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-3-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-4-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-4-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-5-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-5-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-6-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-6-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-7-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-7-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-8-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-8-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-9-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-9-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-10-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-10-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-11-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-11-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-12-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-12-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-13-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-13-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-14-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-14-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-15-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-15-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-16-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-16-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-17-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-17-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-18-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-18-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-19-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-19-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-20-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-20-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-21-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-21-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-22-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-22-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-23-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-23-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-24-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-24-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-25-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-25-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-26-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-26-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-27-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-27-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-28-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-28-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-29-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-29-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-30-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-30-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-31-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-31-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-32-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-32-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-33-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-33-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-34-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-34-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-35-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-35-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-36-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-36-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-37-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-37-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-38-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-38-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-39-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-39-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-full-40-levinverb_nofunc_roleexp_prep_syn.lisp > voz-full-40-levinverb_nofunc_roleexp_prep_syn.lisp.txt &
clisp voz-eval-1-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-1-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-2-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-2-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-3-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-3-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-4-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-4-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-5-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-5-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-6-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-6-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-7-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-7-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-8-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-8-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-9-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-9-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-10-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-10-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-11-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-11-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-12-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-12-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-13-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-13-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-14-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-14-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-15-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-15-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-16-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-16-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-17-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-17-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-18-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-18-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-19-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-19-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-20-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-20-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-21-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-21-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-22-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-22-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-23-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-23-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-24-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-24-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-25-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-25-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-26-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-26-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-27-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-27-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-28-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-28-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-29-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-29-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-30-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-30-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-31-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-31-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-32-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-32-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-33-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-33-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-34-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-34-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-35-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-35-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-36-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-36-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-37-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-37-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-38-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-38-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-39-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-39-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-40-levinverb_functs_roleexp_prep_syn.lisp > voz-eval-40-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-1-levinverb_functs_roleexp_prep_syn.lisp > voz-full-1-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-2-levinverb_functs_roleexp_prep_syn.lisp > voz-full-2-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-3-levinverb_functs_roleexp_prep_syn.lisp > voz-full-3-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-4-levinverb_functs_roleexp_prep_syn.lisp > voz-full-4-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-5-levinverb_functs_roleexp_prep_syn.lisp > voz-full-5-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-6-levinverb_functs_roleexp_prep_syn.lisp > voz-full-6-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-7-levinverb_functs_roleexp_prep_syn.lisp > voz-full-7-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-8-levinverb_functs_roleexp_prep_syn.lisp > voz-full-8-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-9-levinverb_functs_roleexp_prep_syn.lisp > voz-full-9-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-10-levinverb_functs_roleexp_prep_syn.lisp > voz-full-10-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-11-levinverb_functs_roleexp_prep_syn.lisp > voz-full-11-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-12-levinverb_functs_roleexp_prep_syn.lisp > voz-full-12-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-13-levinverb_functs_roleexp_prep_syn.lisp > voz-full-13-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-14-levinverb_functs_roleexp_prep_syn.lisp > voz-full-14-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-15-levinverb_functs_roleexp_prep_syn.lisp > voz-full-15-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-16-levinverb_functs_roleexp_prep_syn.lisp > voz-full-16-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-17-levinverb_functs_roleexp_prep_syn.lisp > voz-full-17-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-18-levinverb_functs_roleexp_prep_syn.lisp > voz-full-18-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-19-levinverb_functs_roleexp_prep_syn.lisp > voz-full-19-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-20-levinverb_functs_roleexp_prep_syn.lisp > voz-full-20-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-21-levinverb_functs_roleexp_prep_syn.lisp > voz-full-21-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-22-levinverb_functs_roleexp_prep_syn.lisp > voz-full-22-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-23-levinverb_functs_roleexp_prep_syn.lisp > voz-full-23-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-24-levinverb_functs_roleexp_prep_syn.lisp > voz-full-24-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-25-levinverb_functs_roleexp_prep_syn.lisp > voz-full-25-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-26-levinverb_functs_roleexp_prep_syn.lisp > voz-full-26-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-27-levinverb_functs_roleexp_prep_syn.lisp > voz-full-27-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-28-levinverb_functs_roleexp_prep_syn.lisp > voz-full-28-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-29-levinverb_functs_roleexp_prep_syn.lisp > voz-full-29-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-30-levinverb_functs_roleexp_prep_syn.lisp > voz-full-30-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-31-levinverb_functs_roleexp_prep_syn.lisp > voz-full-31-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-32-levinverb_functs_roleexp_prep_syn.lisp > voz-full-32-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-33-levinverb_functs_roleexp_prep_syn.lisp > voz-full-33-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-34-levinverb_functs_roleexp_prep_syn.lisp > voz-full-34-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-35-levinverb_functs_roleexp_prep_syn.lisp > voz-full-35-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-36-levinverb_functs_roleexp_prep_syn.lisp > voz-full-36-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-37-levinverb_functs_roleexp_prep_syn.lisp > voz-full-37-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-38-levinverb_functs_roleexp_prep_syn.lisp > voz-full-38-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-39-levinverb_functs_roleexp_prep_syn.lisp > voz-full-39-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-full-40-levinverb_functs_roleexp_prep_syn.lisp > voz-full-40-levinverb_functs_roleexp_prep_syn.lisp.txt &
clisp voz-eval-1-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-1-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-2-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-2-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-3-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-3-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-4-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-4-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-5-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-5-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-6-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-6-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-7-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-7-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-8-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-8-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-9-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-9-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-10-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-10-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-11-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-11-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-12-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-12-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-13-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-13-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-14-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-14-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-15-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-15-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-16-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-16-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-17-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-17-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-18-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-18-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-19-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-19-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-20-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-20-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-21-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-21-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-22-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-22-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-23-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-23-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-24-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-24-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-25-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-25-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-26-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-26-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-27-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-27-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-28-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-28-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-29-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-29-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-30-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-30-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-31-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-31-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-32-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-32-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-33-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-33-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-34-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-34-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-35-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-35-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-36-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-36-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-37-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-37-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-38-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-38-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-39-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-39-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-40-levinverb_nofunc_roleexp_prep_voz.lisp > voz-eval-40-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-1-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-1-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-2-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-2-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-3-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-3-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-4-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-4-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-5-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-5-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-6-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-6-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-7-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-7-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-8-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-8-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-9-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-9-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-10-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-10-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-11-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-11-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-12-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-12-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-13-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-13-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-14-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-14-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-15-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-15-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-16-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-16-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-17-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-17-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-18-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-18-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-19-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-19-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-20-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-20-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-21-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-21-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-22-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-22-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-23-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-23-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-24-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-24-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-25-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-25-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-26-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-26-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-27-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-27-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-28-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-28-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-29-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-29-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-30-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-30-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-31-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-31-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-32-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-32-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-33-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-33-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-34-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-34-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-35-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-35-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-36-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-36-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-37-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-37-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-38-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-38-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-39-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-39-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-full-40-levinverb_nofunc_roleexp_prep_voz.lisp > voz-full-40-levinverb_nofunc_roleexp_prep_voz.lisp.txt &
clisp voz-eval-1-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-1-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-2-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-2-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-3-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-3-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-4-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-4-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-5-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-5-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-6-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-6-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-7-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-7-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-8-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-8-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-9-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-9-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-10-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-10-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-11-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-11-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-12-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-12-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-13-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-13-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-14-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-14-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-15-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-15-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-16-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-16-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-17-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-17-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-18-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-18-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-19-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-19-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-20-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-20-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-21-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-21-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-22-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-22-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-23-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-23-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-24-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-24-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-25-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-25-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-26-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-26-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-27-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-27-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-28-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-28-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-29-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-29-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-30-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-30-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-31-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-31-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-32-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-32-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-33-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-33-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-34-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-34-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-35-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-35-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-36-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-36-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-37-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-37-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-38-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-38-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-39-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-39-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-eval-40-levinverb_functs_roleexp_prep_voz.lisp > voz-eval-40-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-1-levinverb_functs_roleexp_prep_voz.lisp > voz-full-1-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-2-levinverb_functs_roleexp_prep_voz.lisp > voz-full-2-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-3-levinverb_functs_roleexp_prep_voz.lisp > voz-full-3-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-4-levinverb_functs_roleexp_prep_voz.lisp > voz-full-4-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-5-levinverb_functs_roleexp_prep_voz.lisp > voz-full-5-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-6-levinverb_functs_roleexp_prep_voz.lisp > voz-full-6-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-7-levinverb_functs_roleexp_prep_voz.lisp > voz-full-7-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-8-levinverb_functs_roleexp_prep_voz.lisp > voz-full-8-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-9-levinverb_functs_roleexp_prep_voz.lisp > voz-full-9-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-10-levinverb_functs_roleexp_prep_voz.lisp > voz-full-10-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-11-levinverb_functs_roleexp_prep_voz.lisp > voz-full-11-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-12-levinverb_functs_roleexp_prep_voz.lisp > voz-full-12-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-13-levinverb_functs_roleexp_prep_voz.lisp > voz-full-13-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-14-levinverb_functs_roleexp_prep_voz.lisp > voz-full-14-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-15-levinverb_functs_roleexp_prep_voz.lisp > voz-full-15-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-16-levinverb_functs_roleexp_prep_voz.lisp > voz-full-16-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-17-levinverb_functs_roleexp_prep_voz.lisp > voz-full-17-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-18-levinverb_functs_roleexp_prep_voz.lisp > voz-full-18-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-19-levinverb_functs_roleexp_prep_voz.lisp > voz-full-19-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-20-levinverb_functs_roleexp_prep_voz.lisp > voz-full-20-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-21-levinverb_functs_roleexp_prep_voz.lisp > voz-full-21-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-22-levinverb_functs_roleexp_prep_voz.lisp > voz-full-22-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-23-levinverb_functs_roleexp_prep_voz.lisp > voz-full-23-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-24-levinverb_functs_roleexp_prep_voz.lisp > voz-full-24-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-25-levinverb_functs_roleexp_prep_voz.lisp > voz-full-25-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-26-levinverb_functs_roleexp_prep_voz.lisp > voz-full-26-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-27-levinverb_functs_roleexp_prep_voz.lisp > voz-full-27-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-28-levinverb_functs_roleexp_prep_voz.lisp > voz-full-28-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-29-levinverb_functs_roleexp_prep_voz.lisp > voz-full-29-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-30-levinverb_functs_roleexp_prep_voz.lisp > voz-full-30-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-31-levinverb_functs_roleexp_prep_voz.lisp > voz-full-31-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-32-levinverb_functs_roleexp_prep_voz.lisp > voz-full-32-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-33-levinverb_functs_roleexp_prep_voz.lisp > voz-full-33-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-34-levinverb_functs_roleexp_prep_voz.lisp > voz-full-34-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-35-levinverb_functs_roleexp_prep_voz.lisp > voz-full-35-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-36-levinverb_functs_roleexp_prep_voz.lisp > voz-full-36-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-37-levinverb_functs_roleexp_prep_voz.lisp > voz-full-37-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-38-levinverb_functs_roleexp_prep_voz.lisp > voz-full-38-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-39-levinverb_functs_roleexp_prep_voz.lisp > voz-full-39-levinverb_functs_roleexp_prep_voz.lisp.txt &
clisp voz-full-40-levinverb_functs_roleexp_prep_voz.lisp > voz-full-40-levinverb_functs_roleexp_prep_voz.lisp.txt &
