;;; -*- Mode: LISP; Syntax: Common-lisp; Package: USER; Base: 10 -*-
#-Symbolics
;;(in-package sme::*the-user-package*)		;defPackage
(in-package "COMMON-LISP-USER")		;defPackage

;;;; Predicate language definition file
(sme:defPredicate have (entity entity) relation)
(sme:defPredicate in (entity entity) relation)

(sme:defPredicate verb (entity entity) relation :expression-type action)

(sme:defPredicate levin-09-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-09-10 (entity entity) relation :expression-type action)
(sme:defPredicate levin-09-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-09-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-09-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-09-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-09-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-09-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-09-8 (entity entity) relation :expression-type action)
(sme:defPredicate levin-09-9 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-4-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-4-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-8 (entity entity) relation :expression-type action)
(sme:defPredicate levin-10-9 (entity entity) relation :expression-type action)
(sme:defPredicate levin-11-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-11-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-11-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-11-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-11-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-12 (entity entity) relation :expression-type action)
(sme:defPredicate levin-13-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-13-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-13-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-13-4-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-13-4-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-13-5-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-13-5-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-13-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-13-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-14 (entity entity) relation :expression-type action)
(sme:defPredicate levin-15-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-15-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-16 (entity entity) relation :expression-type action)
(sme:defPredicate levin-17-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-17-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-18-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-18-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-18-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-18-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-19 (entity entity) relation :expression-type action)
(sme:defPredicate levin-20 (entity entity) relation :expression-type action)
(sme:defPredicate levin-21-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-21-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-22-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-22-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-22-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-22-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-22-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-23-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-23-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-23-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-23-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-24 (entity entity) relation :expression-type action)
(sme:defPredicate levin-25-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-25-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-25-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-25-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-26-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-26-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-26-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-26-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-26-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-26-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-26-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-27 (entity entity) relation :expression-type action)
(sme:defPredicate levin-28 (entity entity) relation :expression-type action)
(sme:defPredicate levin-29-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-29-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-29-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-29-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-29-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-29-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-29-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-29-8 (entity entity) relation :expression-type action)
(sme:defPredicate levin-30-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-30-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-30-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-30-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-31-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-31-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-31-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-31-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-32-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-32-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-33-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-34 (entity entity) relation :expression-type action)
(sme:defPredicate levin-35-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-35-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-35-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-35-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-35-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-35-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-36-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-36-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-36-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-37-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-37-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-37-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-37-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-37-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-37-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-37-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-37-8 (entity entity) relation :expression-type action)
(sme:defPredicate levin-37-9 (entity entity) relation :expression-type action)
(sme:defPredicate levin-38 (entity entity) relation :expression-type action)
(sme:defPredicate levin-39-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-39-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-39-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-39-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-39-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-39-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-39-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-1-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-1-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-1-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-3-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-3-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-3-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-8-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-8-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-8-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-40-8-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-41-1-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-41-1-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-41-2-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-41-2-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-41-3-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-41-3-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-41-3-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-42-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-42-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-43-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-43-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-43-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-43-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-44 (entity entity) relation :expression-type action)
(sme:defPredicate levin-45-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-45-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-45-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-45-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-45-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-45-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-46 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-5-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-5-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-5-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-47-8 (entity entity) relation :expression-type action)
(sme:defPredicate levin-48-1-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-48-1-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-48-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-48-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-49 (entity entity) relation :expression-type action)
(sme:defPredicate levin-50 (entity entity) relation :expression-type action)
(sme:defPredicate levin-51-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-51-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-51-3-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-51-3-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-51-4-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-51-4-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-51-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-51-6 (entity entity) relation :expression-type action)
(sme:defPredicate levin-51-7 (entity entity) relation :expression-type action)
(sme:defPredicate levin-52 (entity entity) relation :expression-type action)
(sme:defPredicate levin-53-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-53-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-54-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-54-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-54-3 (entity entity) relation :expression-type action)
(sme:defPredicate levin-54-4 (entity entity) relation :expression-type action)
(sme:defPredicate levin-54-5 (entity entity) relation :expression-type action)
(sme:defPredicate levin-55-1 (entity entity) relation :expression-type action)
(sme:defPredicate levin-55-2 (entity entity) relation :expression-type action)
(sme:defPredicate levin-56 (entity entity) relation :expression-type action)
(sme:defPredicate levin-57 (entity entity) relation :expression-type action)

(sme:defPredicate happy (entity) attribute :expression-type emotion)
(sme:defPredicate sad (entity) attribute :expression-type emotion)

(sme:defPredicate young (entity) attribute)
(sme:defPredicate old (entity) attribute)

(sme:defPredicate roleHero (entity) attribute :expression-type role)
(sme:defPredicate roleVillain (entity) attribute :expression-type role)
(sme:defPredicate roleTester (entity) attribute :expression-type role)
(sme:defPredicate rolePrize (entity) attribute :expression-type role)
(sme:defPredicate roleFalseHero (entity) attribute :expression-type role)
(sme:defPredicate roleOther (entity) attribute :expression-type role)
(sme:defPredicate roleNA (entity) attribute :expression-type role)


(sme:defPredicate funcFiller-alpha (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-beta (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-gamma (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-delta (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-epsilon (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-zeta (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-eta (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-theta (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-lambda (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-A (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-a (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-depart (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-B (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-C (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-D (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-E (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-F (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-G (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-H (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-I (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-J (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-K (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-return (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-Pr (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-Rs (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-Ex (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-o (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-L (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-M (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-N (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-Q (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-T (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-U (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-W (entity) relation :expression-type filler) 
(sme:defPredicate funcFiller-w (entity) relation :expression-type filler) 