
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-19
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1 t2 t3 t4))
         (phase2 (:s  t5))

       )
       (:templates
         ;; A long time ago, near the capital city, lived a family with their son.
         ;; A dragon terrorized the region.
         ;; The dragon wanted to take over the family's lands.
         ;; One day the parents went to the market.
         ;; He wanted revenge and ran after the dragon but got lost.

         (t1 "A long time ago , near the capital city , lived " (STORY19-m1000 "a family") " with " (STORY19-m1001 "their son") " . ")
         (t2 "" (STORY19-m1002 "A dragon") " terrorized the region . ")
         (t3 "" (STORY19-m1002 "The dragon") " wanted to take over the family 's lands . ")
         (t4 "One day " (STORY19-m1000 "the parents") " went to the market . ")
         (t1001 (STORY19-EXTRA1  (STORY19-m1001 "their son") " is the " (Other "Other") ) ".")
         (t1002 (STORY19-EXTRA2  (STORY19-m1002 "The dragon") " is the " (Other "Other") ) ".")
         (t5 "" (STORY19-m1001 "He") " wanted revenge and ran after the dragon but got lost . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY19-m1000 :type animate)
           (STORY19-m1001 :type animate)
           (STORY19-m1002 :type animate)
         )
         (:expressions
           ((roleOther STORY19-m1001) :name STORY19-EXTRA0)
           ((roleOther STORY19-m1002) :name STORY19-EXTRA1)
         )
       )
       (phase2
         (:entities
           (STORY19-m1000 :type animate)
           (STORY19-m1001 :type animate)
           (STORY19-m1002 :type animate)
         )
         (:expressions
         )
       )

     )
   )
)
    