
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-8
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2 phase3 phase4))
         (phase1 (:s  t1 t2 t3 t4 t5))
         (phase2 (:s  t6 t7 t8 t9))
         (phase3 (:s  t10 t11 t12 t13 t14 t15 t16 t17 t18))
         (phase4 (:s  t19 t20 t21 t22 t23 t24 t25))

       )
       (:templates
         ;; Once upon a time there was a happy queen with a son and a daughter.
         ;; In the kingdom lived a witch that was jealous of their happiness.
         ;; The witch devised a plan to ruin their family.
         ;; The witch visited them.
         ;; She gave the prince a ring and told him that he would be happy as long as he married a girl who the ring would fit.
         ;; One day, his sister saw the ring and tried it on.
         ;; The ring fit perfectly and she couldn't take it off.
         ;; He immediately asked her to marry him.
         ;; The girl panicked and escaped the palace.
         ;; Inside there was a maiden.
         ;; The maiden was the daughter of a witch.
         ;; The maiden was lonely and asked the girl to be friends.
         ;; The girl agreed.
         ;; They talked for hours.
         ;; The next day the maiden asked the girl for help braiding a handkerchief.
         ;; The girl agreed.
         ;; Together they braided a beautiful handkerchief.
         ;; The maiden asked the girl to keep it as a token of their friendship.
         ;; Then the witch appeared from the sky.
         ;; The witch smelled the girl and wanted to eat her.
         ;; The maiden hid the girl from the witch.
         ;; When she couldn't find her, the witch left and the girl escaped safely.
         ;; The girl arrived home and found her brother sobbing in her absence.
         ;; Her brother apologized to her for his behavior.
         ;; Eventually both the brother and sister married royalty from neighboring kingdoms and were happy ever after.

         (t1 "Once upon a time there was a happy queen with a son and a daughter . ")
         (t2 "In the kingdom lived a witch that was jealous of their happiness . ")
         (t3 "The witch devised a plan to ruin their family . ")
         (t4 "The witch visited them . ")
         (t5 "She gave the prince a ring and told him that he would be happy as long as he married a girl who the ring would fit . ")
         (t6 "One day , his sister saw the ring and tried it on . ")
         (t7 "The ring fit perfectly and she could n't take it off . ")
         (t8 "He immediately asked her to marry him . ")
         (t9 "The girl panicked and escaped the palace . ")
         (t10 "Inside there was a maiden . ")
         (t11 "The maiden was the daughter of a witch . ")
         (t12 "The maiden was lonely and asked the girl to be friends . ")
         (t13 "The girl agreed . ")
         (t14 "They talked for hours . ")
         (t15 "The next day the maiden asked the girl for help braiding a handkerchief . ")
         (t16 "The girl agreed . ")
         (t17 "Together they braided a beautiful handkerchief . ")
         (t18 "The maiden asked the girl to keep it as a token of their friendship . ")
         (t19 "Then the witch appeared from the sky . ")
         (t20 "The witch smelled the girl and wanted to eat her . ")
         (t21 "The maiden hid the girl from the witch . ")
         (t22 "When she could n't find her , the witch left and the girl escaped safely . ")
         (t23 "The girl arrived home and found her brother sobbing in her absence . ")
         (t24 "Her brother apologized to her for his behavior . ")
         (t25 "Eventually both the brother and sister married royalty from neighboring kingdoms and were happy ever after . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )
       (phase3
         (:entities
         )
         (:expressions
         )
       )
       (phase4
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    