
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-19
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2 phase3 phase4))
         (phase1 (:s  t1 t2 t3 t4))
         (phase2 (:s  t5))
         (phase3 (:s  t6 t7))
         (phase4 (:s  t8 t9 t10))

       )
       (:templates
         ;; A long time ago, near the capital city, lived a family with their son.
         ;; A dragon terrorized the region.
         ;; The dragon wanted to take over the family's lands.
         ;; One day the parents went to the market.
         ;; He wanted revenge and ran after the dragon but got lost.
         ;; The dragon and the boy fought for a long time.
         ;; The dragon couldn't see the boy in the darkness and he managed to struck him in the head and kill him.
         ;; The boy and his bride returned to his family's lands.
         ;; His parents were lamenting his death but were overjoyed to see him alive.
         ;; With their newfound wealth, they rebuilt their house and lived happily.

         (t1 "A long time ago , near the capital city , lived a family with their son . ")
         (t2 "A dragon terrorized the region . ")
         (t3 "The dragon wanted to take over the family 's lands . ")
         (t4 "One day the parents went to the market . ")
         (t5 "He wanted revenge and ran after the dragon but got lost . ")
         (t6 "The dragon and the boy fought for a long time . ")
         (t7 "The dragon could n't see the boy in the darkness and he managed to struck him in the head and kill him . ")
         (t8 "The boy and his bride returned to his family 's lands . ")
         (t9 "His parents were lamenting his death but were overjoyed to see him alive . ")
         (t10 "With their newfound wealth , they rebuilt their house and lived happily . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )
       (phase3
         (:entities
         )
         (:expressions
         )
       )
       (phase4
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    