
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-14
     (:discourse
       (:clauses
         (c0 (:s phase1))
         (phase1 (:s  t1 t2 t3 t4))

       )
       (:templates
         ;; A poor laborer lived in a small town.
         ;; His master's crops had been ruined and there was no work for him.
         ;; Eventually his master told him he had to let him go.
         ;; The laborer was very understanding.

         (t1 "" (STORY14-m1002 "A poor laborer") " lived in a small town . ")
         (t2 "" (STORY14-m1000 "His master's crops") " had been ruined and there was no work for him . ")
         (t3 "Eventually " (STORY14-m1001 "his master") " told " (STORY14-m1002 "him") " he had to let him go . ")
         (t4 "" (STORY14-m1002 "The laborer") " was very understanding . ")
         (t1001 (STORY14-EXTRA1  (STORY14-m1000 "His master's crops") " is the " (NA "NA") ) ".")
         (t1002 (STORY14-EXTRA2  (STORY14-m1001 "his master") " is the " (NA "NA") ) ".")
         (t1003 (STORY14-EXTRA3  (STORY14-m1002 "The laborer") " is the " (NA "NA") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY14-m1000 :type NA)
           (STORY14-m1001 :type NA)
           (STORY14-m1002 :type NA)
         )
         (:expressions
           ((levin-37-2 STORY14-m1001 STORY14-m1002) :name STORY14-VERB1)
           ((roleNA STORY14-m1000) :name STORY14-EXTRA0)
           ((roleNA STORY14-m1001) :name STORY14-EXTRA1)
           ((roleNA STORY14-m1002) :name STORY14-EXTRA2)
         )
       )

     )
   )
)
    