
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-24
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2 phase3 phase4))
         (phase1 (:s  t1 t2 t3 t4))
         (phase2 (:s  t5 t6 t7))
         (phase3 (:s  t8 t9))
         (phase4 (:s  t10))

       )
       (:templates
         ;; Once upon a time there was a king who had three daughters.
         ;; Their mother died at childbirth.
         ;; The father, zealous of his daughters locked them in a tower of the palace.
         ;; One day, the girls escaped and ventured into one of the palace's gardens.
         ;; The king issued a call to all the knights of the kingdom.
         ;; Three heroes offered themselves to rescue the princesses.
         ;; They got weapons and armor and departed to encounter the dragon.
         ;; Each knight succeeded and cut a dragon's head.
         ;; They rescued the princesses from the dragon's den.
         ;; The king rewarded them with riches and made them noblemen.

         (t1 "Once upon a time there was a king who had three daughters . ")
         (t2 "Their mother died at childbirth . ")
         (t3 "The father , zealous of his daughters locked them in a tower of the palace . ")
         (t4 "One day , the girls escaped and ventured into one of the palace 's gardens . ")
         (t5 "The king issued a call to all the knights of the kingdom . ")
         (t6 "Three heroes offered themselves to rescue the princesses . ")
         (t7 "They got weapons and armor and departed to encounter the dragon . ")
         (t8 "Each knight succeeded and cut a dragon 's head . ")
         (t9 "They rescued the princesses from the dragon 's den . ")
         (t10 "The king rewarded them with riches and made them noblemen . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )
       (phase3
         (:entities
         )
         (:expressions
         )
       )
       (phase4
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    