
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-15
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2))
         (phase1 (:s  t1 t2 t3))
         (phase2 (:s  t4 t5 t6))

       )
       (:templates
         ;; A woman was once kidnapped by a bear.
         ;; The woman gave birth to a bearlet who was half-boy and half-bear.
         ;; Eventually, the woman was able to escape and took the boy with her.
         ;; He had a plan to get rid of the bearlet.
         ;; He told the bearlet that he would only let him stay if he got rid of the water spirits in the lake.
         ;; The bearlet left not knowing what to do.

         (t1 "A woman was once kidnapped by " (STORY15-m1000 "a bear") " . ")
         (t2 "" (STORY15-m1001 "The woman") " gave birth to " (STORY15-m1002 "a bearlet") " who was half-boy and half-bear . ")
         (t3 "Eventually , the woman was able to escape and took " (STORY15-m1002 "the boy") " with her . ")
         (t1001 (STORY15-EXTRA1  (STORY15-m1000 "a bear") " is the " (Other "Other") ) ".")
         (t1002 (STORY15-EXTRA2  (STORY15-m1002 "the boy") " is the " (Other "Other") ) ".")
         (t4 "" (STORY15-m1004 "He") " had a plan to get rid of the bearlet . ")
         (t5 "" (STORY15-m1004 "He") " told " (STORY15-m1002 "the bearlet") " that he would only let him stay if " (STORY15-VERB2 "" (STORY15-m1002 "he") " got rid of the water " (STORY15-m1005 "spirits") " " ) "in the lake . ")
         (t6 "" (STORY15-m1002 "The bearlet") " left not knowing what to do . ")
         (t1003 (STORY15-EXTRA3  (STORY15-m1004 "He") " is the " (Other "Other") ) ".")
         (t1004 (STORY15-EXTRA4  (STORY15-m1005 "spirits") " is the " (Other "Other") ) ".")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
           (STORY15-m1000 :type animate)
           (STORY15-m1001 :type animate)
           (STORY15-m1002 :type animate)
         )
         (:expressions
           ((roleOther STORY15-m1000) :name STORY15-EXTRA0)
           ((roleOther STORY15-m1002) :name STORY15-EXTRA1)
         )
       )
       (phase2
         (:entities
           (STORY15-m1000 :type animate)
           (STORY15-m1001 :type animate)
           (STORY15-m1002 :type animate)
           (STORY15-m1004 :type animate)
           (STORY15-m1005 :type animate)
         )
         (:expressions
           ((levin-37-2 STORY15-m1004 STORY15-m1002) :name STORY15-VERB1)
           ((levin-13-5-1 STORY15-m1002 STORY15-m1005) :name STORY15-VERB2)
           ((roleOther STORY15-m1004) :name STORY15-EXTRA2)
           ((roleOther STORY15-m1005) :name STORY15-EXTRA3)
         )
       )

     )
   )
)
    