
;; --------------------------------------------------------------------
;; This file has been automatically generated by Voz
;; Josep Valls-Vargas
;; Jichen Zhu
;; Santiago Ontanon
;; --------------------------------------------------------------------

(setf *story*
  '(STORY-38
     (:discourse
       (:clauses
         (c0 (:s phase1 phase2 phase3 phase4))
         (phase1 (:s  t1 t2 t3))
         (phase2 (:s  t4 t5 t6))
         (phase3 (:s  t7 t8 t9))
         (phase4 (:s  t10 t11))

       )
       (:templates
         ;; Once there was a beautiful princess.
         ;; For some unknown reason she was very sad.
         ;; Her father sent a call to figure out why she was always sad.
         ;; A clever farmer heard about the call.
         ;; He decided to go talk to a witch.
         ;; He packed his things and departed.
         ;; She wanted to play some games of cards.
         ;; The clever farmer won all of the games.
         ;; The witch gave the farmer a magic handkerchief for the princess.
         ;; When the princes saw the handkerchief she started smiling immediately.
         ;; They got married and lived happily ever after.

         (t1 "Once there was a beautiful princess . ")
         (t2 "For some unknown reason she was very sad . ")
         (t3 "Her father sent a call to figure out why she was always sad . ")
         (t4 "A clever farmer heard about the call . ")
         (t5 "He decided to go talk to a witch . ")
         (t6 "He packed his things and departed . ")
         (t7 "She wanted to play some games of cards . ")
         (t8 "The clever farmer won all of the games . ")
         (t9 "The witch gave the farmer a magic handkerchief for the princess . ")
         (t10 "When the princes saw the handkerchief she started smiling immediately . ")
         (t11 "They got married and lived happily ever after . ")

       )
     )
     (:structure
       
       (common
         (:entities
           (human :type animate)
           (MA :type human)
           (FE :type human)
           (anthropomorphized :type animate)
           (AA :type anthropomorphized)
           (AO :type anthropomorphized)
           (othera :type animate)
           (GR :type othera)
           (MB :type anthropomorphized)
           (PA :type entity)
           (AN :type othera)
           (HA :type entity)
           (OB :type inanimate)
           (SC :type inanimate)
           (PO :type inanimate)
           (setting :type entity)
           (SS :type setting)
           (ST :type setting)
           (NC :type entity)
           (NA :type entity)
           (m-1 :type NA)

         )
         (:expressions
         )
       )
      
       (phase1
         (:entities
         )
         (:expressions
         )
       )
       (phase2
         (:entities
         )
         (:expressions
         )
       )
       (phase3
         (:entities
         )
         (:expressions
         )
       )
       (phase4
         (:entities
         )
         (:expressions
         )
       )

     )
   )
)
    